tiiuae/ghaf

README.md

Add directory structure to README.md

---

README.md

Instructions on how to add new pages to the book
and how to organize your content to make topics clear.
Next iteration: add new top-level folders to src/,
link with SG and glossary, new contributing page (site).

Add Working with Files and Managing Content to README

---

src/SUMMARY.md
src/scs/pki.md

Just the intro. More to be added. 
Signed-off-by: Aleksandr Tserepov-Savolainen <alextserepov@gmail.com>

Initial commit of PKI chapter skeleton

---

src/scs/scs.md
src/scs/slsa-framework.md

Signed-off-by: Aleksandr Tserepov-Savolainen <alextserepov@gmail.com>

Trying to fix broken links / imgs.

---

src/scs/pki.md

- adding short text on YubiHSM usage
Signed-off-by: Aleksandr Tserepov-Savolainen <alextserepov@gmail.com>

CommentFix

---

src/scs/pki.md

Signed-off-by: Aleksandr Tserepov-Savolainen <aleksandr.tserepov-savolainen@unikie.com>

Fix small typo in PKI

---

src/scs/slsa-framework.md

- TODO: Add links
Signed-off-by: Aleksandr Tserepov-Savolainen <aleksandr.tserepov-savolainen@unikie.com>

Initial SLSA Requirements table

---

.git-blame-ignore-revs
README.md
doc.nix
flake.lock
flake.nix
modules/hardware/nvidia-jetson-orin.nix
targets.nix

Add simple flake outputs for NixOS based setup. Doesn't yet do anything

Add simple flake outputs for NixOS based setup

---

CONTRIBUTING.md
docs/src/SUMMARY.md
docs/src/appendices/contributing_doc.md

Docs: fix links and content

---

README.md
docs/src/SUMMARY.md
docs/src/build_config/cross_compilation.md

Signed-off-by: Brian McGillion <brian.mcgillion@tii.ae>

Add some information on cross compilation

---

README.md
docs/README.md

Signed-off-by: Brian McGillion <brian.mcgillion@tii.ae>

Fix a minor rebase issue

---

docs/src/scs/pki.md

Signed-off-by: Aleksandr Tserepov-Savolainen <aleksandr.tserepov-savolainen@unikie.com>

Docs: Add HSM feature table

---

README.md
flake.nix
modules/development/ssh.nix
targets/default.nix
targets/nvidia-jetson-orin.nix

Please use "Merge commit" when merging this PR, so my GPG signatures don't get destroyed

Some refactoring and added a SSH development module

---

.gitignore

Signed-off-by: Ivan Nikolaenko <ivan.nikolaenko@unikie.com>

Add Qemu disk image (ghaf-host.qcow2) to .gitignore

---

docs/src/about/overview.md
docs/src/appendices/contributing_general.md
docs/src/architecture/adr.md
docs/src/architecture/adr/minimal-host.md
docs/src/build_config/build_configurations.md
docs/src/build_config/reference_implementations.md
docs/style_guide.md

Docs: fix links, proofread

---

docs/src/scs/sbom.md
docs/src/scs/scs.md

Under the SCS chapter, add a new section for SBOM.
Signed-off-by: Henri Rosten <henri.rosten@unikie.com>

Docs: add section for sbom

---

docs/src/build_config/reference_implementations.md

doc: fix link to dev authentication details

---

modules/development/intel-nuc-getty.nix
targets/default.nix

* 'raw-efi' resulting image format;
* Debugging serial interface via USB-serial converter;
Co-authored-by: Tero Tervala <tero.tervala@unikie.com>
Signed-off-by: Ivan Nikolaenko <ivan.nikolaenko@unikie.com>

Add support for Intel NUC.

---

CONTRIBUTING.md
docs/src/about/overview.md

Docs: Try to fix index page

---

configurations/host/microvm.nix
configurations/host/networking.nix
configurations/netvm/default.nix
flake.lock
flake.nix
modules/development/nix.nix
modules/development/packages.nix
modules/hardware/nvidia-jetson-orin.nix
targets/default.nix
targets/nvidia-jetson-orin.nix

Initial microvm.nix and netvm configuration

---

.git-blame-ignore-revs
.github/workflows/fmt-check.yml
configurations/host/configuration.nix
docs/doc.nix
flake.nix
modules/development/authentication.nix
modules/development/intel-nuc-getty.nix

Fix .nix format check

---

modules/graphics/weston.nix
targets/default.nix
targets/nvidia-jetson-orin.nix

Enable Weston on host

---

CONTRIBUTING.md
README.md
docs/README-docs.md
docs/src/appendices/glossary.md
docs/src/research/research.md
docs/style_guide.md

Added info about: Markdown Syntax, Voice and Tone (plain English), Spelling and Punctuation (numbers, date format, lists, dashes and hyphens, brackets), Tips and Tricks.
Open questions: cross compilation/cross-compilation, passthrough/pass-through.
Stay tuned.

Docs: add more info to writing guidelines

---

flake.lock
flake.nix
targets/nvidia-jetson-orin-flash-script.nix

* All of my wip_hacks_2 branch things now have proper implementations in microvm.nix main-branch, so change back to it

Change back to astro's microvm.nix main-branch

---

modules/graphics/fonts.nix
modules/graphics/weston.ini.nix
modules/graphics/weston.nix

* Chromium and Element are added to the image;
* Launchers for ^ are added to weston panel;
* New fonts are added to the system;
* Screen blanking is disabled by default.

Some steps towards usable graphic image

---

docs/src/SUMMARY.md
docs/src/technologies/hypervisor_options.md

* Added a document describing how to set hypervisor options for VM running under microvm

Docs: Added hypervisor_options.md doc

---

docs/src/technologies/nvidia_agx_pt_pcie.md
docs/src/technologies/passthrough.md
docs/src/technologies/technologies.md

Initial documentation for ARM64 PCIe passthrough with Nvidia Orin

Docs: PCIe device passthrough

---

flake.lock
modules/hardware/nvidia-jetson-orin/mk-flash-script.nix
targets/nvidia-jetson-orin.nix

* Refactor flash script to use newly exposed mkFlashScript

Update jetpack-nixos in flake.lock

---

modules/development/authentication.nix
modules/development/docker.nix
targets/common-debug.nix

Added the docker module. It adds to Ghaf docker package and changes system configuration (systemd, groups, socket, etc.) to support docker.

Add docker

---

targets/common-debug.nix
targets/common.nix

Move user accounts module to common for now, to fix release build.

Fix release build

---

flake.nix
templates/default.nix

Remove unnecessary self argument from import of templates/default.nix

Remove unnecessary self from templates/default.nix

---

docs/src/technologies/hypervisor_options.md

Fix links in the hypervisors options section.

doc: update the hypervisors options section

---

docs/src/features/features.md
docs/src/ref_impl/build_and_run.md
docs/src/ref_impl/cross_compilation.md
flake.nix
modules/hardware/polarfire/mpfs-nixos-sdimage.nix
targets/default.nix
targets/microchip-icicle-kit.nix
templates/default.nix
templates/targets/riscv64/microchip/polarfire/flake.nix

Enabled template for Polarfire

Polarfire Icicle-kit reference platform

---

docs/src/SUMMARY.md
docs/src/architecture/adr/minimal-host.md
docs/src/architecture/adr/platform-bus-passthrough-support.md
docs/src/architecture/adr/template.md
docs/src/ref_impl/build_and_run.md
docs/src/ref_impl/ghaf-based-project.md
docs/src/ref_impl/modules_options.md
docs/src/ref_impl/reference_implementations.md
docs/src/research/research.md
docs/src/scenarios/run_win_vm.md
docs/style_guide.md

Let's try the new structure with ghaf overview, for developers, build system and supply chain, usage scenarios, append.

Docs: new structure and proofreading

---

docs/src/SUMMARY.md
docs/src/technologies/passthrough.md
docs/src/technologies/x86_pcie_crosvm.md

Pcie passthrough example for x86 crosvm

doc: crosvm x86 pcie passthrough

---

docs/src/SUMMARY.md
docs/src/release_notes/ghaf-23.05.md
docs/src/release_notes/ghaf-23.06.md
docs/src/release_notes/release_notes.md

Some initial and not full information about the Ghaf release.

Docs: add release notes information

---

modules/virtualization/microvm/appvm.nix
targets/lenovo-x1-carbon.nix

Separate extra modules config for appVMS
Lenovo X1 Integrated webcam support for chromium appVM as reference

Add integrated Lenovo X1 webcam for Chromium AppVM

---

docs/src/appendices/glossary.md
docs/src/ref_impl/example_project.md

Creating a SKU with the udev rules.

Docs: Ghaf as library, Lenovo X1 troubleshooting

---

overlays/acpi-devices-passthrough.patch
overlays/custom-packages.nix
targets/lenovo-x1-carbon.nix

Lid button, battery and AC adapter devices are added to Qemu as a patch and they are used in Guivm.

lenovo-x1-carbon: Add ACPI devices passthrough

---

modules/virtualization/microvm/netvm.nix
overlays/custom-packages.nix
user-apps/wifi-connector/default.nix

Usage from net-vm:
sudo wifi-connector "SSID" "PSK"

Add wifi connection helper utilty.

---

modules/development/debug-tools.nix

Add iperf to debug-tools

---

modules/virtualization/microvm/appvm.nix
modules/virtualization/microvm/guivm.nix
modules/virtualization/microvm/netvm.nix
targets/lenovo-x1-carbon.nix

Add default timezone, current system time is updated from external NTP
Current default timezone is set to Asia/Dubai

Add default timezone for all VMS

---

.github/workflows/build.yml

Follow-up for PR https://github.com/tiiuae/ghaf/pull/358. This should be merged together with https://github.com/tiiuae/ghaf/pull/358.

GhA: Change vedenemo key in build workflow

---

modules/graphics/default.nix
modules/graphics/labwc.nix
modules/graphics/weston.nix
modules/graphics/window-manager.nix
modules/profiles/graphics.nix
modules/virtualization/microvm/guivm.nix
overlays/custom-packages/default.nix
overlays/custom-packages/labwc/default.nix
targets/lenovo-x1-carbon.nix

This commit introduces LabWC and making it a hardcoded option. (let's discuss).
This commit adds third option for DE, which can be enabled with `profiles.graphics.compositor = "labwc"` option.
Also at this moment I am not quite sure about how to implement painless configuration of labwc and its components. This topic needs some additional research.

Introduce LabWC compositor/desktop environment

---

.github/pull_request_template.md

This change adds SPDX License header to this template, so that when `nix fmt check` is run it does not complain about reuse compatiblity.
- Yes, now it passes after this commit has been merged
This can be tested by running: `nix flake check --allow-import-from-derivation`

pull_request_template: Fix reuse compatiblity

---

overlays/cross-compilation/default.nix
overlays/cross-compilation/firefox.nix

Cross compilation fix for firefox (by temporary switch to ESR version)
Cherry-picked from 23.11 branch, where it builds

firefox: fix cross-compilation by replacing firefox with firefox-esr

---

.gitignore
nix/devshell.nix

<How this was tested by the author? How is this supposed to be tested by people doing system testing?>

Fix formatting issue

---

overlays/cross-compilation/edk2.nix

Fix reuse compliance
nix develop
reuse lint

Fix reuse compliance

---

modules/hardware/definition.nix
modules/module-list.nix
targets/lenovo-x1-carbon.nix

In this first stage:
* Implement hardware definition module and make Lenovo X1 Carbon target use that.
Build and run Lenovo X1 Carbon debug target. There's actually 0 paths changed if one does `nixos-rebuild boot`, which is a good sign that nothing has actually changed with this commit.

Initial Hardware definition and refactor

---

.github/workflows/build-yml-check.yml
.github/workflows/build.yml
.github/workflows/check.yml
.github/workflows/doc.yml

This PR makes the following changes to github actions:
- print github-hosted runner system info in build workflow
- move checks from `build.yml` to a new workflow `check.yml` in an attempt to try to avoid the usage of the custom environment-based authorization for checks that don't need to access github secrets. For more info, see: https://ssrc.atlassian.net/wiki/x/OABjMg
- Update all github actions to their current latest version
This change was tested in a forked repo at: https://github.com/henrirosten/ghaf/pull/18. 
This PR modifies `build.yml` which runs in the context of the base branch, therefore, this needs to be tested in a fork as explained in: `https://github.com/tiiuae/ghaf/blob/1b0275f2d4df61b777877a44dcbf08d3c33a3966/.github/workflows/build-yml-check.yml#L52-L61`.

Gha move checks from build

---

.github/workflows/build.yml

reduce priority for cachix

---

docs/src/architecture/hardening.md
docs/src/release_notes/ghaf-23.09.md
docs/src/scenarios/run_win_vm.md

Docs: proofread Hardening, update RN ghaf-23.09

---

.github/workflows/build.yml

REVERT-ME: Disable cachix as a binary-cache

---

overlays/cross-compilation/jbig2dec.nix

Replace current solution, with solution agreed with upstream
https://github.com/NixOS/nixpkgs/pull/266254 and pending https://github.com/NixOS/nixpkgs/pull/275027

jbig2dec: use upstream agreed solution

---

.github/workflows/build.yml

Reverts tiiuae/ghaf#424
And temporarily disables the x1-carbon pretests

Revert "REVERT-ME: Disable cachix as a binary-cache"

---

README.md

Add OpenSSF BestPractices Badge

---

packages/gala/default.nix

Update Gala version so it works with the new Nix version

[Packages] Gala: update urls

---

CODE_OF_CONDUCT.md
README.md
SECURITY.md
docs/src/appendices/glossary.md
docs/src/ref_impl/creating_appvm.md
docs/src/ref_impl/development.md
docs/src/ref_impl/labwc.md

Docs: add code of conduct

---

targets/lenovo-x1-carbon.nix

Fixes compilation with LabWC enabled: https://ssrc.atlassian.net/browse/SP-3966

Powercontol over ssh labwc fix

---

targets/nvidia-jetson-orin/default.nix

This reverts commit 6b236a4acb56ee12af23370acab2be84aae9983b.
We can re-enable it, because problem was workarounded in 968f80a15ddf64813974f7b4fb1dcdb716e17eaa

Revert "Disable windows-launcher with cross-compilation"

---

targets/lenovo-x1-carbon-installer.nix
targets/lenovo-x1-carbon.nix

Debug and Release variants for installer, instead of previous hardcoded Debug

Debug and Release variants for installer

---

modules/hardware/nvidia-jetson-orin/mk-esp-contents.py
nix/treefmt.nix
packages/installer/default.nix
packages/installer/ghaf-installer.sh
targets/lenovo-x1-carbon-installer.nix

treefmt: Enable Python formatting and linting and enable Shellcheck
ghaf-installer: Fix shellcheck issues
mk-esp-contents: Fix Python formatting
Because of the changes to install script, just in case tested installer again.

treefmt: Enable Python formatting and linting and enable Shellcheck

---

targets/lenovo-x1/appvms/chromium.nix
targets/lenovo-x1/appvms/default.nix
targets/lenovo-x1/appvms/gala.nix
targets/lenovo-x1/appvms/zathura.nix
targets/lenovo-x1/everything.nix
targets/lenovo-x1/guivmExtraModules.nix
targets/lenovo-x1/netvmExtraModules.nix

This change does not modify any functionality, creats no new build. it only factors out some common components from the x1 target so that they could be used in other targets as required.
- [] Tested on Lenovo X1 `x86_64`

Micro vm target refactor

---

targets/flake-module.nix
targets/generic-x86_64/flake-module.nix
targets/imx8qm-mek/flake-module.nix
targets/lenovo-x1-installer/flake-module.nix
targets/lenovo-x1/appvms/chromium.nix
targets/lenovo-x1/appvms/default.nix
targets/lenovo-x1/appvms/gala.nix
targets/lenovo-x1/appvms/zathura.nix
targets/lenovo-x1/everything.nix
targets/lenovo-x1/flake-module.nix
targets/lenovo-x1/guivmExtraModules.nix
targets/lenovo-x1/netvmExtraModules.nix
targets/microchip-icicle-kit/flake-module.nix
targets/nvidia-jetson-orin/flake-module.nix
targets/vm/flake-module.nix

targets: Refactor from lib.recursiveUpdate to proper flakeModule usage. 
Build all targets. Basic tests again, although this change should not even change the resulting build hashes.

targets: Refactor from lib.recursiveUpdate to proper flakeModule usage

---

modules/desktop/graphics/waybar.config.nix

Fixes the clock in the waybar, where issue was introduced by https://github.com/tiiuae/ghaf/pull/502.

labwc: fix clock in waybar

---

targets/lenovo-x1/guivmExtraModules.nix

This resolves PDFs not opening on Chromium.
Tested with labwc only.

guivm: fix PDF opener service

---

packages/gala/default.nix
packages/nm-launcher/default.nix
packages/powercontrol/default.nix
packages/powercontrol/png-icons.nix
packages/vsockproxy/default.nix
packages/wifi-connector/default.nix
targets/lenovo-x1/guivmExtraModules.nix

Refactor and tidy up some of the packages a bit. Remove direct usage of pkgs in callPackage arguments, and instead directly use the packages. Also fixed few other things in packages, like shellcheck errors, and missing runHook pre/post calls.
Run regular tests on all platforms.

Refactor packages a bit

---

.github/workflows/build.yml

Disable x1 as it fails on every invocation

---

modules/common/hardware/lenovo-x1/definitions/x1-gen11.nix

lenovo x1: additional udev rules for mouse and trackpad for laptop version 21mh--002gus

additional udev rules

---

modules/desktop/graphics/labwc.nix
modules/microvm/virtualization/microvm/guivm.nix

Screenshot tool Grim is added into labwc.nix to replace shortcut "Win"+"s" in weston.

Add screenshot tool Grim

---

.gitignore

Ignore all result files

---

templates/targets/aarch64/nvidia/orin-agx/flake.nix
templates/targets/aarch64/nvidia/orin-nx/flake.nix
templates/targets/aarch64/nxp/imx8/flake.nix
templates/targets/riscv64/microchip/polarfire/flake.nix
templates/targets/x86_64/generic/flake.nix

User might include inputs for overriding input dependencies without actually using those.

templates: guard all templates against unexpected arguments

---

flake.lock

This does not update the 3 inputs (jetpack, nixpkgs, microvm) as they are being handled separately.
Bump all of the helper inputs that are quite outdated. This does not bump : jetpack-nixos, nixpkgs, microvm.nix as all of these will be handled separately.

Bump all of the helper inputs

---

.github/workflows/check.yml

We broke the templates in the past and this should help for the future.

add regression test for all templates

---

modules/common/development/authorized_ssh_keys.nix
modules/common/development/ssh.nix
targets/lenovo-x1-installer/flake-module.nix

Avoid having ssh keys scattered to different places in ghaf repository. Gather all ssh keys to single file modules/common/development/authorized_ssh_keys.nix and import from there when needed.
Tested with my own key pair (added public ssh key to modules/common/development/authorized_ssh_keys.nix) that ssh connection works both to ghaf-installer and to ghaf.

Move all ssh keys to single file

---

flake.lock

• Updated input 'devshell':
'github:numtide/devshell/2c8e04e5c29299bec53c2e5a73da0f9afa8dabb5' (2024-04-15)
→ 'github:numtide/devshell/12e914740a25ea1891ec619bb53cf5e6ca922e40' (2024-04-19)
• Updated input 'flake-root':
'github:srid/flake-root/d9a70d9c7a5fd7f3258ccf48da9335e9b47c3937' (2023-08-22)
→ 'github:srid/flake-root/bc748b93b86ee76e2032eecda33440ceb2532fcd' (2024-04-19)
• Updated input 'microvm':
'github:astro/microvm.nix/a1341f7195e34d9bb88c12314cc3b0c4429f9b0a' (2024-04-15)
→ 'github:astro/microvm.nix/6a4f822a817180be03fcdceb654088d002c9ec5e' (2024-04-18)
• Updated input 'nixos-hardware':
'github:NixOS/nixos-hardware/6f976e53752e5b9ab08f9a3b1b0b9c67815c9754' (2024-04-18)
→ 'github:NixOS/nixos-hardware/5d48925b815fd202781bfae8fb6f45c07112fdb2' (2024-04-19)
Basic test suites

Update other inputs than nixpkgs in flake.lock

---

modules/common/services/dendrite-pinecone.nix
packages/dendrite-pinecone/default.nix

go1.19 -> go1.20 upgrade for dendrite

---

overlays/custom-packages/labwc/labwc-colored-borders.patch

labwc: rebase patches from 0.7.1 -> 0.7.2

---

modules/common/services/dendrite-pinecone.nix
packages/dendrite-pinecone/default.nix

* Refactor & clean dendrite-pinecone a bit
* TODOs for future dendrite-pinecone refactorings
I only tested building and running it on Lenovo X1. I don't have any idea how to test how it works. I would probably need to set up multiple devices and a network with multicast. Anyway I don't think this even caused any rebuilds

Refactor & clean dendrite-pinecone a bit

---

overlays/README.md

Update the tracker to list the carried patches

---

modules/common/development/authorized_ssh_keys.nix

Add shamma to authorized keys

---

modules/microvm/virtualization/microvm/audiovm.nix
modules/reference/appvms/chromium.nix
modules/reference/appvms/default.nix
modules/reference/appvms/element.nix
modules/reference/appvms/zathura.nix
targets/lenovo-x1/guivmExtraModules.nix
targets/lenovo-x1/netvmExtraModules.nix

Use config time for the timeZone

---

docs/src/appendices/glossary.md
docs/src/architecture/adr.md
docs/src/architecture/adr/idsvm.md
docs/src/architecture/adr/minimal-host.md
docs/src/architecture/adr/netvm.md
docs/src/architecture/adr/template.md
docs/src/architecture/variants.md
docs/src/features/features.md
docs/src/ref_impl/creating_appvm.md
docs/src/ref_impl/example_project.md
docs/src/ref_impl/idsvm-development.md
docs/src/ref_impl/labwc.md
docs/src/ref_impl/systemd-service-config.md
docs/src/release_notes/ghaf-23.09.md
docs/src/release_notes/ghaf-23.12.md
docs/style_guide.md

https://github.com/tiiuae/ghaf/pull/422

Docs: proofread PR 422

---

flake.lock
flake.nix
modules/desktop/graphics/window-manager.nix
modules/reference/appvms/appflowy.nix

take in the latest ssh fixes for the latest RCE regreSSHion
Needs testing on all platforms. no new features but many packages updated

Bump flake.lock for ssh fixes

---

templates/boilerplate/modules/hardware/default.nix

Add a template for new x86 hardware support

---

modules/common/networking/hosts.nix
modules/common/services/desktop.nix
modules/profiles/mvp-user-trial.nix
modules/reference/appvms/business.nix
modules/reference/appvms/default.nix
packages/icon-pack/default.nix

Support the trusted Browsing use case
Support VPN
TODO Support PWA for the MS suite
TODO Firewall support

Add the initial business VM

---

LICENSES/WTFPL.txt
docs/book.toml
docs/default.nix
docs/theme/index.hbs
docs/theme/pagetoc.css
docs/theme/pagetoc.js

This PR adds two plugins for mdBook package:
https://github.com/lambdalisue/rs-mdbook-alerts
https://github.com/JorelAli/mdBook-pagetoc

Documentation appearance improvings

---

docs/theme/index.hbs
docs/theme/pagetoc.css
docs/theme/pagetoc.js

Add the original author of the plugin to the copyright.
Add the original author of the plugin to the copyright.

Docs: mdBook-pagetoc: Fix copyright

---

docs/src/SUMMARY.md
docs/src/ref_impl/creating_appvm.md
docs/src/ref_impl/development.md
docs/src/ref_impl/hw-config.md
docs/src/ref_impl/profiles-config.md
docs/src/ref_impl/reference_implementations.md

Docs: add new VM, HW and profile configuration

---

modules/microvm/virtualization/microvm/adminvm.nix
modules/microvm/virtualization/microvm/appvm.nix
modules/microvm/virtualization/microvm/netvm.nix

This addresses the floating time where the various parts of the system have different times and timezones.

Set the date and time using timesyncd in vms

---

modules/microvm/virtualization/microvm/adminvm.nix

With updated server endpoint url, loki will be using https with basic auth. Access using insecure ip:port and http no longer possible.
**Prerequisite:** 
Depends on https://github.com/tiiuae/ghaf-infra/pull/207 to deployed on server (Now its Merged and Deployed).
**What can be checked?**
Need to identify if there is more frequent journal logs from system with this change and check if any other issues found.

logging: Update the logging server endpoint

---

modules/reference/appvms/business.nix

Open microsoft teams app , it should run

Teams not working issue

---

modules/common/development/debug-tools.nix
modules/common/users/accounts.nix

Support on target development with -debug images via ghaf-host. This can be preferable option to remote builders with:
* native development (e.g. cross-compilation not working on aarch64)
* code on local SSD + nixos-rebuild switch can be faster than remote builder with network traffic
* git enables direct clone
* `ghaf` as `trusted-users` enables caches
Changes support
```
[ghaf@ghaf-host:~]$ git clone https://github.com/tiiuae/ghaf.git
[ghaf@ghaf-host:~]$ nix build .#<target>
[ghaf@ghaf-host:~]$ nixos-rebuild ... switch
```
instead of
```
[root@ghaf-host:~]# nix-shell -p git
[nix-shell:~]# git clone https://github.com/tiiuae/ghaf.git [nix-shell:~]# nix build .#<target>
[nix-shell:~]# nixos-rebuild ... switch
```
```
[ghaf@ghaf-host:~]$ git clone https://github.com/tiiuae/ghaf.git …
```

dev: support building ghaf on target as ghaf user

---

flake.nix

Fixes #33
Signed-off-by: Brian McGillion <bmg.avoin@gmail.com>
-------

Change the project description

---

.github/pull_request_template.md
.gitignore
nix/devshell.nix
packages/flake-module.nix
packages/make-checks/default.nix

This adds a new package to test the evaluation of all the outputs that
are produced from the flake.
This is a basic sanity check, it does not build all the targets and
packages as that is covered by `nix-fast-build` and requires even more
substantial resources and time to complete.
-------
Add the start of a checker that can be run to evaluate a commit, that it evaluates all targets correctly.
run `make-checks` in the root of the Ghaf project

Add make-checks to evaluate a derivation

---

.github/workflows/check.yml
packages/make-checks/default.nix

This adds the initial evaluation checker to ensure all changes can be evaluated across all the flake targets.

Add make-checks to the Github Actions

---

.github/pull_request_template.md

Improve the testing definition

---

README.md

Documentation update. Remove links specific to legacy CI/CD that will no longer be used for Q3/24 release.

README.md: Remove legacy CI/CD links

---

modules/microvm/virtualization/microvm/appvm.nix
modules/reference/appvms/gala.nix

Move mitm certificates to appvms certificate files for DPI.   
lenovo x1
1. Enable ids-vm and mitm proxy:
```
idsvm = {
enable = true;
mitmproxy.enable = true;
};
```
2. Verify all apps start up
3. Verify MITM works (e.g., start mitmweb-ui in guivm, run chromium and inspect traffic)

Move mitm certificate to appvm

---

packages/installer/ghaf-installer.sh

When running Ghaf on a target device and also trying to boot from an SSD there is a conflick in the boot, as to which target image will be run. for that reason the insstaller now has an option to wipe the installed ghaf image from the DUT.
Normal installation (wipe and install)remains:
`sudo ghaf-installer`
To only wipe the system run:
`sudo ghaf-installer -w`
adds the `-w` option to the installer to erase the installed disk and return. This differs from the normal installation that wipes and then installs t\he new image to the internal disk
X1 installer
Normal installation (wipe and install)remains:
`sudo ghaf-installer`
To only wipe the system run:
`sudo ghaf-installer -w`
Extends the installer to also allow just wiping

Add a wiping option to the installer

---

.github/pull_request_template.md

add checklist items for reinstallation vs. update req
- [N/A] Test procedure described (or includes tests). Select one or more:
- [N/A] Author has run `make-checks` and it passes
- [N/A] All automatic Github Action checks pass - see [actions](https://github.com/tiiuae/ghaf/actions)
N/A

pr: add checkitem for reinstallation vs. update req

---

modules/common/networking/hosts.nix
modules/common/services/desktop.nix
modules/reference/appvms/comms.nix
modules/reference/appvms/default.nix
modules/reference/profiles/mvp-user-trial.nix
modules/reference/services/dendrite-pinecone/dendrite-config.nix
modules/reference/services/dendrite-pinecone/dendrite-pinecone.nix
packages/icon-pack/default.nix

This PR modifies the existing element-vm into a more generic comms-vm and adds Slack to it. Slack runs as a PWA due to 
issues in the electron package. [(SP-4808)](https://ssrc.atlassian.net/browse/SP-4808) 
Open the element application. Also open the slack application. Both applications should be able to launch. Sign in into slack, to make sure everything is well. ( Make sure you are connected to wifi first to test the signing in :) ) 
Known issues:
You need to wait for some time till the wifi connects to be able to launch slack ( not a slack problem, but i believe ghaf needs some time to just connect)

Add comms-vm

---

modules/common/default.nix
modules/disko/disko-basic-partition-v1.nix
modules/flake-module.nix
modules/hardware/definition.nix
modules/hardware/flake-module.nix
modules/hardware/laptop.nix
modules/reference/hardware/default.nix
targets/laptop/flake-module.nix

return some common parts back to the modules as they are a core
functionality. This also forced a refactor of some parts of the hardware
definitions inclusion to longer rely on relative paths but rather paths
explicitly defined by the caller.
-------

fix the hw to return common parts

---

modules/common/networking/hosts.nix
modules/common/profiles/debug.nix
modules/common/profiles/release.nix
modules/common/security/sshkeys.nix
modules/hardware/definition.nix
packages/flake-module.nix

This refactors our x86 target to be exposed as a NixOS module. This makes usage outside of ghaf much easier without having to use expensive "extendModules` function. It also makes usage inside ghaf easier i.e. it gives us a target that we can import in module documentation or we can derive a debug target from the release target without having to use wrapper functions.

Fix nixos module documentation

---

packages/flake-module.nix

Signed-off-by: Brian McGillion <bmg.avoin@gmail.com>
-------

fix the hw include path for the docs

---

modules/reference/appvms/comms.nix

This PR makes Slack metadata (session/login) persistent between reboots.
It applies only to Lenovo-X1
1. Run Slack and log in.
2. Restart comms-vm or reboot the computer
3. Run Slack againg and make sure the session is preserved

Slack: make metadata persistent

---

modules/reference/appvms/business.nix
modules/reference/appvms/chromium.nix
packages/openPdf/default.nix

- change path to absolute for `realpath`
- allow business-vm to open pdfs
Lenovo X1 `x86_64`

Fix pdfopener

---

modules/reference/hardware/lenovo-x1/definitions/x1-gen11.nix

*Addresses SP-5198 - lenovo-x1: Brightness changing doesn't work
and finally screen shows totally black.
*By default the i915 driver tries to use PWM to control backlight
brightness, which might not work. To set the backlight through
writes to DPCD registers using the AUX channel set
i915.enable_dpcd_backlight=3 as a kernel parameter which will
force Intel interface.
1. Brightness related test cases need to be tested thoroughly.
2. Can be tested on different variants on Lenovo Gen 11 to verify it doesn't break anything.

Fix brightness on Lenovo X1 Carbon 21HM0072MX

---

modules/common/services/desktop.nix
modules/desktop/graphics/demo-apps.nix
modules/desktop/graphics/labwc.config.nix
modules/desktop/graphics/labwc.nix
modules/desktop/graphics/launchers.nix
modules/desktop/graphics/waybar.config.nix
modules/desktop/profiles/graphics.nix
modules/reference/programs/windows-launcher.nix

- Add descriptions for launcher applications
- It includes the VM name in case it is launched in a VM.
In the future, category tabs may be added. Currently with nwg-drawer the categories are hard-coded, so that has to be changed to support category per-VM or other custom categories.
- gui-vm will reboot
- Any target that has desktop environment and launcher
-  Lenovo X1
- Jetson Orin
- Boot into desktop
- Hover on each launcher entry
- Each should have an accurate description shown, with correct VM listed (in case it is a VM application).
- Improves usability

desktop: Add descriptions for launcher applications

---

docs/src/scs/ci-cd-system.md

Make it to match new ghaf-infra based CI/CD.
Replace legacy CI/CD documentation with the documentation of the new CI/CD.

Docs: Update CI/CD documentation

---

modules/common/services/desktop.nix
modules/microvm/virtualization/microvm/guivm.nix

The app can display them either in line or they can be arranged as a
series of "postits" on the screen. It has very basic functionality but
it fits the bill.
Signed-off-by: Brian McGillion <bmg.avoin@gmail.com>
-------
Adds a basic notes taking application
lenovo MVP target
open the sticky notes application.
create some notes
pull them across the screen as desired or leave them in the postit stack
cest ca

Add a sticky notes application.

---

flake.lock
modules/common/services/desktop.nix
packages/icon-pack/default.nix

Add GhafAudioControl app from ghapkgs
Update lock file
Run application in taskbar "Audio Control"
Run Chromium and check, if some streams appeared. Mostly, they don't have proper names
Check you can control sound by sliding a slider

[Packages] Add GhafAudioControl app from ghapkgs

---

modules/disko/disko-ab-partitions.nix

zfs: create zpool with ashift=12

---

flake.lock

Flake lock bump

---

modules/reference/hardware/lenovo-x1/definitions/x1-gen11.nix
packages/hardware-scan/hardware-scan.sh
targets/laptop-hw-scan/flake-module.nix

Adding a new sku for the uae devices. Yet another batch
-------

New sku for uae X1-GEN11

---

modules/desktop/graphics/ewwbar.nix
modules/desktop/graphics/labwc.nix

1. **Fixed Power Menu Bug**
- The issue was caused by the command timing out before it finishes.
- Not certain why this is not an issue when mic is not in use.
2. **Changed Default Ghaf Background Image**
Lenovo X1
Can be tested on Lenovo X1 following usual installation or `nixos-rebuild ... switch`
Increased usability and introduced functionality offered by common operating systems.

Fix power menu bug and change default background image

---

flake.lock
flake.nix
modules/common/services/desktop.nix
modules/hardware/flake-module.nix
modules/microvm/virtualization/microvm/guivm.nix
packages/icon-pack/default.nix

Control panel was added as input to flake.nix
Control panel app added as an input to the root flake.nix and then as system package in GUI VM. Task number is [SP-5063](https://ssrc.atlassian.net/browse/SP-5063).
Build ghaf image, flash using flash.sh, load (or use nixos-rebuild ... switch). Open Ghaf menu and choose Control panel or launch terminal and run ctrl-panel.  The Ghaf Control panel app should run.

Control panel integration

---

modules/common/services/desktop.nix
modules/reference/appvms/business.nix
packages/icon-pack/default.nix

Xarchiver icon launcher is added to guivm/desktop which can run the app on business-vm.

Add xarchiver app to business-vm

---

modules/flake-module.nix
modules/givc/flake-module.nix
modules/microvm/virtualization/microvm/appvm.nix
modules/reference/appvms/business.nix
overlays/custom-packages/default.nix
overlays/custom-packages/open-normal-extension/default.nix
packages/open-normal-extension/default.nix
packages/open-normal-extension/fi.ssrc.open_normal.json
packages/open-normal-extension/manifest.json
packages/open-normal-extension/open_normal.js
packages/open-normal-extension/open_normal.sh

Add browser extension to trusted browser which adds "Open in normal browser" option to pop-up menu for links.
* Open an allowed site in trusted browser
* Right-click on a link
* Select "Open link in normal browser"
* Check if the link is actually opened in the normal browser 
* Open a not-allowed page in trusted browser
* Right-click anywhere on the "Site cannot be reached" or "403 Access denied" -page
* Select "Open page in normal browser"
* Check if the page actually opened in the normal browser

Add extension to trusted browser to allow opening links in normal browser

---

modules/desktop/graphics/ewwbar.nix

1. **Runtime multi-monitor support for ewwbar**:
- Implemented functionality to handle multiple monitors during runtime—ewwbar can now adapt to changes in monitor configuration without requiring a system reboot.
- This functionality was implemented using a udev rule to listen for DRM events, upon which the ewwbar service is restarted.
2. **Variable fetching at daemon startup**:
- Added logic to fetch and initialize variable values as soon as the eww daemon starts. This ensures that variables are correctly populated from the beginning.
This should also address a previously observed bug where some button icons might not display correctly at system boot.
3. **Cleaned up logs**:
- Got rid of several redundant or non-critical warnings and errors. Most of these messages were unnecessary, …

EWW: Add runtime multi-monitor support and improve variable fetching

---

modules/desktop/graphics/labwc.config.nix

Labwc window switcher shows the title and display output of the window.

Change labwc window switcher texts

---

flake.nix

Start using prod-cache.vedenemo.dev.

Start using prod-cache.vedenemo.dev

---

modules/common/services/desktop.nix
modules/reference/appvms/comms.nix
modules/reference/appvms/default.nix
packages/icon-pack/default.nix

The Zoom app can't work on Wayland properly. 
The web app is tested and the only issue is the webcam that is already known.
The chromium tabs are sharable from comms-vm but not the screen from gui-vm.

Add zoom web app in comms-vm

---

modules/common/networking/hosts.nix

This allows better integration with NixOS ecosystem.

networking: unbreak NixOS networking.hosts

---

packages/gala/default.nix

[Packages] Gala: update version

---

modules/desktop/graphics/labwc.config.nix
modules/desktop/graphics/login-manager.nix

labwc output are now stored in temporary files, rather than previously showing on the screen briefly. Also sets the session name as ghaf-session rather than the long nix store path.

desktop: fix text flash on login/logout

---

flake.lock
flake.nix
modules/desktop/graphics/labwc.config.nix

Pull in new version of ghaf-ctrl-panel
Apply set-environment in ghaf-launcher to get locale settings into gui-vm applications
- start control panel from top menu
- navigate to settings / region & language
- make changes to timezone and/or language and click apply
- restart control panel, verify selections remain
- reboot
- start control panel again, verify settings persist
- only chromium and trusted browser currently change language; some UI components may change places according to language in other components
- time in bar should adjust to timezone changes with some delay

Integrate ctrl-panel with locale setting support

---

docs/src/SUMMARY.md
docs/src/release_notes/ghaf-24.09.2.md
docs/src/release_notes/release_notes.md

Docs: add ghaf-24.09.2 release note

---

modules/common/services/audio.nix

More generic solution to initialize audio device
Finds default audio device and profile
after going through all profiles resets back to the original default
This fixes a bug with Lenovo X1 audio when booted with 3.5mm headset connected
In the bug wrong audio profile got activated and no audio was heard from either speakers or headset

Generic initialize of audio devices

---

modules/common/users/accounts.nix

this was introduced as a non-merge conflicting rebase.

fix uid errors

---

modules/disko/disko-ab-partitions.nix

This allows to incrementally update installations on usb-sticks without having to go through the process of creating slow images.

add option to disable compression in image builder

---

flake.lock
flake.nix
modules/givc/adminvm.nix
modules/givc/appvm.nix
modules/givc/audiovm.nix
modules/givc/common.nix
modules/givc/guivm.nix
modules/givc/host.nix
modules/givc/netvm.nix
modules/reference/profiles/laptop-x86.nix

- bump givc to include locale listener fix
- add global debug option for givc to increase log levels for all givc components
bugfix + global debug flag

Givc bump + debug option

---

modules/desktop/graphics/ewwbar.nix

1. **Reworked Taskbar Instance Management on External Displays:**
- Adding a new display dynamically creates a corresponding taskbar instance.  
- Removing a display automatically removes its associated taskbar instance.  
- The `ewwbar` service no longer restarts during display change events (e.g., adding or removing displays). This results in a smoother experience, as the taskbar on the "main" display will no longer disappear or blink.
2. **Disabled Interactivity for Brightness and Volume Popups:** 
- Previously, the sliders could be manipulated, but they had no effect on system volume or display brightness.  
- These popups now ignore mouse clicks entirely, improving user experience by avoiding misleading interactions.  
All targets where ewwbar is used.
- The `ewwbar` service now …

Desktop: Dynamically manage taskbar instances on external displays

---

docs/src/SUMMARY.md
docs/src/release_notes/ghaf-24.09.3.md
docs/src/release_notes/ghaf-24.09.4.md
docs/src/release_notes/release_notes.md

Docs: add ghaf-24.09.3 and ghaf-23.09.4 release notes

---

modules/hardware/definition.nix
modules/microvm/virtualization/microvm/audiovm.nix
modules/microvm/virtualization/microvm/microvm-host.nix
modules/reference/hardware/lenovo-x1/definitions/x1-gen10.nix
modules/reference/hardware/lenovo-x1/definitions/x1-gen11.nix

Lenovo X1 PCI audio device needs to be reset when audioVM shuts down Generic version that allows configuration for other platforms
The change removes hard coded paths from audioVM config and adds configurable options for
audio ACPI configuration file and audio hardware device reset functionality.

Generic acpi and reset of PCI audio device

---

flake.lock
modules/common/services/desktop.nix

[Flake-inputs] Ghafpkgs: update to the latest version
1. Check if AudioControl works the same
2. Done

[Flake-inputs] Ghafpkgs: update to the latest version

---

.github/workflows/check.yml

As pointed out in https://github.com/tiiuae/ghaf/pull/947#discussion_r1914759525  by @Mic92, we don't need to run `nix-eval-jobs --force-recurse` to evaluate the flake. This PR changes the `check.yml` github action workflow so the evaluation check step runs `nix flake show --all-systems` which improves the `check` workflow runtime from ~35 minutes down to ~1 minute.

GhA: Flake evaluation check with nix flake show

---

modules/reference/desktop/applications.nix

Set uppercase letters for the "Control Panel" name. Issue  id is [SSRCSP-5801](https://jira.tii.ae/browse/SSRCSP-5801). The application name will be changed in the app repository.

Fix Control Panel name

---

modules/common/logging/logs-aggregator.nix

This patch will add new loki process pipeline which adds capability to drop expressions which are not required.
**Unwanted logs will be dropped.**

admin-vm: Add loki process to drop expressions

---

.github/workflows/build.yml
hydrajobs/flake-module.nix
packages/flake-module.nix
targets/flake-module.nix

riscv is not POR for ghaf at the moment so disable it for now but leave it in the tree so that it can be reenabled at a later time.

disable riscv

---

docs/src/ref_impl/build_and_run.md

docs/jetson: fix image flake attribute name

---

default.nix
shell.nix

Use the new flake-compat api

---

modules/reference/services/pac/pac.nix
modules/reference/services/proxy-server/3proxy-config.nix

The service users did not exist when the proxy service files were created. That's why the system sets files' ownership as root. `environment.etc.${path_name}` was replaced by `systemd.tmpfiles.rules` 
- All the targets that have trusted browser
1)  Trusted browser should open the websites that are permitted.

fix: correct ownership of proxy service files

---

flake.lock
flake.nix
modules/microvm/virtualization/microvm/netvm.nix
modules/reference/appvms/google-chrome.nix
modules/reference/profiles/mvp-user-trial.nix
modules/reference/services/chromecast/chromecast-config.nix
modules/reference/services/chromecast/chromecast.nix
modules/reference/services/default.nix
modules/reference/services/dendrite-pinecone/dendrite-pinecone.nix
modules/reference/services/nw-packet-forwarder/nw-packet-forwarder.nix
modules/reference/services/smcroute/smcroute.nix

- smcroute modularisation
- nw-packet-forwarder package for Chromecast feature
- firewall configs for Chromecast
1) Open google chrome
2) Click three-dots -> Cast, save, and share -> Cast...
3) Chromecast device must be appeared 
4) Select the device and cast tab (cast screen does not work due to system restrictions)

Chromecast support

---

modules/microvm/flake-module.nix
modules/microvm/virtualization/microvm/adminvm.nix
modules/microvm/virtualization/microvm/appvm.nix
modules/microvm/virtualization/microvm/audiovm.nix
modules/microvm/virtualization/microvm/guivm.nix
modules/microvm/virtualization/microvm/idsvm/idsvm.nix
modules/microvm/virtualization/microvm/netvm.nix

Fixes an evaluation error:
```
sudo rm -fr /tmp/tempstore && mkdir /tmp/tempstore && chmod 777 /tmp/tempstore; \
nix flake check --no-build --debug -L --no-eval-cache --store /tmp/tempstore
...
… while evaluating the option `sdImage.storePaths':
… while evaluating definitions from `/tmp/tempstore/nix/store/irknf7niks2djxz4csh7sr44wwrs082y-source/nixos/modules/installer/sd-card/sd-image.nix':
… while evaluating the option `system.build.toplevel':
… while evaluating definitions from `/tmp/tempstore/nix/store/irknf7niks2djxz4csh7sr44wwrs082y-source/nixos/modules/system/activation/top-level.nix':
… while evaluating the option `microvm.vms.net-vm.config':
(stack trace truncated; use '--show-trace' to show the full, detailed trace)
error: path …
```

Set microvm nixpkgs path

---

modules/reference/personalize/authorizedSshKeys.nix

personalize/authorizedSshKeys: add Juan Pablo authorized sshkey

---

modules/common/services/xdghandlers.nix
modules/common/users/desktop.nix
modules/microvm/virtualization/microvm/appvm.nix
modules/microvm/virtualization/microvm/common/ghaf-audio.nix
modules/microvm/virtualization/microvm/guivm.nix
modules/microvm/virtualization/microvm/microvm-host.nix
modules/microvm/virtualization/microvm/netvm.nix
modules/reference/appvms/business.nix
modules/reference/appvms/comms.nix
modules/reference/appvms/google-chrome.nix
modules/reference/services/pac/pac.nix
modules/reference/services/proxy-server/3proxy-config.nix

Cleaning statix linter warnings

Cleaning statix warnings

---

flake.lock
flake.nix
nix/treefmt.nix
templates/boilerplate/flake.nix
templates/boilerplate/nix/devshell.nix

Use nix-fast-build from nixpkgs

---

flake.lock
flake.nix

Fixes and IFD in the process for the nix flake check.
Simple bump of lanzaboot to the latest release

Bump lanzaboot to the latest version

---

flake.nix

unused follows in flake.nix

---

flake.lock

bump microvm as it is needed by a couple of pending PRs
https://github.com/tiiuae/ghaf/pull/945
https://github.com/tiiuae/ghaf/pull/965
fairly minimal bump.
applies to all targets
will enable new functionality in the linked PRs so by itself nothing new.

bump microvm

---

modules/desktop/graphics/ewwbar/config/scripts/default.nix
modules/desktop/graphics/ewwbar/config/variables/default.nix
modules/desktop/graphics/ewwbar/config/widgets/default.nix
modules/desktop/graphics/ewwbar/config/windows/default.nix
modules/desktop/graphics/labwc.config.nix

1. **Send active window to next/previous desktop:**  
- Added keybindings:
- **Super + Shift + Left** - move active window to the previous desktop;
- **Super + Shift + Right** - move active window to the next desktop.
- Moving the active window to a different desktop will also switch to the specified desktop. This behavior can be adjusted.
- These keybindings should not be confused with **Super + Alt + Left/Right**, which still switch desktops without moving the active window, as they did before.
2. **Improved EWW error handling and logging:**  
- Reduced false errors and unnecessary log messages for better clarity;
- Improved EWW error handling:
- Failures in audio backend services are now less likely to cause visual glitches in the taskbar and its widgets;
- Failures in audio backend …

Desktop: Add window send-to-desktop keybinds, refine EWW logging & error handling

---

modules/common/logging/logs-aggregator.nix

Added more filters in log aggregator module to avoid logging expressions which are not required.
1) Unwanted expressions will be dropped.    
2) Make sure we are not dropping similar expressions unintentionally, i.e dropping what is not required to drop.

admin-vm: Add more filters in loki drop stage

---

.github/eval.sh

Before the changes from this PR, the 'eval' check would always pass, even if a target ghaf flake output would fail to evaluate. This was caused by me not realizing the fact that `nix-eval-jobs` exits with success status even if the evaluation fails. This PR fixes the issue by parsing the `nix-eval-jobs` output after execution, converting possible evaluation error to exit status accordingly.
This PR also adds `--option allow-import-from-derivation false` option to `nix-eval-jobs` as well as sets sensible defaults to `-j` and `-m` making it possible to call the `.github/eval.sh` from a local devshell.
The changes were tested in a fork:
- Evaluation failure example: https://github.com/henrirosten/ghaf/actions/runs/13198465558/job/36844927220?pr=96
- Evaluation pass example: …

Fix eval.sh exit status on evaluation error

---

modules/desktop/graphics/ewwbar.nix
modules/desktop/graphics/ewwbar/config/scripts/default.nix

There is an issue with `:exclusive "true"` handling in Wayland and ewwbar. But realized that if eww is reloaded, the issue disappeared.
Task id: SSRCSP-5824
1. Open Chrome and maximize the window 
2. Navigate to youtube.com
3. Open a video and put it into full-screen

Desktop: Fix taskbar reserving space on fullscreen events

---

flake.lock

bump to get the latest fix for mitm-proxy that was broken in the extras image.
https://github.com/NixOS/nixpkgs/pull/380668
- bump so all packages
- 
fixes the building of the extras image

bump: flake bump

---

modules/microvm/virtualization/microvm/common/storagevm.nix

Fix boot issue when givc TLS is disabled and Ghaf flashed by adding appropriate guard.
Tested on x1.

Add TLS guard for storagevm

---

.envrc

the flake show is expensive due to the number of targets that there are currently in ghaf. so rather than using the check. we will assume that everyone uses flakes.
/flame-war on

envrc: use the flake directly

---

docs/src/SUMMARY.md
docs/src/release_notes/ghaf-24.12.2.md
docs/src/release_notes/release_notes.md

Docs: add ghaf-24.12.2 release notes

---

flake.lock
flake.nix
modules/common/services/audio.nix

normal bump
- alll as it is a bump

bump: standard bump

---

modules/reference/personalize/authorizedSshKeys.nix

Add my ssh key into authorizedSshKeys.

authorizedSshKeys: add my ssh key

---

flake.lock
flake.nix

bump: another standard bump

---

docs/src/SUMMARY.md
docs/src/release_notes/ghaf-24.12.3.md
docs/src/release_notes/release_notes.md

Docs: add ghaf-24.12.3 release notes

---

packages/element-gps/main.py

Websockets library was updated from 13.1 to 14.1 at some point, this broke the element-gps package (Python program shoveling gps data between gpsd and a web socket). This quick fix should remedy the problem.
* All x86 targets at least maybe others too
* Build and run Ghaf on device with serial-gps-device
* Check that location sharing works in Element
* Location sharing in Element should work if gps device connected and gps location fix has been acquired.

Fix element-gps to work with newer websocket lib

---

modules/common/development/debug-tools.nix
modules/microvm/virtualization/microvm/guivm.nix
modules/reference/hardware/alienware/alienware-m18.nix
modules/reference/hardware/alienware/extra-config.nix
targets/flake-module.nix
targets/laptop-installer/flake-module.nix
targets/laptop/flake-module.nix

Add alienware laptop

---

modules/reference/personalize/authorizedSshKeys.nix

chore(keys): cleanup ssh keys

---

targets/flake-module.nix
targets/laptop/flake-module.nix
targets/laptop/laptop-configuration-builder.nix
targets/laptop/laptop-installer-builder.nix

Automatically create an installer image for all defined laptop-configurations to reduce some redundancy of defining the installer per device config.

installer: align laptop installer with targets

---

modules/reference/personalize/authorizedSshKeys.nix

Personalize/authorizedSshKeys: add Jarek's authorized sshkey

---

modules/reference/profiles/laptop-x86.nix
modules/reference/profiles/mvp-user-trial.nix

The appvms that are enabled are defined by the profile, so this is where the common shared directories for those vms should be declared.

shares: move the shares from generic to profile

---

targets/imx8mp-evk/flake-module.nix

Technically we were never making an aarch64-linux package as it was always from-x86. Fixed this now by adding an actual cross-target.

imx8: fix the cross compiled targets

---

lib/mk-flash-script/default.nix
targets/nvidia-jetson-orin/flake-module.nix

After the latest changes to the jetpack mainline the mkFlashScript was a one-liner that returned the flash script. So have inlined the script retrieval.

nvidia: clean up the script generation

---

modules/flake-module.nix
modules/reference/hardware/dell-latitude/definitions/dell-latitude-7230.nix
modules/reference/hardware/flake-module.nix
targets/laptop/flake-module.nix

Export hardware definition as nixosModules, so they can be used downstream.
Export reference hardware definitions for re-use downstream.

Export hardware definitions

---

flake.lock
flake.nix
modules/givc/flake-module.nix
modules/microvm/appvm.nix
modules/microvm/microvm-host.nix
modules/microvm/sysvms/adminvm.nix
modules/microvm/sysvms/audiovm.nix
modules/microvm/sysvms/guivm.nix
modules/microvm/sysvms/netvm.nix

Make a single import namespace for givc to reduce conditional imports.
See also https://github.com/tiiuae/ghaf-givc/pull/56/commits

Flatten givc import structure

---

flake.lock
flake.nix
modules/hardware/flake-module.nix
packages/flake-module.nix
targets/laptop/laptop-configuration-builder.nix

Update control panel dependency to latest version and fix overlay configuration by moving it from hardware module to the laptop configuration builder where it belongs.

refactor: update Ghaf control panel dependency and fix overlays

---

tests/installer/default.nix

missed in the pkgs-by-name change.

tests: fix the ghaf-installer test

---

modules/reference/hardware/dell-latitude/definitions/dell-latitude-7330.nix

On Dell Latitude 7330 Network controller may enumerate on different PCI device even for same Dell model.
1.  **Closes:** SP-6343
2. Make sure network/wifi works fine on different dell 7330 variants.

dell-7330: Add new network controller PCI device

---

docs/src/SUMMARY.md
docs/src/release_notes/ghaf-24.12.4.md
docs/src/release_notes/release_notes.md

Release note 24.12.4

---

docs/src/release_notes/ghaf-24.09.1.md
docs/src/release_notes/ghaf-24.09.2.md
docs/src/release_notes/ghaf-24.09.3.md
docs/src/release_notes/ghaf-24.09.4.md
docs/src/release_notes/ghaf-24.09.md
docs/src/release_notes/ghaf-24.12.1.md
docs/src/release_notes/ghaf-24.12.2.md
docs/src/release_notes/ghaf-24.12.3.md
docs/src/release_notes/ghaf-24.12.4.md
docs/src/release_notes/ghaf-24.12.md

Fixed hyperlink when checking release notes in browser.

docs: Fix broken release notes hyperlink

---

overlays/flake-module.nix
targets/generic-x86_64/flake-module.nix
targets/imx8mp-evk/flake-module.nix
targets/laptop/laptop-configuration-builder.nix
targets/vm/flake-module.nix

Combine our main overlays and export them as a single default so that they are easier to consume downstream.
The individual overlays are still exported to support cases where the downstream wants to be more selective about what they are consuming.

overlay: create a default overlay

---

targets/nvidia-jetson-orin/flake-module.nix

overlays: use the default for orin also

---

flake.lock

not bumping nixpkgs in this round

bump: all the assistant packages

---

modules/reference/personalize/authorizedSshKeys.nix
modules/reference/personalize/default.nix
modules/reference/personalize/keys.nix
targets/laptop-hw-scan/flake-module.nix
targets/laptop/laptop-installer-builder.nix

This avoids the explicit file based imports and also makes it possible to copy to the downstream.

installer: use reference module for the keys

---

modules/hardware/common/usb/vhotplug.nix

Add extra rules for vhotplug to extend defaults downstream without overwriting existing definitions.

Vhotplug extra rules

---

targets/laptop/flake-module.nix
targets/laptop/laptop-installer-builder.nix

installer: generalize the installer

---

modules/hardware/common/kernel.nix
modules/microvm/modules.nix
modules/reference/hardware/alienware/net-config.nix
modules/reference/hardware/flake-module.nix
packages/own-pkgs-overlay.nix
packages/pkgs-by-name/rtl8126/package.nix

Inherit netvm kernel params from the hardware config and rtl8126 driver package for use with the alienware laptop.

Add netvm kernel params and rtl8126

---

modules/hardware/common/qemu.nix
modules/hardware/definition.nix
modules/reference/hardware/demo-tower/demo-tower.nix
modules/reference/hardware/demo-tower/extra-config.nix
modules/reference/hardware/flake-module.nix
targets/laptop/flake-module.nix

Demo desktop

---

docs/src/SUMMARY.md
docs/src/release_notes/ghaf-25.03.md
docs/src/release_notes/release_notes.md

docs:add release note 25.03

---

docs/src/release_notes/ghaf-25.03.md

docs: fix formatting and typo in release note

---

modules/desktop/nvidia-gpu/default.nix
modules/desktop/nvidia-gpu/vaapi.nix
targets/laptop/flake-module.nix

Update nvidia to add support for vulkan and fix the vaapi support which currently seems to be only available in the closed drivers.

vulkan: Add vulkan support for nvidia

---

modules/desktop/graphics/ewwbar.nix
modules/microvm/modules.nix
modules/microvm/sysvms/guivm.nix
modules/profiles/graphics.nix
packages/ghaf-powercontrol/package.nix
targets/laptop/flake-module.nix

Fix idle management and add a `suspendAllow` flag to graphics profile to disallow suspend on certain targets.

UI Idle management

---

modules/common/systemd/hardened-configs/greetd.nix

Allow privilege escalation in greetd as it is a parent process of many. It allows child processes to run under sudo.
It fixes SSRCSP-5890.
- [Ticket](https://jira.tii.ae/browse/SSRCSP-5890)

Bug fix SSRCSP-5890

---

modules/development/debug-tools.nix

add some tools to help find and navigate the file system.
1. ...

debug: add some additional tools

---

modules/microvm/sysvms/guivm.nix

fix: fix the xhci pt in gui-vm

---

nix/devshell/kernel.nix

This got missed with the python changes earlier and the package was missing.
1. ...

fix: devshell

---

flake.lock
modules/reference/personalize/authorizedSshKeys.nix

Fix ci devshell

---

.github/workflows/eval.yml

Start evaluating Ghaf devShell outpus in the eval.yml workflow.
~Evaluation step will fail currently:
Needs to be rebased and merged only after https://github.com/tiiuae/ci-test-automation/pull/299 has been merged and updated in Ghaf flake inputs~
==> Done
1. ...

Github actions: Evaluate devShells

---

modules/reference/personalize/authorizedSshKeys.nix

keys: Add Milla to known devs

---

modules/reference/personalize/authorizedSshKeys.nix

keys: Add new nixos key for rodrigo

---

.github/workflows/authorize.yml
.github/workflows/build.yml

- Move the authorization step to its own workflow `.github/workflows/authorize.yml` 
- Remove the usage of hard-coded `AUTHORIZED_USERS` list. Instead, authorize members of tiiuae organization by querying the organization membership API [Get organization membership REST API](https://docs.github.com/en/rest/orgs/members?apiVersion=2022-11-28#get-organization-membership-for-a-user). This requires a token as stated in the API documentation:
>_The fine-grained token must have the following permission set:_
>_"Members" organization permissions (read)_
Such token with no permissions other than read access to tiiuae organization membership is already configured in the Ghaf repo at `secrets.READ_ORG_MEMBERS`.
The actions will fail for this PR, but will pass as soon as merged.
1. ...

GhA: Authorize workflow

---

.github/workflows/authorize.yml

Url encode `github.actor` before querying https://docs.github.com/en/rest/orgs/members API.
1. ...

GhA: authorize.yml: url-encode actor

---

modules/development/debug-tools.nix

Provides a better interface and the option to select servers to test against.
1. ...

testing: replace speedtest-cli with ookla

---

SECURITY.md

docs: update docs

---

docs/src/SUMMARY.md
docs/src/technologies/hardware_acceleration.md
docs/src/technologies/passthrough.md
docs/src/technologies/x86_gpu_passthrough_qemu.md

Updated documentation about GPU passthrough for x86 platform and hardware acceleration details in Linux.
1. ...

docs: Add x86 GPU PT and hardware acceleration

---

modules/desktop/intel-gpu/default.nix
modules/development/dt-gui.nix
modules/development/flake-module.nix
modules/microvm/sysvms/guivm.nix

Add the intel-compute-runtime for opencl support.
1. ...

iGPU: Add compute engine offload capability

---

docs/src/SUMMARY.md
docs/src/release_notes/ghaf-25.04.md
docs/src/release_notes/release_notes.md

Docs: add ghaf-25.04 release notes

---

modules/desktop/graphics/labwc.config.nix
modules/desktop/graphics/labwc.nix
modules/desktop/intel-gpu/default.nix
modules/desktop/nvidia-gpu/default.nix
modules/desktop/nvidia-gpu/vaapi.nix
modules/microvm/modules.nix
modules/reference/programs/firefox.nix

- remove typos from programs/firefox
- add env vars to labwc ghaf-launcher
- remove programs config copy
1. ...

Fix GPU Accelleration

---

modules/desktop/graphics/labwc.config.nix
packages/ghaf-powercontrol/package.nix

1. **Cleanup tmp-display Files on Logout:**
- Adjusted display script behavior to no longer create tmp files
- Adjusted `ghaf-powercontrol logout` to allow user services to terminate cleanly instead of killing by force
- The above apply only to LabWC, Cosmic is unaffected
Closes #1049
See https://github.com/tiiuae/ghaf/issues/1049
1. Login
2. Check `/tmp/tmp-display*` files on the gui-vm - you should see **no** files matching the format
3. Logout
4. Connect remotely via ssh and login to the same account
5. Check `/tmp/tmp-display*` files on the gui-vm - there should be **no** files matching the format

bugfix: cleanup display tmp files on logout

---

flake.lock
modules/givc/host.nix

Bump `ghaf-givc`.
This brings following features in `ghaf-givc`:
- Cerificate checking
- Added update server
- Added unit-status command in givc-cli
- Generalized certificate generation
- Bumped some inputs 
- Upgraded some Go modules
1. Test  overall functionality.

bump ghaf-givc

---

modules/reference/hardware/flake-module.nix
modules/reference/hardware/lenovo-x1/definitions/x1-gen13.nix
targets/laptop/flake-module.nix
targets/laptop/laptop-installer-builder.nix

lenovo x1 gen 13 aura edition laptop.
1. ...

hardware: Add the lenovo x1 gen 13

---

flake.lock

Fixes the segfault issues in sticky notes starting.
1. ...

fix: Include the latest version of sticky-notes

---

modules/hardware/common/usb/vhotplug.nix

ChromeVM may use video devices which take higher precedence over audio devices or AudioVM. So set the order accordingly in vhotplug module.
**Addresses:** SP-6633 (USB camera does not work in Chrome)
1. Connect to the internet
2. Open a webcam test in Chrome, e.g. https://webcamtests.com/
3. Try to activate the camera

vhotplug: Set precedence of ChromeVM over AudioVM

---

.github/workflows/actions-security-analysis.yml
.github/workflows/authorize.yml
.github/workflows/build.yml
.github/workflows/check.yml
.github/workflows/codeql.yml
.github/workflows/dependency-review.yml
.github/workflows/doc.yml
.github/workflows/eval.yml
.github/workflows/warn-on-workflow-changes.yml

[zizmor](https://woodruffw.github.io/zizmor/) is a static analysis tool for GitHub Actions to find common security issues.
Adds a workflow to run zizmor on push and pull request. The findings will be available in the repository security tab, similarly to the currently used scorecard workflow.
zizmor workflow was originally introduced in ghaf-infra: https://github.com/tiiuae/ghaf-infra/pull/431.
In addition, this PR makes the first set of fixes based on initial zizmor findings.
Note:  **warn-on-workflow-changes** will fail for this PR. This is intentional and can be ignored.
1. ...

Add GitHub actions security analysis with zizmor

---

modules/hardware/common/usb/external-devices.nix
modules/microvm/appvm.nix

xbox: Add new variant

---

flake.lock

Will it be standard ? :)
1. general bump. so quick test on all platforms

bump: updates

---

REUSE.toml
docs/default.nix
docs/package-lock.json
docs/package.json
docs/public/CNAME
docs/src/styles/custom.css

- Fix domain name resetting each deployment
- Improve contrast of text in dark mode slightly (previously also passed WCAG AAA)
- Update Astro dependencies

docs: fix domain cname, improve contrast, and update deps

---

modules/reference/hardware/flake-module.nix
modules/reference/hardware/lenovo-x1/definitions/x1-2-in-1-gen-9.nix
targets/laptop/flake-module.nix

Add the 2-in-1 laptop hardware configuration.
1. ...

hardware: add x1 2-in-1 gen9

---

modules/common/services/default.nix
modules/common/services/timezone.nix
modules/microvm/sysvms/guivm.nix

Add a simple service to propagate gui-vm timezone changes to givc, only if givc is available. 
1. Boot into Ghaf Cosmic DE
2. Navigate to Cosmic Settings app and adjust the timezone
3. Save the changes and reboot
4. The selected timezone should be saved between reboots

guivm: add service to propagate gui-vm timezone changes to givc

---

packages/pkgs-by-name/ghaf-build-helper/package.nix

**Expanded the functionality of ghaf-build-helper with two additional flags:**
- `--force-remote` forces the build to be performed on configured remote builders by adding `--max-jobs 0` option internally
- `--force-local` forces the build to be performed on the local machine by adding `--builders ""` option internally
- These are mutually exclusive - if multiple flags of this type are applied, the last one takes precedence
1. Test e.g. `ghaf-rebuild` with either of the above mentioned flags set
2. The build should be done on the local machine or on a remote builder, whichever is selected.

feat(devshell): added options to force local/remote builds

---

docs/src/content/docs/ghaf/releases/ghaf-25.05.mdx
docs/src/content/docs/ghaf/releases/ghaf-25.06.mdx

docs: add ghaf-25.06 release note

---

flake.lock

bump: wireguard, control panel and givc

---

flake.lock
flake.nix
overlays/custom-packages/qemu/0001-ivshmem-flat-memory-support.patch
overlays/custom-packages/qemu/acpi-devices-passthrough-qemu-8.1.patch

fix the graphics display issues that were introduced in the bump to qemu 10.0.0 for the arc graphics on gen 14 intel (meteorlake) chips
1. ...

qemu: bump to latest rc of qemu

---

modules/development/debug-tools.nix
overlays/cross-compilation/default.nix
overlays/cross-compilation/v4l-utils/default.nix

Add a cross-compilation fixes for v4l-utils
Also enable v4l-utils on all platform (discussable, we definitely need it on x86_64 and Orin)
https://github.com/tiiuae/fog-ghaf/pull/44  (request from upstream)
https://github.com/NixOS/nixpkgs/pull/429900
(revert this PR when PR mentioned above would be merged)
1. ...

v4l-utils: cross-compilation overlay

---

modules/reference/personalize/authorizedSshKeys.nix

keys: Add Gayathri

---

flake.lock
flake.nix

bump: latest updates

---

flake.lock
flake.nix

use the latest rc version of qemu
1. ...

bump: qemu-10.1.0-rc2

---

flake.lock
flake.nix
modules/common/firewall/kernel-modules.nix
modules/reference/hardware/jetpack/nvidia-jetson-orin/jetson-orin.nix
modules/reference/hardware/jetpack/nvidia-jetson-orin/virtualization/common/bpmp-virt-common/default.nix
modules/reference/hardware/jetpack/nvidia-jetson-orin/virtualization/host/bpmp-virt-host/default.nix
modules/reference/services/smcroute/smcroute.nix

Bump mid august

---

modules/reference/hardware/system76/definitions/system76-darp11-b.nix
packages/pkgs-by-name/hardware-scan/hardware-scan.sh

- hardware-scan: Bump copyright to 2025 and update USB passthrough config.
- system76: We need to add event passthrough for the INT33D5 device path to ensure brightness keyboard events function correctly in gui-vm.
1. Brightness controlling works fine from Keyboard shortcuts

Fix brightness for System76 and script update

---

docs/src/content/docs/ghaf/releases/ghaf-25.06.mdx
docs/src/content/docs/ghaf/releases/ghaf-25.08.mdx

docs: add ghaf-25.08 release note

---

docs/src/content/docs/ghaf/releases/ghaf-25.08.mdx
modules/common/firewall/firewall.nix
modules/common/firewall/kernel-modules.nix
modules/common/security/default.nix
modules/common/security/ssh-tarpit/default.nix
modules/common/systemd/hardened-configs/firewall.nix
modules/microvm/host/networking.nix
modules/microvm/sysvms/idsvm/mitmproxy/default.nix
modules/microvm/sysvms/netvm.nix
modules/reference/appvms/business.nix
modules/reference/services/proxy-server/3proxy-config.nix
targets/imx8mp-evk/flake-module.nix
targets/microchip-icicle-kit/flake-module.nix
targets/nvidia-jetson-orin/orin-configuration-builder.nix
tests/firewall/default.nix
tests/firewall/test_scripts/ban_rules.nix
tests/firewall/test_scripts/basic_rules.nix

* SSH tarpit to slow or trap unauthorized SSH attempts
* Packet marking and redirection for blacklisted traffic
* Blacklist management via ipset and iptables
* Ensures required firewall kernel modules are included for all the targets.
* Includes tests for tarpit, marking, redirection, and blacklist enforcement
1. Network-related services should work
2. Launch an attack using the command `hping3 -S -p 22 -i u10000 -c 20 ${netVmIp}` 
3. Check the blacklist on net-vm with `ipset list BLACKLIST`. You should see attacker's IP in the members section.
4. Attempt to connect from the attacker's device to the Ghaf laptop via SSH. The connection should hang.

Firewall blacklisting mechanism & testing

---

flake.lock
modules/desktop/graphics/boot.nix
modules/desktop/graphics/cosmic/config/cosmic-config.nix
modules/microvm/host/microvm-host.nix
modules/reference/profiles/mvp-orinuser-trial-extras.nix
modules/reference/profiles/mvp-orinuser-trial.nix
modules/reference/profiles/mvp-user-trial.nix
overlays/custom-packages/cosmic/cosmic-osd/default.nix
overlays/custom-packages/default.nix

1. **Enabled graphical boot:**
- Splash screen with Ghaf logo will be displayed at boot 
- updated ghafpkgs to latest available to include ghaf logo
- expanded existing ghaf graphics boot module with additional nix options
2. **Minor simplification of cosmic config via cosmic osd:**
- Cosmic already handles playing a ding sound on volume change via keyboard shortcut.
This change removes our own workaround for that in favor of using Cosmic's own implementation
1. Boot laptop
2. Verify graphical boot is enabled - splash screen with ghaf logo and loading animation is shown
3. Verify boot continues to Cosmic greeter login
4. Login
5. Verify adjusting system volume with keyboard shortcuts (F2-F3) causes a sound to play

enable graphical boot, bump ghafpkgs, adjust cosmic config

---

modules/reference/profiles/mvp-user-trial.nix
targets/vm/flake-module.nix

currently the gala app is out dated and does not point to an active AiC backend. Disable it until it is refreshed.
1. ...

gala: disable gala from the mvp profile

---

docs/default.nix
docs/package-lock.json
nix/devshell.nix

docs: bump the npm packages and all the depends

---

.gitignore
modules/common/services/github.nix
modules/reference/hardware/jetpack/nvidia-jetson-orin/mk-esp-contents.py
packages/pkgs-by-name/flash-script/flash.sh
packages/pkgs-by-name/ghaf-installer/ghaf-installer.sh
packages/pkgs-by-name/open-normal-extension/open_normal.js

- Remove hardcoded GitHub client ID, make it configurable
- Add input validation to shell scripts to prevent path traversal
- Improve error handling in Python script to prevent info disclosure
- Add URL validation to JavaScript extension to prevent XSS
- Enhanced device validation in installer and flash scripts
- Remove Python cache file and update .gitignore
- Fix Python path validation to allow absolute paths and improve device/filename validation
1. Test the installer for any x86 target
2. Test the flashing of the AGX or NX device
3. Check that the ability to create a bug report with the github token
4. check that the "open in real browser" still works

Fix multiple code scanning security issues

---

docs/default.nix
docs/package-lock.json

docs: bump npm packages

---

modules/microvm/common/xdgitems.nix

Fix malformed mime type

---

targets/vm/flake-module.nix

VM configuration to run UI on host with givc and admin/net/audio VMs. Allows some simple, non-hardware related tests.
1. ...

feat(vm-target): simple host ui

---

docs/astro.config.mjs
docs/src/content/docs/ghaf/dev/technologies/fake-battery.mdx

docs: Add fake battery info

---

flake.lock
flake.nix
modules/common/systemd/hardened-configs/default.nix
modules/common/systemd/hardened-configs/nw-packet-forwarder.nix
modules/reference/profiles/mvp-user-trial.nix
modules/reference/services/chromecast/chromecast.nix
modules/reference/services/default.nix
modules/reference/services/nw-packet-forwarder/nw-packet-forwarder.nix

Service hardenings to address the battery draining issue caused by restoring the suspend state, while also enhancing security.
https://github.com/tiiuae/ghafpkgs/pull/87 must be merged first
1. Follow the test steps in SSRCSP-7293
2. Chromecast should still be working

Service hardenings 

---

modules/hardware/definition.nix
modules/microvm/host/microvm-host.nix
modules/reference/hardware/alienware/alienware-m18.nix
modules/reference/hardware/dell-latitude/definitions/dell-latitude-7230.nix
modules/reference/hardware/lenovo-x1/definitions/x1-2-in-1-gen-9.nix
modules/reference/hardware/lenovo-x1/definitions/x1-gen10.nix
modules/reference/hardware/lenovo-x1/definitions/x1-gen11.nix
modules/reference/hardware/lenovo-x1/definitions/x1-gen12.nix
modules/reference/hardware/lenovo-x1/definitions/x1-gen13.nix
modules/reference/hardware/system76/definitions/system76-darp11-b.nix

This commit removes the removePciDevice entry from various hardware configurations. Now microvms now able to shut down cleanly, the removePciDevice workaround is no longer necessary. This removal is cleanup effort to eliminate redundant configurations.
1. Please test Audio related test cases thoroughly.

Audio: Drop the removePciDevice workaround

---

modules/common/firewall/attack-mitigation.nix
modules/common/firewall/firewall.nix
modules/common/security/fail2ban.nix
modules/development/ssh.nix

* Adds `ssh` and `icmp` submodules under `ghaf.firewall.attack-mitigation` with `enable` and `rule` options.
* Set fail2ban `maxretry` value to 10 for debug builds based on a request from the test team.
1.

Extending attack-mitigation module options

---

docs/default.nix
docs/package-lock.json
docs/package.json

Docs: bump to the latest
