README.md
modules/development/authentication.nix
targets.nix

* Default account implemented as module. Easy to remove/harden.
* Tested with: nix build .#packages.x86_64-linux.vm result/bin/run-nixos-vm login with module configured username and password
* Module included only for "x86_64-linux" for now

dev: login to VM with preset development user account

---

.git-blame-ignore-revs

Because commits were rebased before merge, the commit-id of the reformat commit was changed. Fixing it.

Fix commit-id in .git-blame-ignore-revs

---

README.md
configurations/host/configuration.nix
targets.nix

* set initial host name to ghaf-host
* fix trace warning with "system.stateVersion"
* update documentation to run the host as VM and clean the qcow2 file

config: introduce host configuration.nix

---

docs/src/about/overview.md

* Reference implementation and link to NVIDIA Jetson with build instructions
* Maintain link to legacy reference - NXP iMX8

doc: update reference implementation

---

README.md
docs/src/SUMMARY.md
docs/src/build_config/build_configurations.md
docs/src/build_config/reference_implementations.md

* Main motivation is to ensure the relevant instructions are kept up-to-date with other system documentation instead of maintaining README outside of GH Pages
* Reference implementations added and structured based on testing with NVIDIA Orin AGX. This content is mainly from the old README.md Added prequisities with NVIDIA Orin AGX.

doc: refactored instructions to ghaf GH pages

---

modules/development/nix.nix
targets/nvidia-jetson-orin.nix

* import and configure as module
* enables flakes and nix-command to build ghaf image on host. NVIDIA Orin AGX is powerful after all.

dev: enable nix configuration as module

---

targets/default.nix

* requires vnclient to access the host - ::5900
* includes microvm and it's default VMMs to "host" VM
* enables microvm.nix defined guest VMs

host: support nested virtualization on x86 vm

---

hydrajobs.nix

Nuc build is needed for CI automatic testing.
VM is pretty unnecessary at least in it's current form for CI.
Signed-off-by: Tero Tervala <tero.tervala@unikie.com>

Add nuc and remove vm from hydra builds

---

modules/hardware/nvidia-jetson-orin.nix

Patch to NVIDIA Tegra kernel's devicetree to make rustvmm-based hypervisors work on NVIDIA Jetson Orin hardware

nvidia-jetson-orin: GICv3 devicetree patch

---

targets/default.nix

x86-nuc: enable flakes via nix-module

---

targets/default.nix

- Based on Mika's comment at: https://github.com/tiiuae/ghaf/pull/53#discussion_r1083911627
This reverts commit 5ce1cfd9f49caf8dd5719d2a3aeaa96c3ccb288f.

Revert "host: support nested virtualization on x86 vm"

---

docs/src/build_config/passthrough/nvidia_agx_pt_uart.md

Fix the platform@c000000 ranges, and fix serial@c000000 reg  cells size to 1. Without this fix, the VM was not able to load the virtio disk (vda1), because serial@c000000 registers where  overlapping.

Doc: update nvidia_agx_pt_uart.md

---

flake.lock
modules/hardware/nvidia-jetson-orin.nix

* Bump jetpack-nixos version in flake.lock
* The GICv3 patch is now part of the kernel that is included from jetpack-nixos, so just drop the patch

nvidia-jetson-orin: Remove GICv3 devicetree patch

---

flake.nix

The attribute that should be used is extra-trusted-substituters, not extra-subtituters

flake.nix: Fix extra-trusted-substituters

---

README.md
docs/README.md
docs/src/appendices/glossary.md
docs/src/build_config/build_configurations.md
docs/src/build_config/passthrough/nvidia_agx_pt_uart.md
docs/src/build_config/passthrough/passthrough.md
docs/src/index.md
docs/src/scs/scs.md
docs/style_guide.md

Made terms in the glossary in alphabetical order,
changed some links to terms in the glossary in a test mode.
Shields or badges are used in Markdown as cool link substitutes, another kind of label.

Docs: update glossary, add shields (badges)

---

modules/hardware/nvidia-jetson-orin.nix

Enabling systemd-networkd probably caused right kernel modules to get laoded, so that the NixOS firewall started working

Enable NixOS firewall on NVIDIA Jetson Orin

---

flake.lock
flake.nix

microvms should now work both on x86_64-linux and aarch64-linux.

Fix microvm.nix on x86_64

---

modules/hardware/nvidia-jetson-orin.nix
targets/nvidia-jetson-orin-flash-script.nix
targets/nvidia-jetson-orin.nix

* The flashing script can be used to flash the ghaf to NVIDIA Jetson Orin board, while the board is in the recovery mode
* ESP and root partitions are extracted from the regular Orin image
* Generate custom partition layout XML
* Change from default GRUB to systemd-boot, because GRUB doesn't seem to work out-of-the-box but systemd-boot does, when using eMMC partition to boot

Flash Script for NVIDIA Jetson Orin

---

docs/src/SUMMARY.md
docs/src/architecture/variants.md

* initial names and descriptions for intended architectural variants of the Ghaf platform with links to relevant, already defined architecture component ADRs and stack

architecture: variants

---

flake.nix

Remove unnecessary nixpkgs input from nixos-hardware, as nixos-hardware does not follow nixpkgs.

Unnecessary nixpkgs-input in nixos-hardware

---

flake.lock

* Fixes the hash mistmatch while building nvidia-display-driver

Update jetpack-nixos in flake.lock

---

modules/host/default.nix
modules/host/minimal.nix

Because of the current dependencies of a ghaf (systemd, grub/systemd-boot) it's impossible to reduce size of a host significantly. As main goal of minification ADR is to reduce TCB we can only configure those packages and remove all unnecessary modules.
Other modifications with the same goal can only be applied to specific hardware (e.g. configuring kernel). This can be seen from these two tables.
Timeline of changes of host size:
| State                           | Entries in /nix/store (raw-efi size) |
|---------------------------------|--------------------------------------|
| Default nixos config            | 498 (1.2G)                           |
| Minimal profile enabled         | 423 (1.1G)                           |
| Systemd-boot instead of grub    | 413 (1.1G) …

Add minimal host module

---

.git-blame-ignore-revs
modules/boot/systemd-boot-dtb.nix
modules/hardware/nvidia-jetson-orin.nix
modules/hardware/x86_64-linux.nix
modules/host/minimal.nix
targets/intel-nuc.nix
targets/vm.nix

- Fix formatting
- Use systemd-boot to load device tree
- Add new module to copy device tree into right place
- Make NVIDIA Jetson Orin target use the new module

systemd-boot-dtb: Load device tree using systemd-boot

---

modules/host/default.nix
modules/overlays/custom-packages.nix

This PR contains temporary fixes for cross-compilation issues which are present in `nixos-22.11` branch of `nixpkgs` that we are using as a dependency.
I decided to add fixes this way, because some of them are already fixed in newer branches of `nixpkgs`, but there is still no official release of next stable version of `nixpkgs` (nixos-23.05). I will re-check everything when we'll switch to nixos-23.05 and upstream all fixes that are not yet there.
Cross-compilation issues summary:
- Before this PR there were 3 packages which failed to build: `argyllcms`, `vte` and `pipewire`. `pipewire` is fixed by this PR, `argyllcms` is removed from `weston` dependencies by this PR.
- After fixing previous, build proceeds and 2 new packages with issues appeared: `freerdp` and `weston`. Those are fixed …

Fixing some cross-compilation issues

---

flake.lock
microvmConfigurations/netvm/default.nix
modules/development/packages.nix
modules/hardware/nvidia-jetson-orin.nix
modules/hardware/pci-passthrough-test.patch
modules/host/networking.nix
targets/intel-nuc.nix
targets/nvidia-jetson-orin.nix

Rebasing and fixes, and refactoring of Orin specific NetVM attributes to the target module, added by Mika Tammi.

Passthrough Jetson Orin WiFi card and Intel NUC Wifi Card to NetVM

---

modules/host/networking.nix

DHCPServer should only listen to network interface provided by virbr0, instead of globally listening to 0.0.0.0

Limit DHCPServer to virbr0 network

---

modules/hardware/nvidia-jetson-orin.nix

Vhost-vsock support in the host kernel is required for running Cuttlefish Virtual Android Devices. It's used by crosvm for communication between host and guest virtual machines.

Enable vhost virtio-vsock driver

---

modules/graphics/weston.ini.nix
modules/graphics/weston.nix
targets/common.nix
user-apps/default.nix
user-apps/gala/default.nix

As GALA app is a closed source peace of software yet, let's have it as pre-built for now.
I'd like to discuss directory structure for adding user applications - I've added new directory into the srcroot for now.
I also do not like the idea of having monolithic `weston.ini` file, but I did not get how to append text from other files/nixos modules.
Ideally, I'd like to add, for instance, weston launcher from the package's .nix file.
And yes, currently there is a mock icon used for Gala launcher.

Add GALA app as an example of user application

---

modules/graphics/weston.ini.nix
modules/windows/launcher.nix
targets/nvidia-jetson-orin.nix
user-apps/default.nix
user-apps/windows-launcher/default.nix

As Brian requested this pull request adds a script that can launch a Windows 11 virtual machine VHDX image downloaded from the [Windows Insider Preview ARM64 page](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewARM64).
Example:
`windows-launcher ./Windows11_InsiderPreview_Client_ARM64_en-us_25324.VHDX`
In addition to that it adds an icon to the Weston toolbar. When clicked for the first time it opens a file selection dialog. Once Windows 11 image has been selected it saves the path to the ~/.config/windows-launcher-ui.conf file and launches the virtual machine. When clicked next time it reads the path from the configuration file and immediately launches the VM. This way the user can launch a Windows virtual machine with a single click.
Signed-off-by: Yuri Nesterov …

Create a script to launch Windows VM

---

microvmConfigurations/netvm/default.nix
modules/host/networking.nix

This pull request moves the DHCP server from host to netvm. Network is provided to netvm by wifi card.
This removes wifi connectivity from host. However, host still has network connectivity though ethernet cable, which is
nice, since developer still can use `nixos-rebuild switch` to deploy changes to development board.
Also name of the internal network interface of the netvm is changed to more descriptive.

Move DHCP service from host to netvm

---

modules/overlays/custom-packages.nix

Remove remote desktop dependencies (freerdp, pipewire), and xwayland from weston.

Configure weston dependencies

---

modules/overlays/cross-compilation.nix
targets/nvidia-jetson-orin.nix

Overrides to pipewire are causing massive rebuilds for chromium for every target. Create separate overlay for fixes needed only for the cross-compilation.

Create overlay specific to cross-compilation

---

modules/overlays/custom-packages.nix

* This part of change was forgot from the previous cross-compilation overlay creation change.
* pipewire override is still part of the cross-compilation overlay

Remove pipewire from custom-packages

---

README.md
docs/src/SUMMARY.md
docs/src/appendices/glossary.md
docs/src/ref_impl/build_and_run.md
docs/src/research/run_win_vm.md

This PR updates the https://tiiuae.github.io/ghaf/ref_impl/build_and_run.html section with the following:
- The old command for building x86 VM image was replaced with the new one [Running Ghaf Image for x86 VM (ghaf-host)](https://tiiuae.github.io/ghaf/ref_impl/build_and_run.html#running-ghaf-image-for-x86-vm-ghaf-host): `nix run .#packages.x86_64-linux.vm` → `nix run .#packages.x86_64-linux.vm-debug`
- Added instructions on how to change labels for the Orin eMMC partitions to [Building and Running Ghaf Image for NVIDIA Jetson Orin AGX](https://tiiuae.github.io/ghaf/ref_impl/build_and_run.html#building-and-running-ghaf-image-for-nvidia-jetson-orin-agx)
- Minor text edits.

Docs: update Build and Run

---

targets/default.nix
targets/generic-x86_64.nix

Inheriting nixos hardware will allow defining
specific fw and drivers for a specific laptop
to specialize in a 'emergency'.
A more clean solution needs to designed by using
ghaf as a module.

Inherit nixos-hardware in generic-x86

---

docs/src/ref_impl/custom_product.md
docs/src/ref_impl/reference_implementations.md
templates/default.nix
templates/targets/aarch64/nvidia/orin-agx/flake.nix
templates/targets/aarch64/nvidia/orin-nx/flake.nix
templates/targets/aarch64/nxp/imx8/flake.nix
templates/targets/x86_64/generic/flake.nix

Ghaf is a framework to allow the easy creation of
virtualized edge devices. As such it should be
used to derive projects that are configured to
the specific use cases.
These templates allow for that easy creation.

Add templates to allow easy inheritance of Ghaf

---

modules/host/default.nix
modules/host/minimal.nix
modules/host/nogetty.nix
targets/common-release.nix

Draft implementation of minification ADR in form of nixos module that reflects it's structure.
Some ADR items are not reflected in the module options, since they are not directly related to minification and will be added as a result of code refactoring. Can be refactored to module that will provide options for high-level configuration of ghaf host system (e.g enable/disable gui, update system, read only filesystem). 
Currently implementation is incomplete because of infinite recursion caused by conditional modules importing.

Host minification module

---

flake.nix
user-apps/default.nix

Export windows-launcher package only for aarch64-linux from flake packages.

windows-launcher package only for aarch64-linux

---

overlays/custom-packages.nix
overlays/systemd-timesyncd-disable-nscd.patch

In Ghaf date and time are synchronized using systemd-timesyncd service. In order to get the correct date and time it requires a working internet connection. However, internet connection doesn't work when the current date and time are not correct because we have Domain Name System Security Extensions (DNSSEC) enabled. This leads to a chicken and egg problem. It's especially bad for Nvidia Orin devices since they don't have batteries for RTC.
Systemd-timesyncd resolves this issue by setting SYSTEMD_NSS_RESOLVE_VALIDATE=0 environmental variable in the unit configuration file. It disables DNSSEC validation for the timesyncd service so that it can connect to the NTP server even if current date and time is incorrect. However, this option doesn't work in Nix because it uses NSCD instead of …

Fix date and time synchronization issues

---

docs/src/architecture/adr.md
docs/src/architecture/adr/platform-bus-passthrough-support.md

This ADR is WIP notes for Platform bus passthrough implementation for RustVMM-based hypervisors.

Platform bus  support ADR

---

docs/book.toml
docs/doc.nix
docs/plugins/mdbook-footnote.nix

* on popular demand - example of adding mdbook-plugins, https://github.com/daviddrysdale/mdbook-footnote
* tested to generate footnote with "Normal text{{footnote: Or is it?}} in body." from docs/src/index.md using "nix build .#doc" Test footnote left out of the commit intentionally.

doc: add mdbook-footnote plugin

---

modules/hardware/nvidia-jetson-orin/jetson-orin.nix

Add ghaf logo to boot screen of edk2 uefi bootloader.

nvidia-jetson-orin: uefi: Add ghaf logo to boot

---

flake.nix
modules/host/default.nix
modules/virtualization/microvm/microvm-host.nix
modules/virtualization/microvm/netvm.nix
targets/generic-x86_64.nix
targets/imx8qm-mek.nix
targets/nvidia-jetson-orin.nix
targets/vm.nix

* Move from flake-based microvm-configuration to declarative
configuration.
* Cross-compilation enabled for NetVM, when host has cross-compilation
enabled.
* Refactored modules/host from function to a nixosModule.
* While building documentation, microvm-host.nix does not need to be
filtered out anymore.

Declarative NetVM

---

docs/src/research/run_win_vm.md
modules/windows-launcher/default.nix
targets/generic-x86_64.nix
user-apps/default.nix
user-apps/windows-launcher/default.nix

This pull request adds windows launcher to generic x86_64 image. It can be launched with either an ISO image or QCOW2:
`Usage: windows-launcher ./Win11_22H2_English_x64v2.iso or ./win11.qcow2`
When the script launched with an ISO image it creates an empty QCOW2 image in the same directory which is used as a system disk in the VM. After Windows 11 has been installed the script should be launched with the QCOW2 image.
How to run Windows 11 VM:
- Download Windows 11 ISO from [https://www.microsoft.com/software-download/windows11](https://www.microsoft.com/software-download/windows11)
- Run `windows launcher ./Win11_22H2_English_x64v2.iso` and hit any key to boot from the ISO.
- In order to bypass Windows 11 system requirement hit `Shift+F10` to open a command prompt and type `regedit`. In …

Add windows launcher for x86_64

---

templates/targets/aarch64/nvidia/orin-agx/flake.nix

I was testing the Jetson Orin Agx flake template and git an error when running `nix flake check`. I think the target name was incorrect when checking the available outputs from Ghaf where agx and nx targets had been separated.

Correct target name in Nvidia Jetson Agx template flake

---

hydrajobs.nix

Add toplevel derivations of cross-compiled NVIDIA Jetson Orin configurations to Hydra jobs, to cache cross-compiled packages.

Cache NVIDIA Jetson Orin cross-compiled packages

---

modules/graphics/weston.ini.nix

When adding launchers on weston panel, new launchers override existing weston-terminal launcher which has to be enabled explicitly in this case.

weston.ini: Keep weston-terminal launcher

---

flake.nix
hydrajobs.nix

Demoapps fail to cross-compile currontly, so add another versions of NVIDIA Jetson Orin cross-compilation hydra jobs, which don't include demo apps.

Cache versions without demo apps

---

docs/src/SUMMARY.md
docs/src/scenarios/run_cuttlefish.md

This adds a new document with instructions on how to run Cuttlefish (Android VM). This is a temporary version. It will be updated once Cuttlefish is nixified and fully integrated in Ghaf.
Thanks @jenninikko for proofreading and converting the Confluence article to markdown.

doc: add instructions how to run Cuttlefish (Android VM)

---

modules/hardware/nvidia-jetson-orin/jetson-orin.nix
modules/hardware/nvidia-jetson-orin/pci-passthrough-nx-test.patch
targets/nvidia-jetson-orin.nix

The configuration of Orin devices moved to modules/hardware/nvidia-jetson-orin. Multiple devices for passthrough can be added. ACS Security override patch included for Orin Nx.

Orin Nx Ethernet Passthrough

---

lib/mk-flash-script.nix

It have proper selection of architecture inside jetpack guts, so no need to force system selection here

Remove requirement of aarch64-linux builder for EFI stuff

---

modules/development/debug-tools.nix
targets/lenovo-x1-carbon.nix

Lenovo X1 touchpad doesn't work on every boot. The reason for that is that the touchpad has two input devices with the same dev link. In this PR I updated udev rules to create separate links and pass them both to the GUIVM. I also added evtest to debug-tools which is really useful for debugging input devices.
Fixes SP-2889

Fix Lenovo X1 touchpad passthrough

---

modules/hardware/nvidia-jetson-orin/jetson-orin.nix
targets/nvidia-jetson-orin.nix

Separation of netvmExtraModules caused a bug in agx wireless, where this was fixed by adding appropriate corrections. Wireless condition for agx is improved. A small fix was added for docker (where it is not included if it is not enabled) in case it is planned to add for support.

AGX Wireless bug fix

---

targets/lenovo-x1-carbon.nix

This is another fix for the Lenovo X1 touchpad passthrough.
I noticed that sometimes Lenovo X1 boots to black screen and the GUIVM fails to start. It turned out that the touchpad has two devices under the same name: PS/2-style mousedev (/dev/input/mouse*) and evdev (/dev/input/event*). When the legacy mousedev device comes first the GUIVM fails to start with the following error: "/dev/mouse: is not an evdev device".
In this patch I added an additional filter to the udev rules to make sure we always use event devices for the passthrough.

Update Lenovo X1 udev rules to use evdev input devices

---

flake.lock
modules/virtualization/microvm/appvm.nix
modules/virtualization/microvm/guivm.nix
modules/virtualization/microvm/netvm.nix
overlays/custom-packages.nix
targets/lenovo-x1-carbon.nix

The behavior onwards from now, is the same as if the microvm.qemu.bios.enable is always set to false.

Update microvm in flake.lock

---

modules/hardware/nvidia-jetson-orin/jetson-orin.nix

Configure nvpmodel to use profile number 3 by default, which enables all CPU cores on Orin AGX and NX devices. This causes AGX to use 50W and NX to use 25W of power.
This also probably fixes random boot time failures of nvpmodel.service

Configure nvpmodel to use profile number 3

---

modules/graphics/default.nix
modules/graphics/demo-apps.nix
modules/graphics/weston.ini.nix

Allow precise control to include/exclude GUI demo application, as well as add firefox as second browser.

Refactor demo apps inclusion

---

modules/virtualization/microvm/appvm.nix
modules/virtualization/microvm/guivm.nix
modules/virtualization/microvm/netvm.nix

/nix/store is shared read-only from the host, and in debug mode, there is read-write tmpfs overlay on top of it, which allows usage of `nix-shell -p ...` inside the virtual machine.
Great way to save space in the images.

Shared /nix/store and read-write tmpfs overlay

---

modules/virtualization/microvm/appvm.nix
modules/virtualization/microvm/guivm.nix
overlays/custom-packages.nix
targets/lenovo-x1-carbon.nix
user-apps/vsockproxy/default.nix

This PR makes Waypipe work over VSOCK instead of UNIX domain sockets. It increases performance by getting rid of the unnecessary overhead caused by forwarding UNIX sockets over SSH. Testing with iperf show that UNIX sockets over SSH can transfer about 4 Gbits/sec on Lenovo X1 Carbon but with VSOCK it can handle about 15 Gbits/sec between GUIVM and APPVMs.

Setup vsock devices for APPVMs and use it for Waypipe

---

modules/host/default.nix

Conditionally add withRepart=false; to systemd override. When building against nixos-unstable, fixes:
`error: assertion '(withRepart -> withCryptsetup)' failed`

Add withRepart=false; to systemd override

---

docs/src/ref_impl/creating_appvm.md
modules/host/networking.nix
modules/virtualization/microvm/appvm.nix
modules/virtualization/microvm/common/vm-networking.nix
modules/virtualization/microvm/guivm.nix
modules/virtualization/microvm/netvm.nix
targets/lenovo-x1-carbon.nix

*Introduce new naming pattern for VMs
All VMs' names/hostnames are created using '<vmname>-vm' pattern. All VMs' network interfaces named using
'tap-<hostname>' pattern. NetVM's bridge is configured to include all 'tap-*' interfaces.
This approach makes no distinction between service VMs and application VMs, but it allows to easily guess the hostname without using a network toolkit.
*Introduce .ghaf local domain.
All VMs except of NetVM now get their IPs from NetVM's DHCP server. The VMs are accessible by their hostnames with .ghaf postfix added, for instance, 'ssh gui-vm.ghaf'.
*All VMs use separate subnet from now on, which is different from the debug-subnet.
*The network configuration which is common for every VM is now extracted into the separate 'vm-networking.nix' file.

Refactor VM networking

---

.github/workflows/build-yml-check.yml
.github/workflows/build.yml

This PR replaces the original proof-of-concept in PR https://github.com/tiiuae/ghaf/pull/282.
Main changes:
- Allow running build workflow for PRs that originate from forks by using the `pull_request_target` trigger. Require approval for running the workflow for external contributions.
- For internal contributions as well as for approved external changes, run the selected build targets, pushing the build artifacts to development cache (cachix). 
For full details, see: https://ssrc.atlassian.net/wiki/spaces/SP/pages/845348920/Authorizing+external+contributors+in+GitHub+actions

Run nix build in github actions

---

modules/graphics/weston.ini.nix
overlays/custom-packages.nix
overlays/weston-backport-workspaces.patch

Multiple workspaces support was removed about a year ago in this merge request: https://gitlab.freedesktop.org/wayland/weston/-/merge_requests/924
This PR enables it back for the upcoming demo. It's a temporary solution until we switch to a wlroots based compositor.

Enable support for multiple workspaces in Weston

---

.github/workflows/build.yml

This commit changes the PR builder action to use [cachix/install-nix-action](https://github.com/cachix/install-nix-action) instead of
[DeterminateSystems/nix-installer-action](https://github.com/DeterminateSystems/nix-installer-action) to install nix in the PR builder workflow.
This change is needed to fix the PR builder workflow build issue for lenovo-x1-carbon-gen11 targets.
It's still unclear why, but using [DeterminateSystems/nix-installer-action](https://github.com/DeterminateSystems/nix-installer-action) in the builder workflow started failing for lenovo-x1-carbon-gen11 somewhere between Monday 2.10.2023 and Friday 6.10.2023. The builder action was not merged to Ghaf yet, so we can't clearly see at which point the failure started. Example error trace from the eariler build failure …

GhA: fix PR builder for lenovo-x1-carbon-gen11

---

modules/windows-launcher/default.nix
user-apps/default.nix
user-apps/windows-launcher/default.nix

Change spice to enableSpice in package arguments. This is because there exists a package called spice, so when called through callPackage the spice argument gets filled with that package, instead of defaulting to false.

windows-launcher: Change spice to enableSpice

---

user-apps/windows-launcher/default.nix

In #290 network interface name pattern was changed from "vm-\*" to "tap-\*". This PR changes it in the windows-launcher as well so that the Windows VM can get network access through the netvm bridge.

Fix netdev name in the windows-launcher

---

modules/development/debug-tools.nix
overlays/cross-compilation.nix

This also reverts commit eaa960c84516f4887fea50e29f4b0bee529980f0.
It now builds, although require more work on it.
I don't like extra patch file too much, it does too much unrelated changes (patch borrowed from https://lore.kernel.org/buildroot/20230525215103.37218-3-svromanov@sberdevices.ru/T/ ).

Fix sysbench cross-compiling

---

.github/workflows/build.yml

Cancel any in-progress build workflow runs from the same PR when a new version of the PR is pushed.
Before this change, pre-merge build workflows would continue to run even if a new version of the PR was pushed.
This change was tested in a forked repository. As an example, the following workflow run in the forked repo was canceled due to new changes pushed to PR while an earlier build was still in-progress: https://github.com/henrirosten/ghaf/actions/runs/6470895940

GhA: Cancel in-progress builds on new trigger

---

modules/hardware/nvidia-jetson-orin/jetson-orin.nix
modules/hardware/nvidia-jetson-orin/partition-template.nix
targets/nvidia-jetson-orin/default.nix

Add variant of flash script, which only flashes QSPI partitions, and not eMMC at all. Also does not build boot & root images so it is faster and lighter to build.

Orin AGX/NX: Add QSPI only variant of flash script

---

overlays/custom-packages.nix
overlays/waypipe-window-borders.patch
targets/lenovo-x1-carbon.nix

Colored window borders currently drawn in waypipe when it runs in server mode. They are used for the information purposes. This can be considered a temporary solution until we get support for colored window borders in the compositor.

Add support for colored window borders

---

.github/workflows/doc.yml

This PR makes the following changes to the github workflow that builds and deploys github pages:
- Use GITHUB_TOKEN to deploy github pages
- Only deploy github pages if the push to main branch changes the content under `docs/`

Deploy github-pages with github token

---

.github/workflows/build.yml

Add following new pre-merge build targets:
- x86_64-linux.nvidia-jetson-orin-nx-debug-nodemoapps-from-x86_64
- riscv64-linux.microchip-icicle-kit-debug
- x86_64-linux.doc
This change was tested in a forked repo: https://github.com/henrirosten/ghaf/actions/runs/6654144039

GhA: Add more pre-merge build targets

---

flake.lock

• Updated input 'nixpkgs':
'github:NixOS/nixpkgs/5cfafa12d57374f48bcc36fda3274ada276cf69e' (2023-09-27)
→ 'github:NixOS/nixpkgs/aeefe2054617cae501809b82b44a8e8f7be7cc4b' (2023-11-05)

Update nixpkgs in flake.lock

---

.github/workflows/build.yml

This PR makes the following changes:
- Start building aarch64 targets in the github actions build workflow.
- Add (aarch64) remote builder support to the github-hosted runners used in ghaf pre-merge builds.
This change was tested in a forked repo, see: https://github.com/henrirosten/ghaf/pull/15 and the build results at: https://github.com/henrirosten/ghaf/actions/runs/6859836639.
The remote builder configuration is in https://github.com/tiiuae/ghaf-infra/pull/17: it's an Ubuntu aarch64 host with nix package manager installed, configured to allow remote builds over ssh with the buildfarm private key. The buildfarm key is currently stored as a repository secret (secrets.BUILDER_SSH_KEY) in the ghaf repo.
This PR adds the aarch64 pre-merge build targets "nvidia-jetson-orin-nx-debug" and …

GhA: add aarch64 remote builder and build targets

---

modules/virtualization/microvm/guivm.nix

This patch sets static IP address (192.168.101.3) for gui-vm to debugging subnet.
Task: SP-3252

Set static IP for gui-vm

---

modules/users/accounts.nix
modules/virtualization/microvm/guivm.nix
overlays/custom-packages/default.nix
overlays/custom-packages/nm-launcher/default.nix
targets/lenovo-x1-carbon.nix
user-apps/nm-launcher/default.nix

Add NetworkManager to the net-vm of the Lenovo X1 Carbon target to manage external network interfaces of the net-vm. Also add the nm-applet package to the gui-vm.
The nm-launcher script is added to create SSH-tunnel to forward D-Bus messaging between net-vm and gui-vm so that nm-connection-editor GUI-application in gui-vm controls NetworkManager core in net-vm.
Usage:
- Click on the corresponding icon to launch the nm-connection-editor.
- Double click "Wifi-1" to edit the default WiFi connection.
- Set the SSID on the "Wi-Fi" tab and password on the "Wi-Fi Security" tab.
Note:
It is possible to set SSID and password before building the image. Just edit values at targets/lenovo-x1-carbon.nix.

Add NetworkManager to net-vm and nm-applet to gui-vm for Lenovo X1

---

flake.nix
templates/targets/aarch64/nvidia/orin-agx/flake.nix
templates/targets/aarch64/nvidia/orin-nx/flake.nix
templates/targets/aarch64/nxp/imx8/flake.nix
templates/targets/riscv64/microchip/polarfire/flake.nix
templates/targets/x86_64/generic/flake.nix

We will be changing to a new cache server soon and this is the new public key. Not to be merged yet, but reviewed and approved so it's ready to go.

Change cache.vedenemo.dev public key to new key

---

modules/hardware/nvidia-jetson-orin/optee.nix
modules/module-list.nix
modules/profiles/debug.nix
targets/nvidia-jetson-orin/optee.nix

Commits adds OP-TEE's xtest. Xtest is added only for Orin NX. 
Xtest ran on Orin NX and following tests fails:
- 1008: Loads corrupt TA. Test requires TA directory path at the compile time, but currently it would end up with infinite recursion.
- 1033: Plugin test case. Plugin support can be disabled or passing an extra argument to tee-supplicant
- 4016_ed25519: One of the function uses uninitialized parameter. Fix requires OP-TEE [patch.](https://github.com/OP-TEE/optee_os/commit/e4c24b7f9f1afbdd7a48766007cf0055b4b8df6b)

Add OP-TEE's xtest (orin nx)

---

modules/hardware/nvidia-jetson-orin/agx-netvm-wlan-pci-passthrough.nix
modules/hardware/nvidia-jetson-orin/default.nix
modules/hardware/nvidia-jetson-orin/jetson-orin.nix
modules/hardware/nvidia-jetson-orin/nx-netvm-ethernet-pci-passthrough.nix
modules/hardware/nvidia-jetson-orin/pci-passthrough-common.nix
targets/nvidia-jetson-orin/default.nix

Instead of enabling WLAN PCI Passthrough for Orin AGX or Ethernet PCI Passthrough always in the jetson-orin.nix module, refactor options for AGX and NX PCI Passthroughs, which will enable or disable PCI Passthrough related functionality and patches from the NVIDIA Jetson Orin modules.

Options for AGX and NX PCI Passthroughs

---

targets/lenovo-x1-carbon.nix

This is a stepping stone to moving Gnome to its own module in another repo.

Disable Gnome as a target

---

modules/hardware/nvidia-jetson-orin/default.nix
modules/hardware/nvidia-jetson-orin/ota-utils-fix.nix

setup-jetson-efi-variables.service failed to start on cross-compiled builds, this seems to be caused by non-working patchShebangs. Adding an overlay which fixes the shebang lines of the scripts in the end of the installPhase.
- [-] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR
- [- Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/
- [-] Author has run `nix flake check --accept-flake-config --allow-import-from-derivation` and it passes
This is a rather small change, and it is clear that it only affects Orin AGX and Orin NX targets.
Tested on both Orin AGX and Orin NX. Tested also that non-cross-compiled builds do not break.
How to test:
Simply run `systemctl status setup-jetson-efi-variables.service`, and see that …

jetpack-nixos: Fix otaUtils cross-compilation

---

nix/checks.nix
nix/devshell.nix

This reduces the memory load of `nix flake check` to ~15GB by making it more sequential.
Changes the scope of nix-flake check to being more streamlined, to reduce memory consumption runaway.
- [-] More detailed description in the commit message(s)
- [-] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR
- [-] Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/
- [-] PR linked to architecture documentation and requirement(s) (ticket id)
- [-] Test procedure described (or includes tests). Select one or more:
<How this was tested by the author? How is this supposed to be tested by people doing system testing?>

checks: Improve nix flake check performance

---

flake.lock

Many new vulnerabilities identified in firefox,
bumping the flake lock to address those.
https://github.com/tiiuae/ghafscan/blob/main/reports/main/packages.x86_64-linux.generic-x86_64-release.md#vulnerabilities-fixed-in-ghaf-nixpkgs-upstream
nix flake lock --update-input nixpkgs
- [X More detailed description in the commit message(s)
- [-] Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/
- [-] PR linked to architecture documentation and requirement(s) (ticket id)
<How this was tested by the author? How is this supposed to be tested by people doing system testing?>

Bump: flake.lock for nixpkgs

---

targets/nvidia-jetson-orin/optee.nix

Store object "optee-load-path" contains Import From Derivation (IFD) in which _builtins.readDir_-function requires realization of _opteeXtest_-derivation. Removing IFD by replacing opteeXtest-derivation reference with explicit list of TAs.
OrinNX: OP-TEE's xtest executes as expected (three failures).

Remove IFD from optee-load-path

---

overlays/custom-packages/wifi-connector/default.nix
packages/wifi-connector/default.nix
targets/lenovo-x1-carbon.nix

Now when NetworkManager is in use for NetVM, edit the script to use nmcli to avoid any conflicts.

wifi-connector: Support nmcli interface

---

.github/pull_request_template.md

As of the recent improvements, the `--allow-import-from-derivation` argument to `nix flake check` is no longer needed.
Run `nix flake check` without `--allow-import-from-derivation´

No more need for --allow-import-from-derivation

---

packages/wifi-connector/default.nix

Fix formatting again
Run `nix fmt` and see that there are not any changes

Fix formatting again by running `nix fmt`

---

modules/boot/systemd-boot-dtb.nix

Use full paths inside script generated by systemd-boot-dtb module.
This commit broke our script, so now using full paths to commands instead: https://github.com/NixOS/nixpkgs/commit/ecd89093e178e50ead57e3338f25e637dd29310b
Test by running `nixos-rebuild --flake .#nvidia-jetson-orin-nx-debug --target-host root@nx --fast boot` OR `nixos-rebuild --flake .#nvidia-jetson-orin-agx-debug --target-host root@agx --fast boot`

systemd-boot-dtb: Fix 23.11 remote nixos-rebuild

---

docs/src/ref_impl/development.md

* Fixes instructions for `nixos-rebuild switch` with Ghaf
* Updates stale links
* Adds note on access to host over SSH with -debug targets
Kudos Vunny Sodhi for testing the instructions and reporting the issue.
`nixos-rebuild --flake .#lenovo-x1-carbon-gen11-debug --target-host root@<ip_address_of_ghaf-host> --fast switch`

fix: development instructions for nixos-rebuild switch

---

flake.lock

• Updated input 'flake-parts':
'github:hercules-ci/flake-parts/8c9fa2545007b49a5db5f650ae91f227672c3877' (2023-11-01)
→ 'github:hercules-ci/flake-parts/34fed993f1674c8d06d58b37ce1e0fe5eebcb9f5' (2023-12-01)
• Updated input 'flake-utils':
'github:numtide/flake-utils/ff7b65b44d01cf9ba6a71320833626af21126384' (2023-09-12)
→ 'github:numtide/flake-utils/4022d587cbbfd70fe950c1e2083a02621806a725' (2023-12-04)
• Updated input 'microvm':
'github:astro/microvm.nix/b16e6261ad2f0bca6ac2a4b7a4d3377cf5e3d95d' (2023-11-18)
→ 'github:astro/microvm.nix/89bb7a5230a4820736a43e058c8d2a2c560d672b' (2023-11-28)
• Updated input 'nix-fast-build':
'github:Mic92/nix-fast-build/96805cafb2bc678ce15eda386989f9e79b28868b' (2023-11-16)
→ 'github:Mic92/nix-fast-build/25e19950f019adea4ca1b490e116a6acc0669e31' …

flake.lock update

---

.github/workflows/build.yml

Don't use nodemoapps versions of NVIDIA Jetson Orin AGX and NX targets, but build full versions instead.
Tested that it is possible to build the full cross-compiled targets:
`nix build .#nvidia-jetson-orin-agx-debug-from-x86_64-flash-script`
`nix build .#nvidia-jetson-orin-nx-debug-from-x86_64-flash-script`

github workflows: Don't use nodemoapps versions

---

modules/virtualization/microvm/appvm.nix
modules/virtualization/microvm/guivm.nix
modules/virtualization/microvm/netvm.nix
targets/lenovo-x1-carbon.nix

Minor bugfix for setting timezone only for Lenovo X1 target and not for other hardware targets.
Fixed a bug of some VMS using Dubai timezone while host used UTC.
Dubai timezone should be only on Lenovo X1 target (demo reference).
- [-] Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/
- [-] Test procedure described (or includes tests). Select one or more:
Lenovo X1 timezone should be set to Dubai
Other targets timezone should be UTC.

Set static timezone of Dubai only for Lenovo X1 target

---

docs/src/SUMMARY.md
docs/src/ref_impl/development.md
docs/src/ref_impl/remote_build_setup.md

- Added the remote_build_setup.md documentation to improve clarity on the process of setting up remote builds on NixOS. (Added under docs/src/ref_impl)
- Updated the ghaf/docs/src/SUMMARY.md and ghaf/docs/src/ref_impl/development.md to indicate the addition of the remote_build_setup.md file. 
The added documentation was reviewed for clarity, accuracy, and completeness and has been validated.

Add remote build setup instructions.

---

.github/workflows/scorecard.yml
README.md

Add OpenSSF scorecard github action
Add OpenSSF Scorecard github action and scorecard badge to README which also operates as a link to scorecard report.
Tested scorecard functionality in github action and compared to command line output to verify results.
Scorecard badge works on README.md in my fork.

OpenSSF scorecard report

---

flake.lock
modules/firewall/default.nix
modules/firewall/kernel-modules.nix
modules/module-list.nix
targets/microchip-icicle-kit.nix

**Enable bunch of firewall related kernel modules for icicle-kit.**
Add new ghaf.firewall.kernel-modules -module, which enables bunch of
netfilter/iptables modules. Update flake.lock file to nixos-hardware
version which supports patching kernel and enabling new options
through boot.kernelPatches.
• Updated input 'nixos-hardware':
'github:NixOS/nixos-hardware/7763c6fd1f299cb9361ff2abf755ed9619ef01d6' (2023-12-13)
→ 'github:NixOS/nixos-hardware/172385318068519900a7d71c1024242fa6af75f0' (2024-01-05)
Needs modification to nixos-hardware https://github.com/NixOS/nixos-hardware/pull/826 which allows to override kernelPatches.
Build & run on Microchip Polarfire Icicle Kit.
Run `systemclt status firewall` and expect it to see running without errors.

icicle-kit: Fix firewall

---

.reuse/dep5

Add .cer and .p12 extensions to dep5 list. Those key/certificate file types are used for example by mitmproxy.

reuse: add .cer and .p12 file types to dep5 configuration

---

modules/hardware/nvidia-jetson-orin/partition-template.nix
modules/hardware/nvidia-jetson-orin/sdimage.nix

On NVIDIA Jetson Orin AGX, extract ESP and root partitions while running the flashing script, instead of shipping the images twice in the store path. This should make NVIDIA build targets take half the disk space the used to.
Build and run NVIDIA Orin AGX flash scripts, both native and cross. Changes should not affect NX flash scripts.

Orin AGX: Extract partitions while flashing

---

overlays/custom-packages/systemd/default.nix

The systemd package was patched nixpkgs upstream, causing the build against nixos-unstable to break, because same patch is about to be applied twice. Check if the patch is already present, and don't do timesync related overrides if it is.
Test by changing `nixpkgs` flake input to `nixos-unstable`. Try to build things

Conditionally enable systemd timesyncd patch

---

modules/graphics/labwc.nix
modules/graphics/weston.nix
modules/virtualization/microvm/guivm.nix

Running applications from appvms with waypipe doesn't work when labwc is enabled. The reason is the waypipe service configured to use the wayland-1 socket which is created by systemd for weston and labwc. However, labwc doesn't have systemd integration and instead of using wayland-1 it creates its own socket which is wayland-0 by default.
This PR makes waypipe use the correct socket from the WAYLAND_DISPLAY environmental variable both for weston and labwc. It also removes the unused wayland-1 socket in labwc module and improves weston startup sequence to leverage systemd integration.
- Enable labwc by uncommenting `profiles.graphics.compositor = "labwc";` in the guivm.nix.
- Build an image for lenovo x1, boot and ssh to zathura-vm.ghaf.
- Run `waypipe --vsock -s 1100 server zathura`.

Fix waypipe in labwc

---

docs/src/ref_impl/creating_appvm.md
modules/graphics/default.nix
modules/graphics/demo-apps.nix
modules/graphics/fonts.nix
modules/graphics/waybar.config.nix
modules/graphics/weston.ini.nix
modules/hardware/definition.nix
modules/profiles/applications.nix
modules/profiles/graphics.nix
modules/windows-launcher/default.nix
overlays/custom-packages/labwc/default.nix
packages/wifi-signal-strength/default.nix
targets/lenovo-x1-carbon.nix
targets/nvidia-jetson-orin/default.nix

Waybar configuration modified based on the default bar configuration and launchers added. 
Pulseaudio, network and battery/power adapter icons implemented. 
Weston and waybar launchers are unified and name section added.
- [-] Tested on Jetson Orin NX or AGX `aarch64`
- [-] Tested on Polarfire `riscv64`
1. Uncomment to set the compositor as "labwc" [here](https://github.com/tiiuae/ghaf/blob/main/modules/virtualization/microvm/guivm.nix#L24).
2. Rebuild with the change.
3. Flash the image and boot.

Introduce to Waybar

---

packages/powercontrol/default.nix
targets/lenovo-x1-carbon.nix

This PR introduces:
- The package PowerControl, which provides scripts to power control the host via ssh;
- Refactored ssh keys generation and sharing on Lenovo X1 target
- Add poweroff and reboot buttons on Lenovo X1 host in GUI
Works only on debug builds so far -- we need ssh-connection in release builds as well
Build debug target on Lenovo X1, run it, you will see two buttons in GUI VM next to applications icons: PowerOff and Reboot. They should make described actions

PowerControl over ssh

---

.reuse/dep5

Minor fixup of `.reuse/dep5` formatting
Should pass reuse check on CI

Use more compact notation in .reuse/dep5

---

overlays/cross-compilation/default.nix
overlays/cross-compilation/pipewire.nix
packages/vsockproxy/default.nix

Fix crosscompilation of broken chain `pipewire -> ffado -> pyqt -> qt*` by disabling `ffado`.
I believe we never would use firewire for audio source/sink on our cross-compiled devices.
(probably refactor upstream ffado to split to ffado and ffado-gui would be proper solution, I even tried to do it couple years ago)
Also this PR contain quickfix for vsockproxy cross-compilation, which is pretty hacky and would need revisit in future.
(see code comment for details)
These fixes unblock building, build proceeds to big packages such as electron

fix cross-build for vsock and pipewire

---

targets/nvidia-jetson-orin/optee.nix

Depricated warnings are being shown as the upstream jetpack has changed the optee namespace for TAs. This patch uses the proposed namespace confentions as suggested in the warning message
- [] Ghaf documentation updated with the commit - https://tiiuae.github.io/ghaf/

Fix deprecated warning for optee namespace

---

modules/virtualization/microvm/appvm.nix
targets/lenovo-x1-carbon.nix

This is a proof of concept XDG handler for PDF files. 
When a user attempts to open a PDF file from Chromium, it executes the openpdf script. The script sends the PDF file path to the GUIVM over a TCP connection. The GUIVM copies the file from chromium-vm to a temporary location in the zathura-vm and opens it there. Once the viewer is closed, the file is deleted from the zathura-vm.
Sending the file path over a TCP connection with the netcat is obviously not ideal. It should be updated once we have some inter-vm communication mechanism developed. Also, using the scp command might not be needed once we have support for permanent file storage.
1. Connect to the internet.
2. Open Chromium browser and download any PDF file.
3. Click on the downloaded PDF and make sure it opens in zathura-vm. …

Add an XDG handler for PDF files to the chromium-vm

---

.github/workflows/build.yml

Fix pre-merge build workflow: on installing `inxi` package during the build step `Print runner system info`, apt-get update needs to be run before apt-get install to make sure apt index is not stale as instructed in the relevant [documentation](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/customizing-github-hosted-runners#installing-software-on-ubuntu-runners):
> Note: Always run sudo apt-get update before installing a package. In case the apt index is stale, this command fetches and re-indexes any available packages, which helps prevent package installation failures.
Tested the change in a forked repo at: https://github.com/henrirosten/ghaf/pull/21.

GhA: build: update before apt-get install

---

modules/module-list.nix
modules/security/tpm2.nix
modules/users/accounts.nix
overlays/custom-packages/default.nix
overlays/custom-packages/tpm2-pkcs11/default.nix
targets/lenovo-x1-carbon.nix

This adds the initial support by providing a PKCS11 interface on the host system for the X1 Carbon, utilising the hardware TPM2.
We had to temporarily disable Feature API (FAPI) by overlaying the package, as the tests were failing. And we don't use it anyways.
Added TPM2-PKCS11 package and double-checked it worked.
How to test:
1. SSH into the debug system.
2. SSH into host: `ssh 192.168.101.2`
3. Create an alias: `alias tpm2pkcs11-tool="pkcs11-tool --module /run/current-system/sw/lib/libtpm2_pkcs11.so"`
4. Test: `tpm2pkcs11-tool --list-token-slots`
Find more details on this page: https://github.com/tpm2-software/tpm2-pkcs11/blob/master/docs/INITIALIZING.md

Add TPM2-PKCS11 support for X1 Carbon

---

modules/partitioning/disko-basic-postboot.nix
targets/lenovo-x1-carbon.nix

Enlargen the LVM partition on first boot
Ready for review!
Flash the Lenovo X1 Carbon image to USB disk. Boot from it. After boot run `df -h` and `lsblk` to see that the filesystem and partition have been really resized. The root-filesystem should fill the originally empty space from the disk, just like in this screenshot.

Enlargen the LVM partition on first boot

---

modules/graphics/fonts.nix
modules/graphics/waybar.config.nix

Hack font is integrated to labwc for weston-terminal application.

Labwc fonts

---

overlays/custom-packages/systemd/default.nix

On checking if the systemd timesyncd patch is applied nixpkgs upstream, do not require a match on the sequential patch file number. Patches can be applied in different order, or the total number of patches might change over time, so it's incorrect to assume the timesyncd patch would always have the sequential order number of '0020'.
Also, please consider the suggestion below:
> _... on longer term, I believe the correct course of action, if possible, would be to get rid of the Ghaf [systemd override](https://github.com/tiiuae/ghaf/blob/cfec51ba6330a1236f8a4395fdc31ee5ed28e260/modules/host/default.nix#L32-L45) altogether, so we would not have to rebuild systemd for Ghaf. As a benefit of doing that we would get rid of the re-builds of systemd, and more importantly, the massive rebuilds of …

Ignore patch file number in shouldOverride

---

targets/microchip-icicle-kit/flake-module.nix

Use cross-compilation overlay through self instead of directly importing it from path.
This again did not cause any rebuild.

targets: Make icicle-kit use overlays through self

---

modules/desktop/graphics/labwc.nix
modules/microvm/virtualization/microvm/guivm.nix

This patch will add functionality of checking if there is no user interaction with the system for 5 minutes, it will lock the screen resulting in the user needing to type the password to unlock the system.
This feature can be enabled by making following code change
```
+++ b/modules/microvm/virtualization/microvm/guivm.nix
@@ -23,7 +23,7 @@
-          graphics.labwc.lock.enable = false;
+          graphics.labwc.lock.enable = true;
profiles.applications.enable = false;
windows-launcher.enable = false;
```
Once feature is enabled system will automatically lock after 5 minutes of idle time, resulting which below screen can be seen
Enter the password for `gui-vm` and hit "Enter". That will unlock the system.

labwc: Screen locking when system is idle

---

lib/mk-flash-script/default.nix

Add warning about aarch64-linux flash-script
This just adds a warning message to aarch64-linux flash script. Checked that x86 and aarch64 versions of the flash script build.

Add warning about aarch64-linux flash-script

---

.github/workflows/build.yml

- Re-enable `lenovo-x1-carbon-gen11-debug` in github action build workflow
- Add `-L` option to github action build workflow `nix build` command to print build logs
This change was tested in a forked repo at: https://github.com/henrirosten/ghaf/pull/22

GhA: Re-enable x1 in build workflow

---

flake.lock
flake.nix
lib.nix
modules/common/version/default.nix
modules/jetpack/nvidia-jetson-orin/partition-template.nix
modules/microvm/virtualization/microvm/appvm.nix
modules/microvm/virtualization/microvm/guivm.nix
modules/microvm/virtualization/microvm/netvm.nix
packages/flake-module.nix
targets/generic-x86_64/flake-module.nix
targets/imx8qm-mek/flake-module.nix
targets/lenovo-x1-installer/flake-module.nix
targets/lenovo-x1/everything.nix
targets/microchip-icicle-kit/flake-module.nix
targets/nvidia-jetson-orin/flake-module.nix
targets/vm/flake-module.nix

This makes it a lot easier to instantiate NixOS systems as you no longer have to pass in special things.
Depends on: https://github.com/tiiuae/ghaf/pull/509

Get rid of specialArgs by defining ghaf.version in nixos directly

---

docs/src/ref_impl/build_and_run.md

- oflag=direct uses direct I/O for data transfer, which is faster by avoiding the kernel buffer cache.
- status=progress shows the progress of the dd command.

dd: add status and oflag

---

modules/common/hardware/definition.nix
modules/disko/flake-module.nix
modules/disko/lenovo-x1-disko-basic.nix
modules/flake-module.nix
targets/lenovo-x1/everything.nix
targets/lenovo-x1/hardwareDefinition.nix

The NixOS module will already throw an error if an option is not set. Anymous NixOS modules will contain no file name in the error message.

lenovo-x1: don't create anymous NixOS module for disko configuration

---

modules/desktop/graphics/labwc.nix
modules/desktop/graphics/waybar.config.nix
overlays/custom-packages/default.nix
overlays/custom-packages/labwc/default.nix

This patch moves the configuration of labwc out of the overlay, allowing us to easily customise the system using ghaf's configuration.
This also makes the labwc package future-proof, as previously we were using configuration files in place from labwc's source `docs` folder. A recent change commented out these files, so labwc would break in nixpkgs 24.05.
Not much changed in terms of functionality, except removal of some right click menu items.
Screen lock functionality is tested.

labwc: refactor labwc configuration

---

modules/desktop/graphics/boot.nix
modules/desktop/graphics/default.nix

This allows enabling plymouth for booting graphical systems, showing a spinning circle and the Ghaf logo underneath.
1. Enable the option `ghaf.graphics.boot.enable = true;` on the host.
2. Reboot, you should see the boot spinner and Ghaf logo on boot. (only visible sometimes when boot is slow, maybe ~20% of time)

boot: add plymouth with Ghaf logo as an optional module

---

modules/common/common.nix
overlays/custom-packages/default.nix
overlays/custom-packages/htop/default.nix
overlays/custom-packages/networkmanagerapplet/default.nix

This removes not-working icons from the drawer, by making these entries "Hidden."
It also removes NixOS documentation from the Ghaf image, that results in a slightly smaller image and removes the NixOS documentation launcher entry.
Can only be tested in labwc. All icons in the launcher drawer should be functional and work.

labwc: remove not-working icons from drawer

---

modules/common/common.nix
modules/common/default.nix
modules/common/systemd/base.nix
modules/common/systemd/default.nix
modules/microvm/virtualization/microvm/appvm.nix
modules/microvm/virtualization/microvm/guivm.nix
modules/microvm/virtualization/microvm/microvm-host.nix
modules/microvm/virtualization/microvm/netvm.nix
targets/generic-x86_64/flake-module.nix
targets/lenovo-x1-installer/flake-module.nix
targets/nvidia-jetson-orin/flake-module.nix
targets/vm/flake-module.nix

Initial PR for minimal systemd for Ghaf (x1 only at the moment). Based on NixOS systemdMinimal, it aims to provide a baseline systemd configuration with options to extend or limit the functionality per VM and host to the necessary minimal.
The implementation provides 2 things:
1. Systemd package configuration
2. Removal of unwanted units (in some cases necessary to allow built)
Hereby, most exposed options follow the respective NixOS systemd config flags. Some options are removing units only, or group flags together. Both package config and unit removal was done in anticipation of future removals and configuration, and will be subject to change.
While the original idea was also to reduce image size; this is not the case at the moment with a shared nix store compared to individual VM …

Initial minimal systemd for Ghaf

---

.github/workflows/build.yml

- Rebase the PR changes on top of the target base head before running the build step. Intentionally do the rebase locally in the github action only, without committing the rebased changes. We also intentionally fail the build step if the automatic git rebase fails to encourage manual rebase.
- Adds verbose logging to the 'Rebase' step to explicitly state the commit hexshas on which the build step was executed (or rebase failed).
- Moves the apt installation as its own step.
In addition, this change set the[ connect-timeout](https://nixos.org/manual/nix/stable/command-ref/conf-file#conf-connect-timeout) to 5 seconds to make nix package manager gracefully degrade if the binary cache is not responding.
This change was tested in a forked repository at: …

GhA: build.yml: rebase before build

---

targets/lenovo-x1/everything.nix

Enable microvm-host.hostNetworkSupport
This should fix regular Lenovo X1 tests

lenovo-x1: Enable microvm-host.hostNetworkSupport

---

packages/flake-module.nix
packages/hart-software-services/default.nix

Build Hart Software Services (HSS) to be able to ~~run RISC-V images on QEMU~~ build own HSS binary from source and run it on Icicle-Kit board

Hart Software Services for Microchip Polarfire Icicle Kit (RISC-V)

---

modules/common/development/debug-tools.nix

Add perf and unixbench to debug-tools.nix. Need to exclude unixbench from RISCV because runtimeShell is not enabled for that target.
These tools are meant for performance monitoring, mainly for Q&A team. 
Perf was added especially for RISCV Icicle-kit target but it was tested also on Lenovo-X1. On Icicle-kit custom perf script will be used (to get execution time decreased):
`{ perf bench sched messaging; perf bench sched pipe -l 50000; perf bench syscall basic; perf bench mem memcpy; perf bench mem memset; perf bench mem find_bit -i 5 -j 1000; perf bench numa mem -p 1 -t 1 -P 1024 -C 0 -M 0 -s 5 -zZq --thp 1 --no-data_rand_walk; perf bench futex all; perf bench epoll wait; perf bench epoll ctl; perf bench internals synthesize -i 1000; perf bench internals kallsyms-parse -i 10; } | tee -a …

Add perf and unixbench to debug tools

---

flake.lock
flake.nix
nix/devshell.nix

nixci provides a cleaner interface to the devour-flake

Move to using nixci from nix-build-all

---

modules/desktop/graphics/launchers.nix

Move the icon path exists check to checkPhase of makeDesktopItem, to remove the IFD.
Run `nix flake check` to see there is no IFD failure anymore

Fix icon IFD: Move the icon path existstance check to checkPhase

---

targets/lenovo-x1-installer/flake-module.nix

Add SSH key to ghaf installer in debug mode. This enables ci-test-automation to run the installer.
The public SSH key which this PR adds corresponds to private key accessible only by test automation. If you want to test with some other key pair clone the repository and add public key to `targets/lenovo-x1-installer/flake-module.nix`
**Debug mode**
Build the installer in debug mode
`nix build .#lenovo-x1-carbon-gen11-debug-installer`
Boot Lenovo-X1 from the installer image and connect it to local network with Ethernet cable + USB adapter.
Check IP address on Lenovo-X1
`ifconfig` 
Test that you can ssh to installer running on Lenovo-X1 from your computer (where the ssh key pair was created)
`ssh nixos@ip_address`
**Release mode**
Build the installer in release mode
`nix build …

Add SSH key to ghaf installer

---

modules/common/hardware/default.nix
modules/common/hardware/usb-network-kernel-patch.nix

Fix MAC-address randomized on USB network cards because of kernel bug. This specifically affects network cards used in testing.

Add USB network card kernel patch

---

packages/wifi-signal-strength/default.nix

Multiple call from multiple instance of waybar causes race condition. flock and trap are used to eliminate.

waybar: lock the wifi-signal-strength script

---

modules/desktop/graphics/fonts.nix
modules/desktop/graphics/waybar.config.nix
targets/generic-x86_64/flake-module.nix

This fixes minor build issues for the generic-x86_64 target when the Labwc compositor is enabled. Also, it disables demo launchers since there are no AppVMs there. While generic-x86_64 target is not currently the main priority, it can still be useful for testing scenarios that don't work with GuiVM and GPU passthrough.
1. Enable Labwc in the generic-x86_64 target by adding `ghaf.profiles.graphics.compositor = "labwc";` and build it.
2. It fails to build on the current version of Ghaf but builds fine with this PR.

Fix generic-x86_64 build with labwc enabled

---

targets/generic-x86_64/flake-module.nix

Disabling demoApplications broke our automated test cases, which check the apps can actually start
I want to re-enable demoApps because I think we should also support the host-only usecase (without VMs), and the tests are already (lightly) checking that.
Tested on NUC, checked that application tests started to pass again.

Re-enable demoApplications for generic-x86_64

---

templates/targets/x86_64/generic/flake.nix

- fixes tiiuae/ghaf#555
```
$ nix flake new --template github:vilvo/ghaf/issue_555#target-x86_64-generic ~/test-ghaf-downstream-fix
cd test-ghaf-downstream-fix/
nix flake show
```

fix: x86_64 template

---

docs/src/SUMMARY.md
docs/src/technologies/device_tree_overlays_pt.md
docs/src/technologies/nvidia_uarti_net_vm.md
docs/src/technologies/passthrough.md
modules/jetpack/nvidia-jetson-orin/jetson-orin.nix
modules/jetpack/nvidia-jetson-orin/virtualization/default.nix
modules/jetpack/nvidia-jetson-orin/virtualization/passthrough/uarti-net-vm/default.nix
modules/jetpack/nvidia-jetson-orin/virtualization/passthrough/uarti-net-vm/patches/net_vm_dtb_with_uarti.patch
modules/jetpack/nvidia-jetson-orin/virtualization/passthrough/uarti-net-vm/uarti_pt_host_overlay.dts
targets/nvidia-jetson-orin/flake-module.nix

Having a USB debug port connected to the Net-VM is useful when the SSH connection is not working or correctly configured. This implementation enables access from the Nvidia Orin AGX debug micro USB port (ttyACM1)  to the Net-VM console.
**NOTE**: this implementation only works with Nvidia Jetson Orin AGX, due is the only 
Nvidia Jetson Orin with the UARTI port available.
The UARTI is mapped as *serial@31d0000* in the device tree information. This UARTI is connected to 
the Nvidia Orin micro USB debugging port (ttyACM1) with a default speed of 115000bps.
The UARTI passthrough is configured in Ghaf for Microvm. 
The UARTI passthrough configuration declaration is available in: 
[UARTI to Net-VM](https://github.com/jpruiz84/ghaf/blob/uarti/modules/hardware/nvidia-jetson-orin/virtualization/pas …

Orin: UARTI passthrough to Net-VM

---

modules/common/hardware/ax88179_178a.nix

Add another patch for ax88179_178a USB network card, to fix random MAC-address problems.

Add another patch for ax88179_178a USB network

---

modules/common/hardware/definition.nix
modules/common/hardware/lenovo-x1/definitions/default.nix
modules/common/hardware/lenovo-x1/definitions/x1-gen10.nix
modules/common/hardware/lenovo-x1/definitions/x1-gen11.nix
modules/microvm/default.nix
modules/microvm/virtualization/microvm/audiovm.nix
modules/microvm/virtualization/microvm/guivm.nix
targets/lenovo-x1/appvms/chromium.nix
targets/lenovo-x1/audiovmExtraModules.nix
targets/lenovo-x1/everything.nix
targets/lenovo-x1/guivmExtraModules.nix

Initial version of AudioVM with Pipewire backend and pulseaudio TCP remote communication layer for the guest VMs. Note that this is not really secure design (yet) basically all VMs can access the pulseaudio TCP service.
On Lenovo X1 integrated sound card is passed through to the new AudioVM.
Chromium VM plays back sound through audiovm after boot.
Tested mostly with 3.5mm headset (both playback and mic).
Also playback with integrated speakers works (did not test integrated mic).

Initial AudioVM implementation with pipewire and pulseaudio

---

.github/workflows/build.yml

Don't print full build logs on the github `build` workflow.

Adjust GitHub build verbosity

---

modules/common/systemd/base.nix
modules/common/systemd/boot.nix

- fix hardcoded NSS dependency
- fix hardcoded systemd-bosd.service dependency

Changes for systemd 255

---

modules/common/default.nix
modules/common/services/default.nix
modules/common/services/dendrite-pinecone.nix
packages/dendrite-pinecone/default.nix
targets/lenovo-x1/appvms/default.nix
targets/lenovo-x1/appvms/element.nix
targets/lenovo-x1/everything.nix
targets/lenovo-x1/netvmExtraModules.nix

The element chat application was intended to facilitate data transmission with the custom netvm and element-vm firewall setup. PR ensures allowing operation of Dendrite Server communication with the external network by enabling TCP port 49000 and routing UDP port 60606 multicast packets. The network security in netvm was strengthened by changing INPUT default behavior from ACCEPT to DROP. `smcroute` multicast routing app was used to forward UDP  bidirectional multicast packets between external/internal networks.
To be reviewed in conjunction with https://github.com/tiiuae/ghaf/pull/430.
1. Normally, dendrite-pinecone runs as a system service, and the `sudo systemctl status dendrite-pinecone.service` output should look like the picture below.
2. We should stop with `sudo systemctl stop …

Integration of Dendrite to Ghaf

---

modules/microvm/virtualization/microvm/appvm.nix
targets/lenovo-x1/appvms/chromium.nix
targets/lenovo-x1/openPdf.nix

When PDF names contain a space, word splitting occurs on multiple areas, resulting the action (openPdf) to fail.
Properly quote arguments and variables, so they are passed properly.
- Search for "pdf assoc example", open first link: `https://github.com/pdf-association/pdf20examples`
- Download the PDF file with a space. Should work.
- PDF files without spaces should work.
- As the `waypipe-run` command has been modified, double-check that all applications still run properly.

openPdf: prevent word splitting when filename contains a space

---

modules/desktop/graphics/labwc.nix
modules/hardware/lenovo-x1/definitions/default.nix
targets/lenovo-x1/everything.nix

Thinkpad multimedia function keys have a different input device than keyboard itself. It is connected to guivm with udev and brightness keybinds are set in labwc.
Use F5 and F6 keys to observe brightness change on the screen backlight in GUIVM.

guivm: Passthrough the multimedia keys

---

modules/common/development/debug-tools.nix

This PR just adds efibootmgr utility to debug tools. This is to enable automated removal of Linux Boot Manager entries. Once PR#585 gets merged ghaf-installer will create always a new Linux Boot Manager entry to UEFI Boot order list.
The plan is to run
```
for f in $(efibootmgr | grep Linux | awk 'NR > 0 {print $1}' | cut -c 5-8)
do
sudo efibootmgr -q -b ${f} -B
done
```
for Lenovo-X1 in automated setup every time after testing ghaf-installer/ghaf.
Command `efibootmgr` lists the current boot order.

Add efibootmgr to debug tools

---

overlays/custom-packages/labwc/labwc-colored-borders.patch

This is a quick fix, the colored borders patch needs a cleanup.
Tested on X1.

labwc: fix window title theme

---

docs/src/features/features.md
docs/src/ref_impl/build_and_run.md
flake.lock
hydrajobs/flake-module.nix
modules/flake-module.nix
modules/imx8/default.nix
modules/imx8/imx8mp-sdimage.nix
targets/flake-module.nix
targets/imx8mp-evk/flake-module.nix
templates/flake-module.nix
templates/targets/aarch64/nxp/imx8mp-evk/flake.nix

NXP i.MX8 MPlus EVK platform support.
- Added template platform
- Host only
- Cross build
- [x ] More detailed description in the commit message(s)
Basic testing on NXP iMX8 MPlus EVK platform.

NXP i.MX8 MPlus platform support

---

targets/lenovo-x1/appvms/zathura.nix

End users shouldn't need to understand the difference between multiple clipboards.
This only applies to X1 Carbon, not to Orin. Zathura is not yet properly integrated on Orin.
Simply adds configuration for Zathura to set the default clipboard.
- Open a PDF (download from internet).
- Select text, should copy to normal clipboard.
- Paste on another window/VM normally with Ctrl+V, this should now work as expected.

zathura VM: Use regular clipboard instead of primary

---

modules/microvm/default.nix
modules/microvm/virtualization/microvm/adminvm.nix
targets/lenovo-x1/everything.nix

* required to integrate givc admin and centralized logging
https://ssrc.atlassian.net/wiki/x/xoCCKw
```
[vilvo@carrie:~/ghaf]$ ssh ghaf@<host_debug_ethernet_ip_address>
Last login: Thu May 16 10:08:17 2024 from ...
[ghaf@ghaf-host:~]$ microvm -l
admin-vm: current(nixos-system-admin-vm-23.11pre-git)
appflowy-vm: current(nixos-system-appflowy-vm-23.11pre-git)
chromium-vm: current(nixos-system-chromium-vm-23.11pre-git)
element-vm: current(nixos-system-element-vm-23.11pre-git)
gala-vm: current(nixos-system-gala-vm-23.11pre-git)
gui-vm: current(nixos-system-gui-vm-23.11pre-git)
net-vm: current(nixos-system-net-vm-23.11pre-git)
zathura-vm: current(nixos-system-zathura-vm-23.11pre-git)
[ghaf@ghaf-host:~]$ ssh 192.168.101.10
The authenticity of host '192.168.101.10 (192.168.101.10)' can't be …
```

admin-vm: VM for ghaf administration

---

overlays/custom-packages/waypipe/default.nix
overlays/custom-packages/waypipe/waypipe-window-borders.patch

The latest release also has a "title-prefix" feature which is also very handy to i.e. prefix the VM name to an application. I haven't tested the patch yet, since I am currently missing
a machine for that.

waypipe: rebase patch on the latest release

---

modules/common/development/debug-tools.nix
modules/common/development/scripts/nvpmodel_check.nix
modules/common/development/scripts/perf_test_icicle_kit.nix
modules/common/development/scripts/rm_linux_bootmgr_entries.nix
modules/common/development/scripts/sysbench_fileio_test.nix
modules/common/development/scripts/sysbench_test.nix

Added few scripts which can make testing faster and easier:
- 2 sysbench scripts which are used in automated testing but currently copied into every VM at each test round
- perf test script for icicle kit target, no need to copy that either
- script for removing Linux Boot Manager entries from UEFI Boot order list
**Levono-X1**
ghaf-host:
`rm-linux-bootmgrs`
**Orin AGX/NX**
ghaf-host:
`nvpmodel-check 3` -> Power mode check ok
`nvpmodel-check 2` -> Unexpected power mode detected
**Icicle-kit**
`perf-test-icicle-kit`
**All targets except Icicle-kit**
ghaf-host:
`sysbench-fileio-test`
ghaf-host or any VM:
`sysbench-test`

Add helper scripts in debug mode

---

targets/lenovo-x1/guivmExtraModules.nix
targets/lenovo-x1/netvmExtraModules.nix

- Enable redistributable fw
- ensure correct driver
- enable GuC
This patch ensure that there is the FW available in the VM for the graphics driver to load into the GPU.
There are still things to fix that still needs to be investigated.
X86 targets for now.

Fix the graphics FW not loading in the GUIvm

---

modules/common/systemd/hardened-configs/common/microvm-virtiofsd@.nix

Fix for admin-vm ssh issue
[Bug](https://ssrc.atlassian.net/browse/SP-4673)
Allow namespace access, privilege system call, and other capabilities to the service.
Tested on Lenovo X1 Gen 11.

Allow 'priviledge' sys calls for microvm-virtiofsd

---

lib/launcher.nix
modules/common/default.nix
modules/common/programs/chromium.nix
modules/common/programs/default.nix
modules/common/programs/zathura.nix
modules/desktop/graphics/demo-apps.nix
modules/desktop/graphics/labwc.nix
targets/lenovo-x1/appvms/chromium.nix
targets/lenovo-x1/appvms/zathura.nix

This creates a new option `ghaf.programs.<name>`, which allows us to configure applications across targets and whether they run inside a VM or not.
This also fixes Chromium border glitch, and Element border colour (SP-4645 & SP-4644).
- Add program option for Zathura, fixes clipboard issue also on Orin.
- Add program option for Chromium
- Fixes border glitch when unmaximising application.
- Chromium on Orin should now behave similarly to X1 carbon.
- Fix Element border.
- Fix duplicate icons on Orin.
- Chromium can still open PDFs on X1 carbon.
- Chromium unmaximise glitch fixed on X1 carbon.
- Zathura on Orin can now copy to normal clipboard (not primary).
- Element border should be fully coloured.

common: Create options for applications, other fixes

---

modules/common/default.nix
modules/common/networking/default.nix
modules/common/networking/hosts.nix
modules/microvm/virtualization/microvm/adminvm.nix
modules/microvm/virtualization/microvm/appvm.nix
modules/microvm/virtualization/microvm/audiovm.nix
modules/microvm/virtualization/microvm/common/vm-networking.nix
modules/microvm/virtualization/microvm/guivm.nix
modules/microvm/virtualization/microvm/idsvm/idsvm.nix
modules/microvm/virtualization/microvm/netvm.nix
packages/mitmweb-ui/default.nix
packages/nm-launcher/default.nix
packages/openPdf/default.nix
packages/wifi-signal-strength/default.nix
targets/lenovo-x1/appvms/chromium.nix
targets/lenovo-x1/appvms/element.nix
targets/lenovo-x1/guivmExtraModules.nix
targets/lenovo-x1/netvmExtraModules.nix

* based on decisions to use static names over internal DNS https://github.com/tiiuae/ghaf/pull/427
* removes dnsmasq and dhcp from net-vm to other guests
* `/etc/hosts` with static hosts to IP mapping generated and made available to host and guests
* resolves https://github.com/tiiuae/ghaf/pull/600
Connect to `ghaf-host` over debug ethernet. Check the IP in your network.
```
❯ ssh ghaf@nn.nn.nn.nn
Last login: Tue Jun  4 10:09:53 2024 from yy.yy.yy.yy
[ghaf@ghaf-host:~]$ less /etc/hosts
[ghaf@ghaf-host:~]$ ssh gui-vm-debug
(ghaf@gui-vm-debug) Password:
[ghaf@gui-vm:~]$
logout
Connection to gui-vm-debug closed.
[ghaf@ghaf-host:~]$ ssh net-vm-debug
(ghaf@net-vm-debug) Password:
[ghaf@net-vm:~]$ ssh gui-vm-debug
(ghaf@gui-vm-debug) Password:
Last login: Tue Jun  4 10:11:35 2024 from …
```

networking: module for static names

---

modules/common/services/audio.nix
modules/common/services/default.nix
modules/hardware/common/passthru.nix
modules/hardware/definition.nix
modules/hardware/lenovo-x1/default.nix
modules/hardware/lenovo-x1/definitions/x1-gen10.nix
modules/hardware/lenovo-x1/definitions/x1-gen11.nix
modules/microvm/virtualization/microvm/audiovm.nix
modules/microvm/virtualization/microvm/microvm-host.nix
targets/lenovo-x1/everything.nix

Refactoring to separate hardware dependencies. Goal is to allow easy creation of targets other than x1, with clear(er) hardware interface. Ultimately, generating a hardware definition should be enough for a new target.
- remove audiovmExtraModules file
- move audio configuration into module
- move audio shutdown fix to microvm-host
- move vfio kernel params generation to hw passthrough
- move x1 specific kernel params to hardware definition
- move audiovm (intel specfic) kernel parameters to audio device definition
General idea here is to move hardware specific kernel configurations to the hardware definition. This allows to change hardware through a single configuration file while the rest of the system can be defined hardware independent.
- create option and move host kernel parameters …

Refactor hardware dependencies and audiovm

---

modules/disko/lenovo-x1-disko-basic.nix
packages/installer/ghaf-installer.sh
targets/lenovo-x1-installer/flake-module.nix

This avoids having images on the builders and cache take too much storage.
The goal of this change is to compress all build artefacts to a reasonable size, in a reasonable amount of time. This is so that:
- Disko image files takes less space in the binary cache and builders.
- Downloading disko images files would be much faster from the binary cache, reducing bandwidth and time required to build a system.
- Building the ISO image would be much faster.
These are results as tested on my Lenovo P1 Gen3 laptop. This table is similar to Fedora's [comparison of compression levels and algorithms](https://fedoraproject.org/wiki/Changes/Switch_RPMs_to_zstd_compression#Comparison_of_compression_algorithms_and_levels), so we can compare easily.
| Target | Compression | Level | Size | Comp. time | …

lenovo-x1: compress image using zstd

---

modules/microvm/virtualization/microvm/netvm.nix

This allows nixos-rebuild --fast switch remotely without major issues.
- All micro VMs restart except netvm.
- gui-vm seems to behave properly when rebooted, issue is only with net-vm.
- With proxyJump configured, `nixos-rebuild switch` remotely.
- Change configuration of the system (e.g. remove a demo application, or app border colour), and rebuild. The system should restart the gui-vm properly, and the change should be applied.

netvm: do not restart microvm when changed

---

modules/microvm/virtualization/microvm/guivm.nix
packages/vsockproxy/default.nix

Disables suspend inside gui-vm, as it causes qemu to segfault.
Related to: https://gitlab.com/qemu-project/qemu/-/issues/2321
Also brings in fix in vsockproxy, which didn't used to handle signals
gracefully, causing it to crash when the host is suspended.
- Configure logind not to suspend inside gui-vm.
- Update vsockproxy to [include fix](https://github.com/tiiuae/vsockproxy/commit/851e995b4c24a776f78d56310010e4e29456921c).
- Let vsockproxy systemd service restart always, so it is always available.
Fixes: SP-3466, and possibly SP-3464
- Boot the system, open any app VM window.
- Close the lid and open, as many times.
- Apps should still be running, interactive, networking available, other apps still launchable.
- Close lid, keep closed for more than 5 minutes, open lid. Apps should work …

guivm: fix crash on lid close

---

modules/desktop/graphics/labwc.config.nix
modules/microvm/virtualization/microvm/audiovm.nix
packages/audio-ctrl/default.nix
packages/nm-launcher/default.nix
packages/wifi-signal-strength/default.nix

Enables the media keys for volume up, down, and mute toggling.
Also now the wifi-signal-strength script is checked by shellcheck, all shellcheck issues are fixed, including bugs when netvm is rebooted and signal strength 0 not showing properly.
- Media keys now work for volume up, volume down, and mute.
- Volume step is 5%.
- Brightness step is now 5% instead of 10%.
- wifi-signal-strength script fixes
- When net-vm reboots, host key check used to fail (even with it set to no). This is now fixed, so status should continue to update after net-vm reboots.
- When signal strength was <30, it used to print "signal0" instead of icon. Now proper icon should be shown.
- Script uses `writeShellApplication` which means it is run through shellcheck.
- Shellcheck issues are fixed.
- Test volume keys …

labwc: enable audio controls, fix wifi status script

---

overlays/custom-packages/waypipe/default.nix
overlays/custom-packages/waypipe/waypipe-window-borders.patch

The old version did break if a screen used output scaling (i.e. on 200% scaling on 4k screens) by making the border only a quarter of the needed size.
This was fixed by requesting the compositor output scaling.
I found this bug when I tested this patch prior to upstreaming the patch to https://gitlab.freedesktop.org/mstoeckl/waypipe/-/merge_requests/21
I also updated the manpage

waypipe: fix border drawing when compositor has output scaling != 1

---

packages/installer/default.nix
packages/installer/ghaf-installer.sh
targets/lenovo-x1-installer/flake-module.nix

The image path is now set as an environment variable, so the script derivation could be reused. Also the installer derivation is created using `writeShellApplication` which will test against shellcheck.
Also added message on running the installer. The installer now only shows devices and the vendor/name, and doesn't include the partitions.
The installer also has proper confirmation prompts, and also warn the user if they are trying to install Ghaf on a removable device.
- Use `writeShellApplication` for installer, specify runtimeInputs. Now script is always checked against shellcheck.
- Installer improvements
- Lists only actual devices, while partitions and loop devices are not shown. This uses `hwinfo` package.
- Includes vendor and disk name of each drive (e.g. Sandisk Cruzer Force).
- …

x1-installer: add checks in installer script, other improvements

---

overlays/README.md
overlays/custom-packages/default.nix
overlays/custom-packages/gtklock/auth-guard-against-race-condition-with-messages.patch
overlays/custom-packages/gtklock/default.nix
overlays/custom-packages/gtklock/update.patch

This patch will fix SP-4849 issue.
Testing instructions in SP-4849

gtklock: Fix screen goes black after wrong passwords

---

modules/common/services/default.nix
modules/common/services/yubikey.nix
modules/hardware/common/qemu.nix
modules/hardware/lenovo-x1/definitions/x1-gen10.nix
modules/hardware/lenovo-x1/definitions/x1-gen11.nix
modules/microvm/virtualization/microvm/modules.nix

This patch enables Yubikey authentication for ghaf gui-vm. We are doing Yubikey passthrough from ghaf-host to gui-vm. Currently Yubikey Authentication supported with screen locker (gtklock) and sudo command in pam sufficient mode means either password or tap on device is enough for authentication.
**Prerequisite:**
1) Yubikey hardware, more details [here](https://www.yubico.com/products/yubikey-5-overview/)
2) Generate Yubikey public key using following command
``
pamu2fcfg  -u ghaf -o pam://gui-vm
``
3) Make sure you have Yubikey public key added [here](https://github.com/tiiuae/ghaf/pull/689/files#diff-d7de64aaf9be5d66f157884b4f27b3a245eb0c8dd830d8a845e6ed90dadeac70R82) ([example](https://github.com/tiiuae/ghaf/pull/689/files#diff-b295efaff3c4d69acf6d0f2eea743b20a9c4234a64bb4b34bbaeb60f6 …

Enable Yubikey Authentication

---

modules/disko/disko-basic-partition-v1.nix
modules/hardware/common/qemu.nix
modules/hardware/definition.nix
modules/hardware/definitions/dell-latitude/dell-latitude-7230.nix
modules/hardware/definitions/dell-latitude/dell-latitude-7330.nix
modules/hardware/laptop.nix
modules/hardware/lenovo-x1/definitions/x1-gen10.nix
modules/hardware/lenovo-x1/definitions/x1-gen11.nix
modules/reference/appvms/business.nix
modules/reference/appvms/chromium.nix
modules/reference/appvms/element.nix
overlays/custom-packages/default.nix
packages/flake-module.nix
packages/hardware-scan/default.nix
packages/hardware-scan/hardware-scan.sh
targets/flake-module.nix
targets/laptop-hw-scan/flake-module.nix
targets/laptop/flake-module.nix
targets/lenovo-x1-installer/flake-module.nix
templates/boilerplate/modules/hardware/default.nix

Adding a (temporary) hardware detection script to generate hardware definition files for different laptop hardware.
The script can generate a Ghaf laptop target compatible hardware definition file (details below).
Main changes:
- Add `hardware-scan` shell script to generate a hardware definition file
- Add a laptop hardware scan target, minimal image without having to generate an image to flash
- Change the udev rule generation for input devices. This is necessary to allow more input devices and rule auto-generation 
- Add a hardware definition for the Dell Latitude 7230 laptop
```
nix build .#packages.x86_64-linux.hardware-scan
./result/bin/hardware-scan
```
or run directly with
`nix run github:tiiuae/ghaf/<commit>#hardware-scan`
1. Add your ssh key
2. Build target 
`nix build …

Hardware detection scanner

---

modules/common/default.nix
modules/common/logging/client.nix
modules/common/logging/default.nix
modules/common/logging/hw-mac-retrieve.nix
modules/common/logging/logs-aggregator.nix
modules/host/default.nix
modules/microvm/virtualization/microvm/adminvm.nix
modules/microvm/virtualization/microvm/appvm.nix
modules/microvm/virtualization/microvm/guivm.nix
modules/microvm/virtualization/microvm/netvm.nix
modules/profiles/laptop-x86.nix

This PR can be tested with multiple `Lenovo X1` devices and each system will upload system logs with unique `mac address`  to remote cloud server.
**Prerequisite:** 
Its recommended to  connect with `wifi` to get unique Mac Address and to upload logs to remote server.
By default system will start collecting logs once its booted.
WAL(Write Ahead Log) will be stored in `/var/lib/private/alloy/data-alloy/loki.write.remote/wal` path which can be accessed through `admin-vm` as well `ghaf-host` (WAL is not in human readable format)
**To View logs remotely on grafana-server**
Open browser and type following [address](https://ghaflogs.vedenemo.dev/explore), it will prompt with `credentials`.
Please request for `Credentials`.  Once you managed to login, choose appropriate labels as in example …

[X1]: logging: To centralize logs using grafana

---

modules/desktop/graphics/window-manager.nix
packages/ghaf-open/default.nix

This allows the user/tester to view and launch applications from the terminal, locally or remotely. It will also show the output of the launched application.
This works with applications inside or outside app VMs.
- Add `ghaf-open` command
- Command lists available applications (launchers) when no or invalid argument is given
- Arguments can be passed to the application
- Run the command with no argument, should list applications.
- Run the command with a valid application, should launch.
- Applications should all be launchable just like clicking on it.
- Any application that has an output, will be displayed in standard output.
- Arguments are passed to the application (typically works well only for local applications).
- Command should work remotely over ssh, GUIs should appear properly …

graphics: add ghaf-open command to launch applications

---

modules/common/logging/hw-mac-retrieve.nix

With this patch will be calling hwinfo utility to retrieve Permanent HW Address / MAC Address for wlp0s5f0 network interface. As we cannot rely on the sys interface for mac retrieval possibly due to MAC randomization.
In `admin-vm` run following command
```
[ghaf@admin-vm:~]$ sudo cat /var/lib/private/alloy/MACAddress
```
Its should match exactly **Permanent HW Address** of `net-vm`
```
[ghaf@net-vm:~]$ hwinfo --network --only /class/net/wlp0s5f0 | grep "Permanent HW Address"
```

logging: Update the mac address retrieval

---

modules/common/systemd/hardened-configs/common/systemd-remount-fs.nix
modules/disko/disko-ab-partitions.nix
modules/disko/disko-zfs-postboot.nix
modules/disko/flake-module.nix
modules/hardware/x86_64-generic/x86_64-linux.nix
targets/laptop/flake-module.nix

New disk configuration provides grounds for upcoming features, such as AB software updates and Storage VM and many more.
The Lenovo X1 config has two LVM pools, first one is fixed-size 250G "system" partition (which is going to be encrypted) and the rest of the disk is dedicated to the StorageVM.
Current upstream partition scheme is as follows:
```
[ghaf@ghaf-host:~]$ lsblk
NAME          MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
sda             8:0    0 465.8G  0 disk 
├─sda1          8:1    0   236M  0 part 
└─sda2          8:2    0   8.6G  0 part 
nvme0n1       259:0    0 953.9G  0 disk 
├─nvme0n1p1   259:1    0     1M  0 part 
├─nvme0n1p2   259:2    0   500M  0 part /boot
└─nvme0n1p3   259:3    0 953.4G  0 part 
└─pool-root 254:0    0 953.4G  0 lvm  /nix/store
/
```
To test new …

Introduce new disk partitioning scheme

---

modules/common/logging/logs-aggregator.nix

This patch will start logging journal logs collected from admin-vm to grafana server in the cloud.
In Grafana server now we can view logs from `admin-vm` as well which is not there previously.

logging: Collect journal logs from admin-vm

---

modules/disko/disko-ab-partitions.nix
modules/hardware/x86_64-generic/x86_64-linux.nix

These changes clean up other configurations that do not use ZFS
This PR fixes the build error for x86-generic target.
All x86-based configuration should build without issues, no matter if they use ZFS or not. The kernel version is `Linux ghaf-host 6.8.12`

Move ZFS-related config pieces to one place

---

modules/common/services/yubikey.nix
modules/desktop/graphics/labwc.config.nix

* Add udev rule for Yubikey hardware such that once Yubikey is plugged out of system, screen should lock automatically.
* Starting swayidle lock in labwc autostart.
Prerequisite 
Yubikey hardware, more details [here](https://www.yubico.com/products/yubikey-5-overview/)
**Steps:**
1) Plugin the Yubikey Hardware
2) Plugout the Yubikey Hardware
3) After plugout screen locker will appear automatically.

Lock the screen when Yubikey hardware is plugged out

---

flake.lock
flake.nix
modules/common/profiles/default.nix
modules/common/profiles/host-hardening.nix
modules/common/profiles/kernel-hardening.nix
modules/profiles/laptop-x86.nix
targets/laptop/flake-module.nix
targets/laptop/laptop-configuration-builder.nix

-  Created host-hardening profile which holds hardening configuration needed for the host. 
Also added secure boot configuration under host. By default host-hardening profile is disabled.
-  Updated lanzaboote package version to v0.4.1.
-  Addresses SP-4919
1) To test secure boot working change  [here](https://github.com/tiiuae/ghaf/pull/708/files#diff-0a25818675b9140f2f3d2007e018a9194d588053fe36654b7e6a484f69d14080R35) `host-hardening.enable = true;`
2) You may need to flash image as some of lanzaboote file may not install with `nixos-rebuild ... switch`
3) Enable secure boot from BIOS.
4) Enroll keys `sudo sbctl enroll-keys --microsoft` and reboot
5) Run below command to verify functionality  
```
[ghaf@ghaf-host:~]$ sbctl status | grep Secure
Secure Boot:    ✓ Enabled
```
6. Also can …

[Lenovo X1]: Created host-hardening profile & updated lanzaboote

---

flake.nix

Add https://dev-cache.vedenemo.dev nix binary cache to Ghaf flake.
https://dev-cache.vedenemo.dev is the ['dev' deployment](https://github.com/henrirosten/ghaf-infra/blob/d0ec199a3c9dc08dfd0e9e56dc3a3843e58ac582/terraform/main.tf#L117) of https://github.com/tiiuae/ghaf-infra/tree/main/terraform, with its jenkins instance running in https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/. The cache content is pushed e.g. from [pre-merge pipeline](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/ghaf-pre-merge-pipeline/) and the [main pipeline](https://ghaf-jenkins-controller-dev.northeurope.cloudapp.azure.com/job/ghaf-main-pipeline/) as outlined in [Confluence](https://ssrc.atlassian.net/wiki/spaces/SP/pages/1127023251/Ghaf-infra+Binary+Cache+Usage#Jenkins- …

Add ghaf-infra dev cache to Ghaf flake

---

.github/workflows/build.yml

Add generic-x86_64-debug target to github action build pipeline to notify PR authors of possible build breaks.
Tested the action builds on github-hosted runners in a forked repo at: https://github.com/henrirosten/ghaf/actions/runs/10368261655/job/28701471161.

build.yml: Add generic-x86_64-debug target

---

docs/src/ref_impl/build_and_run.md
nix/devshell.nix
packages/flash/default.nix
packages/flash/flash.sh
packages/installer/ghaf-installer.sh

The 'flash.sh' script makes image flashing easy and hassle-free, both for compressed and uncompressed images.
These changes should fix the recent issue with ZFS, when the device does not boot after the storage media was reflashed.
Build an image, flash it to the media using `flash.sh` script and boot the device.

Add universal flashing script

---

modules/jetpack/nvidia-jetson-orin/mk-esp-contents.py
nix/treefmt.nix
packages/element-gps/main.py
pyproject.toml

One tool less to download.
Ruff's formatting tries to stay close to 100% compatible with black while being faster.
Having one tool for everything also should in theory cause less compatibility issues.

treefmt: replace black with ruff

---

modules/common/services/desktop.nix
modules/profiles/mvp-user-trial.nix

The windows VM is not PoR for this configuration so remove it in order that it does not cause confusion.
The functionality is still available and can be enabled in different profiles as needed.
The windowns launcher should not be visable in the app launcher.

Disable the windows-vm launcher for MVP trial

---

nix/checks.nix

Temp disable this until there is a process to ensure that the hardening
checks are applicable to the current kernels.
-------
Disable the hardening checks from the `nix flake check` so that `nix-fast-build`` will know state for iterative builds`
Run `nix-fast-build` on consecutive times and see that there is nothing to be built after the first iteration.

Disable hardening kernel checks as unmaintained

---

modules/disko/disko-ab-partitions.nix

Trying to reduce the ARC didn't help to reduce the overall memory usage of the VM while building the disk images.
I see some increase of zio_buf_comb_<NUM> slabs which are also used for ARC, but maybe also in other places of zfs.
Hence I am increasing zfs to what is commonly known as the recommended memory size (also I personally used zfs with 4GB just fine on my NAS).
It could be that I am missing some other leak but I couldn't spot anything suspciously large except for zfs related allocations in /proc/slabinfo

increase memsize for building disko images

---

modules/common/services/desktop.nix
modules/microvm/virtualization/microvm/audiovm.nix
modules/reference/profiles/laptop-x86.nix

The call of the vm by name fails because has "debug" suffix. The call has been modified to use the correct option, following the Lenovo X1 targets. 
However it doesn't solve the functional issue and doesn't work on release targets because of connections are restricted. GIVC will fix it in the future.
Build the targets:
#packages.x86_64-linux.lenovo-x1-carbon-gen11-release
#packages.x86_64-linux.lenovo-x1-carbon-gen11-release-installer
You can also check with "#packages.x86_64-linux.lenovo-x1-carbon-gen11-debug" target to be sure does it work.
Run the image and run one of the applications or scripts in the launcher; for example "shutdown".
Observe that the script or application works.

lenovo-x1: temporary fix build errors of release and release installer targets to build only

---

.github/workflows/build.yml
hydrajobs/flake-module.nix
packages/flake-module.nix
targets/microchip-icicle-kit/flake-module.nix

This is to be consistent with the naming conventions as this package is a xcompiled package we should follow the same convention and list it as a package that is built on x86 and not claim that it is a package that is built on riscv directly

Change the riscv target to have -from-x86_64

---

REUSE.toml
packages/hart-software-services/0001-Workaround-for-a-compilation-issue.patch
packages/hart-software-services/default.nix

Workaround for hss compilation issue
- Patched hss package to removed `-fcompare-debug` flag from make rules
- Downgrading compiler didn't work, Compiler build fails for  gcc11 and gcc12
GCC Bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=104180

Workaround for hss compilation issue

---

modules/microvm/virtualization/microvm/common/vm-networking.nix
modules/microvm/virtualization/microvm/idsvm/idsvm.nix
modules/microvm/virtualization/microvm/netvm.nix

IDS VM is not working in current configuration.
Changes:
- change idsvm `microvm.hypervisor` from 'cloud-hypervisor' to 'qemu'
- fix gateway settings
lenovo x1
- enable idsvm in `modules/profiles/laptop-x86.nix`:
```
idsvm = {
enable = true;
mitmproxy.enable = true;
};
```
- run `mitmweb-ui` in guivm terminal
Check config with nix repl
```
:lf .
vms = nixosConfigurations.lenovo-x1-carbon-gen11-debug.config.microvm.vms
:p builtins.map (vm: {"${vm}-gateway" = vms."${vm}".config.config.systemd.network.networks."10-ethint0".gateway;}) (builtins.attrNames vms)
```
- Output with idsvm disabled 
```
[
{ admin-vm-gateway = [ "192.168.100.1" ]; }
{ appflowy-vm-gateway = [ "192.168.100.1" ]; }
{ audio-vm-gateway = [ "192.168.100.1" ]; }
{ business-vm-gateway = [ "192.168.100.1" ]; }
{ …
```

Fix ids-vm

---

flake.lock
flake.nix
modules/flake-module.nix
modules/microvm/flake-module.nix
modules/microvm/virtualization/microvm/appvm.nix
modules/microvm/virtualization/microvm/common/storagevm.nix
modules/microvm/virtualization/microvm/guivm.nix
modules/microvm/virtualization/microvm/netvm.nix
modules/reference/appvms/business.nix
modules/reference/appvms/chromium.nix
targets/laptop/flake-module.nix

This is the initial implementation of the Storage solution. It uses `impermanence` framework along with virtiofs shares to make needed files/directories persistent.
Currently it allows to store WiFi configuration, user data from GUI-vm user home directory and common-purpose browser configuration and user sessions/data.
Each VM has an access to it's only data and does not know anything about other stored entities. The host system has an access to all the data stored.
1. Boot the system. Connect to Wi-Fi network through GUI-VM.
2. Open Chromium browser, go to any website and add it's address as a bookmark. Close browser window.
3. Open Business-VM browser (MS365), log in to the Outlook. Close the browser window.
4. Create any file in user's home directory in GUI-VM: `touch ~/testfile`
5. …

Storage (VM) phase 0.1

---

modules/hardware/common/default.nix
modules/hardware/common/qemu.nix
modules/hardware/common/usb/vhotplug.nix
modules/microvm/virtualization/microvm/audiovm.nix
modules/microvm/virtualization/microvm/netvm.nix
modules/reference/profiles/laptop-x86.nix
packages/qemuqmp/default.nix
packages/vhotplug/default.nix

This adds a service that runs on the host and listens for device add and remove events using libudev. When a new USB device is attached, it is automatically assigned to the designated virtual machine using the official qemu.qmp library."
Input Devices:
- Connect a USB keyboard or mouse to the Lenovo X1 and verify that it is working in the GUI VM.
Audio Devices:
- Connect a USB headset to the Lenovo X1 and ssh into the audio-vm.
- Run `aplay -l` and find the headset in the list. It should be listed as either card 0 or card 1.
- To test the sound, execute `speaker-test -D hw:1,0 -c 2 -t sine`. If the headset appears as card 0, change hw:1,0 to hw:0,0.
If a bug is found or if something is not working as expected, please collect the vhotplug service logs from journalctl on the host.

Add support for USB hot plugging

---

REUSE.toml
modules/desktop/profiles/graphics.nix
modules/hardware/lenovo-x1/definitions/x1-gen11.nix
modules/microvm/virtualization/microvm/0001-x86-gpu-Don-t-reserve-stolen-memory-for-GPU-passthro.patch
modules/microvm/virtualization/microvm/guivm.nix

This patch will enable hardware accelerated display for renderering along with media hardware codecs.
Also we are patching Intel i915 driver in gui-vm to avoid reserving Intel graphics memory during boot
time which in turn fixes DMA Fault errors on the ghaf-host.
**Its would be nice if we can get results across different GEN of Lenovo X1 Carbon devices.** 
1) Check hardware acceleration in  `gui-vm`  using following command --> **Accelerated** should be `yes`
```
[ghaf@gui-vm:~]$ DISPLAY=:0.0 glxinfo -B
name of display: :0.0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
Vendor: Intel (0x8086)
Device: Mesa Intel(R) Graphics (RPL-U) (0xa7a1)
Version: 24.1.4
Accelerated: yes
..........................
```
2) Run `glxgears` in `gui-vm` and …

[Lenovo X1] gui-vm: Enable GPU acceleration

---

modules/microvm/virtualization/microvm/guivm.nix
modules/reference/profiles/default.nix
modules/reference/profiles/mvp-user-trial-extras.nix
modules/reference/profiles/mvp-user-trial.nix
targets/laptop/flake-module.nix
targets/laptop/laptop-configuration-builder.nix

This patch enables features that are needed for testing and validation,
which are not currently enabled by defualt in the standard MVP image.
The corresponding image is intended only for the bi-weekly regression
tests at present.
-------
new target created for testing the features that are not enabled by default. It is based on the default MVP-user-trial image, with a few additional features. It only applies to the lenovo X1 gen11 at the moment.
`nix build .#lenovo-x1-extras-debug`

Create testing profile for non-default features

---

targets/vm/flake-module.nix

The virtual machine target  `packages.x86_64-linux.vm-debug` wouldn't boot after we have integrated hardware rendering. Changed this setting to software renderer "pixman" for now so that we get a clean boot from running this target.
- [X ] Summary of the proposed changes in the PR description
- [ X] More detailed description in the commit message(s)
- [X ] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR
- [X ] [Contribution guidelines](https://github.com/tiiuae/ghaf/blob/main/CONTRIBUTING.md) followed
- [ X] Test procedure described (or includes tests). Select one or more:
- [X ] Tested on Lenovo X1 `x86_64`
Run Ghaf in vm according to instructions at https://tiiuae.github.io/ghaf/ref_impl/build_and_run.html#running-ghaf-image-for-x86-vm-ghaf …

Chnage vm-target renderer to software renderer pixman

---

modules/desktop/graphics/labwc.config.nix
modules/desktop/profiles/graphics.nix
modules/microvm/virtualization/microvm/guivm.nix

* Change kernel version to linuxPackages_latest which is 6.10.2
* Addresses SP-4919 - Temporary folder in gui-vm / host home directory
**Note:** Test specifically more on brightness test cases.
**Reason:** As default behaviour of `intel_backlight` driver from `max_brightness` to `min_brightness` is changed from kernel 6.10.1 onwards.  More details in this [patch](https://github.com/torvalds/linux/commit/92714006eb4d10ddfaa0eca41c81e6b483e02f93) 
1) If we reduce brightness and then logout and later try to login then brightness will be back to maximum because now we are setting brightness to max for every `labwc` session launch. 
Can be resolved later, once we have store for those brightness values. 
2) Fontconfig errors expected when login after logout.

gui-vm: Change kernel to linux latest and fix path issue

---

modules/common/services/desktop.nix
modules/desktop/graphics/ghaf-launcher.nix
modules/desktop/graphics/labwc.config.nix
modules/desktop/graphics/login-manager.nix
modules/desktop/graphics/waybar.config.nix
modules/desktop/profiles/graphics.nix

This implements the new theme as per the new designs.
Also the cursor on the desktop should be consistent with apps.
Regarding opacity: setting alpha channel to 1 for background colour somehow breaks border-radius for GTK applications. Setting it to 0.99 resolves this issue.
- All targets with labwc desktop
- Boot, desktop bar should be darker, same as launcher, lock screen, and login screen.
- Cursor shouldn't change theme when moving across different apps, or desktop and waybar
- Changes shouldn't impact functionality.

desktop: new color scheme, fix cursors

---

flake.nix
packages/installer/default.nix
packages/installer/ghaf-installer.sh
tests/flake-module.nix
tests/installer/default.nix

Introduce [nixos testing framework](https://nixos.org/manual/nixos/stable/index.html#sec-nixos-tests), by adding test for the installer. 
For now this test only for the installation of `lenovo-x1-carbon-gen11-debug` but could be extended to other targets. To execute this test run `nix build .#checks.x86_64-linux.installer.driver` and then `./result/bin/nixos-test-driver`. Use this way to utilize kvm, this way it takes up to 10 times less times to run. Other way is to just run `nix build .#checks.x86_64-linux.installer` which will build and run test at build time. To use kvm in this case you'll need to configure nix https://nixos.org/manual/nixos/stable/index.html#sec-running-nixos-tests-requirements, but I couldn't get it working.
Remember that it can eat a lot of memory because system …

Add test for the installer

---

modules/common/services/audio.nix
modules/common/services/bluetooth.nix
modules/common/services/default.nix
modules/common/services/desktop.nix
modules/common/systemd/hardened-configs/common/bluetooth.nix
modules/common/users/accounts.nix
modules/hardware/common/qemu.nix
modules/microvm/virtualization/microvm/audiovm.nix
modules/microvm/virtualization/microvm/guivm.nix
modules/microvm/virtualization/microvm/modules.nix
modules/reference/appvms/business.nix
modules/reference/appvms/chromium.nix
modules/reference/appvms/comms.nix
modules/reference/hardware/lenovo-x1/definitions/x1-gen10.nix
modules/reference/hardware/lenovo-x1/definitions/x1-gen11.nix
overlays/custom-packages/default.nix
overlays/custom-packages/pulseaudio/default.nix
overlays/custom-packages/pulseaudio/pulseaudio-remove-dont-move.patch
packages/bt-launcher/default.nix
packages/icon-pack/default.nix

Adds initial bluetooth support to audiovm, for the use of bluetooth headsets.
Global changes:
- set `mutableUsers` to false
- enable hardened systemd configurations in audiovm
Bluetooth module:
- add bluetooth service config, service system user, dbus config, hardened config, system user, etc.
- add (temporary) bluetooth manager (blueman), connecting to audiovm dbus via ssh 
- add persistent storage for bluetooth device configs
Functionality added:
- search, add/connect, disconnect, and use bluetooth headsets
- use bluetooth headset (and mic) in chromium
Known issues:
- to use mic in chromium, headset profile needs to be manually switched to an HSP/HFP profile (lower quality)
- (irregular) once in a while a new connection will fail, then after a while pop-up an authorization request 
- …

Add bluetooth support

---

modules/common/development/debug-tools.nix

These tools are necessary in running automated GUI tests:
https://github.com/tiiuae/ci-test-automation/pull/140
- grim can be used in taking screenshots
- with ydotool mouse and keyboard can be operated from command line
Lenovo X1
Orin AGX
Orin NX
NUC
To check the tools are available run in gui-vm for Lenovo-X1 and in ghaf-host for other targets:
ydotool
grim
Usage of the tools can be demonstrated by running ci-test-atutomation test case SP-T97 on Lenovo-X1 with https://github.com/tiiuae/ci-test-automation/pull/140
robot -v DEVICE:Lenovo-X1 -v BUILD_ID:X1 -v LOGIN:ghaf -v PASSWORD:ghaf -i SP-T97 ./

Add ydotool and grim to debug tools

---

modules/desktop/graphics/labwc.config.nix
modules/desktop/graphics/labwc.nix
modules/disko/disko-ab-partitions.nix
modules/microvm/virtualization/microvm/appvm.nix
modules/microvm/virtualization/microvm/guivm.nix
modules/reference/appvms/business.nix
modules/reference/appvms/chromium.nix
modules/reference/appvms/comms.nix
modules/reference/appvms/zathura.nix
packages/flake-module.nix
packages/ghaf-screenshot/default.nix

This is for storing some of the user common directories that are under the users home directory.
This makes some of the directories persist across the reboots.
In addition this patch adds the ability to select the capture area that
is used for the screenshots. When the screenshot is selected there is
Satty functionality that allows for some basic post capture editing in
the form of an overlay to add annotations such as, arrows, boxes, and
text.
The user can the save the file, or copy it to the clipboard. Once in the
clipboard it can be pasted into any of the other vms where there is an
app that will accept those images. This is the case for e.g. slack and
outlook.
lenovo-x1 MVP target
-   this adds some of the appvm user directories to the permanent storage.
```
ssh chromium-vm or …
```

Enable permanent storage for user common files

---

modules/reference/appvms/business.nix
modules/reference/appvms/chromium.nix

Double RAM amount  for ChromiumVM  -- 3072Mb was too tight and causing OOM watchdog to kill browser.
Fix for SP-5195 issue.

Double RAM settings for ChromiumVM

---

modules/reference/hardware/jetpack-microvm/agx-netvm-wlan-pci-passthrough.nix

Changes in NetVm for Lenovo left the state of NetVm in NVIDIA AGX behind where there was no NetworkManager tool to create a connection. The passthrough for Wifi device was active but there were no means of creating a wireless connection. NX had no problems as the netvm utilizes the ethernet device. Here this PR adds NetworkManager and nmcli to the netvm on NVIDIA AGX devices to allow networkmanager to connect to wireless network. 
1. Run `nmcli` to check the connections listing wlp0s5f0 (wifi device) disconnected.
2. Run `nmcli` con to ensure there is no wifi connection but only loopback.
```
NAME  UUID                                  TYPE      DEVICE 
lo    9fe4bd21-f68d-4df6-8537-ab2edba3d9ed  loopback  lo  
```
3. Run `nmcli d wifi list` to get a list of Wireless Access Points 
``` …
```

AGX nmcli for netvm

---

modules/desktop/graphics/waybar.config.nix

hmmmm. how it ever worked???
-------
Fixes the nm-launcher path in the waybar so that it can be found.
x1-carbon MVP user image
Bug fix that just appeared from nowhere.

fix the nm-launcher not found error

---

LICENSES/BSD-2-Clause.txt
REUSE.toml
modules/reference/hardware/jetpack/nvidia-jetson-orin/optee.nix
targets/nvidia-jetson-orin/0001-ta-pkcs11-Build-time-option-for-controlling-pin-lock.patch
targets/nvidia-jetson-orin/optee.nix

Introducing a build time option for OP-TEE's PKCS11 TA: lockPinAfterFailedLoginAttempts. If lockPinAfterFailedLoginAttempts is set to true then PKCS11 TA is build with CFG_PKCS11_TA_LOCK_PIN_AFTER_FAILED_LOGIN_ATTEMPTS=y and respectively CFG_PKCS11_TA_LOCK_PIN_AFTER_FAILED_LOGIN_ATTEMPTS=n if option is set to false.
Default value is false.
**Note**: This is a custom feature. It is not part of the OP-TEE's upstream, but I have opened [a pull request](https://github.com/OP-TEE/optee_os/pull/7040) towards OP-TEE repository. I will updated this pull request if my OP-TEE's pull request receives any comments. 
Note: Need to remove /data/tee-directory
A complete testing requires two sequence _limited_ and _unlimited_ logins. 
Common for both cases are initilization:
`alias p11="pkcs11-tool-optee …

OP-TEE: Add option for PKCS11 TA (CFG_PKCS11_TA_LOCK_PIN_AFTER_FAILED_LOGIN_ATTEMPTS)

---

modules/common/services/audio.nix
modules/microvm/virtualization/microvm/appvm.nix
modules/microvm/virtualization/microvm/common/ghaf-audio.nix
modules/reference/appvms/business.nix
modules/reference/appvms/chromium.nix
modules/reference/appvms/comms.nix

Fix issue with getting no audio when changing sound IO port
Add common Ghaf audio setting and configuration for App-vns
Also fixes issue for changing audio IO port
Fixes a bug when playing/recording audio and user unplugs 3.5mm (or usb etc) headset
Audio should re-route automatically to integrated speakers/mic.
There is 1 second delay in the switchin of audio port
Verify recording with shell tool parecord / paplay since some mic recording web pages seemed to cause buggy noise

Add common Ghaf audio configuration for app-vms

---

modules/common/services/default.nix
modules/common/services/desktop.nix
modules/common/services/disks.nix
modules/desktop/graphics/ghaf-launcher.nix
modules/hardware/common/usb/vhotplug.nix
modules/microvm/virtualization/microvm/guivm.nix
packages/icon-pack/default.nix

- Enable passthrough of USB drives to the GUIVM.
- Add a new service to enable auto-mounting.
- Add a simple file manager to the GUIVM.
Note: A reboot or a restart of the vhotplug service is required to enable USB drive passthrough if the system is updated with nixos-rebuild.
- Reboot the device or restart the vhotplug service on the host if the system was updated with nixos-rebuild.
- Connect a USB drive to the Lenovo X1.
- Make sure an auto-mount notification appears.
- Click on the disk icon at the bottom panel and browse the files.
- The file manager should also be accessible from the launcher panel.
- Also, it would be nice to test a use case when the system is booted from a USB drive. In this case it shouldn't be attached to the GUIVM.

Add support for USB removable media

---

modules/desktop/graphics/default.nix
modules/desktop/graphics/ewwbar.nix
modules/desktop/graphics/ghaf-launcher.nix
modules/microvm/virtualization/microvm/guivm.nix

Proposed waybar taskbar replacement using [Elkowars Wacky Widgets](https://github.com/elkowar/eww), with modified base config made by https://github.com/rxyhn.
Main taskbar configuration is defined in `modules/desktop/graphics/ewwbar.nix` and stored in `/etc/eww/eww.yuck`.
Styling defined in `modules/desktop/graphics/ewwbar.nix` and stored in `/etc/eww/eww.css`.
Available widgets (from left to right):
- Launcher;
- Battery;
- Wifi;
- Bluetooth (currently disabled);
- Security (currently disabled);
- Keyboard layout indicator;
- Clock;
- Date;
- Calendar (can be opened through date widget).
Known issues:
- Currently, it is only possible to read the initial keyboard layout set during boot (US, as defined in `modules/desktop/profiles/graphics.nix`). Any subsequent changes made to the …

Taskbar replacement using EWW

---

modules/disko/disko-zfs-postboot.nix

This fix resolves SSRCSP-5296.
Previously, zfspool has not been expanded for the system, installed on nvme drive. The issue was so that a partition's parent disk name is not resolved correctly for `/dev/nvme0n1` device.
Install the system and check ZFS pool size with `zpool status` or `zpool list`. It must occupy all the free space available on the disk.

Fix postboot command for ZFS installation.

---

modules/common/services/desktop.nix
modules/desktop/graphics/labwc.nix
modules/reference/appvms/business.nix
packages/icon-pack/default.nix

gnome-text-editor is added into business-vm with icon

Add gnome-text-editor application in business-vm

---

modules/microvm/virtualization/microvm/appvm.nix
modules/microvm/virtualization/microvm/common/shared-directory.nix
modules/microvm/virtualization/microvm/microvm-host.nix
modules/reference/profiles/laptop-x86.nix
modules/reference/programs/chromium.nix

Add directory that allow user to share files between appvms and guivm easily.
1. Connect to chromium-vm and create file in `/home/ghaf/Unsafe share` directory.
2. Go back to guivm and move file from `/home/ghaf/Shares/Unsafe chromium-vm share` to `/home/ghaf/Shares/Unsafe business-vm share`.
3. Connect to business vm and check that file appears in `/home/ghaf/Unsafe share` directory.
4. Check that file stays in place after reboot.

Add common directory

---

flake.lock
modules/desktop/graphics/ewwbar.nix
packages/audio-ctrl/default.nix
packages/bt-launcher/default.nix

1. **Moved Taskbar to the Top:**
- Based on user feedback, the taskbar has been relocated to the top of the screen.
2. **Added Quick Settings Widget:**
- Introduced a new **Quick Settings** widget that allows users quick access to essential system settings.
- The widget can be opened by clicking on the controls area in the taskbar (WiFi, Battery, Brightness, Volume).
3. **Added Power Menu Widget:**
- Implemented a **Power Menu** widget that includes options for shutdown, restart, and suspend.
4. **Added Bluetooth & WiFi Buttons:**
- Added dedicated buttons for **Bluetooth** and **WiFi** in the Quick Settings widget.
- The WiFi button is dynamic - the icon and subtitle represent different connection strengths and statuses.
- Clicking on the Bluetooth and WiFi buttons will open their …

EWW Taskbar adjustments and additional EWW widgets

---

overlays/custom-packages/waypipe/default.nix
overlays/custom-packages/waypipe/waypipe-fix-reading-data-from-pipes.patch

This fixes issues with copying and pasting images from the clipboard between virtual machines. It turned out to be a bug in waypipe that prevents it from synchronizing pipes with data larger than 64 KB. This seems to be one of those issues that are not easy to track but the fix is a one-liner or even a half-liner.
Fixes SSRCSP-5120.
Copy images from Chromium to Outlook using the clipboard. The complete testing procedure is described in SSRCSP-5120.

Fix the copying and pasting of images between VMs

---

modules/common/services/desktop.nix
modules/reference/appvms/business.nix

Add VideoEditor into BusinessVM.
Use losslesscut as the video editor
Run "Video Editor" from an app list. It should run (after a few seconds)

[Packages] Add VideoEditor into BusinessVM

---

modules/reference/appvms/business.nix
modules/reference/profiles/mvp-user-trial.nix
modules/reference/services/default.nix
modules/reference/services/proxy-server/3proxy-config.nix
modules/reference/services/proxy-server/ms_urls.json

The proxy solution, which can allow or deny specific URLs, has been implemented as shown in the picture above. The HTTP/HTTPs packets from the business-vm will be redirected through the proxy server in netvm.
- The targets include business-vm 
- ms365 URLs fetched from [the link](https://endpoints.office.com/endpoints/worldwide?clientrequestid=b10c5ed1-bad1-445f-b386-b919946339a7) instead of static firewall policy configuration. [URLs](https://endpoints.office.com/endpoints/worldwide?clientrequestid=b10c5ed1-bad1-445f-b386-b919946339a7) should be accessible through proxy. In other words Teams, Outlook, and Microsoft 365 apps should work flawlessly
- URLs with tii domain can be only accessible through VPN.

Proxy setup to allow/deny specific urls for BusinessVM

---

.github/workflows/doc.yml
.github/workflows/scorecard.yml
REUSE.toml
docs/book.toml
docs/theme/pagetoc.css
flake.lock
flake.nix
modules/desktop/graphics/labwc.config.nix
modules/desktop/graphics/login-manager.nix
modules/microvm/virtualization/microvm/adminvm.nix
modules/reference/appvms/business.nix
modules/reference/profiles/laptop-x86.nix
modules/reference/services/proxy-server/ms_urls.json
nix/checks.nix
nix/devshell.nix
nix/treefmt.nix
pyproject.toml

just loads the applications into the devshell correctly
this change only targets the development shell that is seen with either `nix develop` or `direnv allow`

fix the direnv and checkers

---

modules/common/services/audio.nix
modules/microvm/virtualization/microvm/audiovm.nix
modules/microvm/virtualization/microvm/microvm-host.nix
modules/reference/hardware/lenovo-x1/definitions/x1-gen10.nix
modules/reference/hardware/lenovo-x1/definitions/x1-gen11.nix

Fix audiovm pulseaudio initial microphone profile
Integrated speakers & mic should work after boot
May work with rebuild-switch but definitely requires a full reboot

Fix1 for pulseaudio selecting default integrated audio profile

---

modules/desktop/graphics/labwc.config.nix
modules/desktop/graphics/login-manager.nix
modules/reference/profiles/mvp-user-trial.nix

Autolock the system by default after boot up.
~~## Issue~~
~~Brightness will be minimum at system boot~~

mvp-user-trial: Enable autolock on system boot

---

targets/imx8mp-evk/flake-module.nix

-------
fixes the breaking build
The nxp target should build
`nix build .#packages.aarch64-linux.nxp-imx8mp-evk-debug`

Disable the tpm in the nxp targets.

---

modules/microvm/virtualization/microvm/audiovm.nix

* Addresses:  SSRCSP-5363
* This patch will start logging journal logs collected from audio-vm to grafana server in the cloud.
* Now `audio-vm` logs will also get uploaded to grafana-server.

logging: Collect journal logs from audio-vm

---

modules/common/services/desktop.nix
modules/microvm/virtualization/microvm/common/storagevm.nix
modules/microvm/virtualization/microvm/guivm.nix
modules/reference/services/default.nix
modules/reference/services/ollama/ollama.nix

- Add ollama (AI backend) and alpaca (AI frontend).
- ~Autoload falcon2 model whenever there is an internet connection~
- Added load-falcon command to load the model, which shows user-friendly notification.
- This command should be integrated with UI later, such as in system bar or widgets.
- ~Increased system partitions size until a permanent fix is available.~ fixed by #813 
This PR carries some overlays and systemd options that should be removed by ~#769~ #809
- Fresh installation of Ghaf (rebuild is not enough)
- Connect to Wi-Fi, open terminal in gui-vm, run `load-falcon`
- On a 50Mb/s internet connection, it may take a bit over 20 minutes
- You can see the progress by running `systemctl status ollama-model-loader`.  If you see messages with "blob", it is downloading. If deactivated …

Add Falcon LLM

---

docs/src/release_notes/ghaf-24.06.md
modules/common/networking/hosts.nix
modules/common/services/desktop.nix
modules/desktop/graphics/demo-apps.nix
modules/desktop/graphics/labwc.nix
modules/reference/appvms/default.nix
modules/reference/profiles/mvp-user-trial.nix

unused and unloved
can be used as a reference of how we currently have to enable apps and app vms.
-------
carbon x1 MVP 
removes appflowy. it should not be enabled `microvm -l` in the host should not show it and it should be removed from the launcher.

disable the appflowy

---

modules/common/systemd/hardened-configs/common/alloy.nix

- alloy.service hardening
- Security exposure reduced to 2.8
- Lenovo X1 Carbon 
- Check if the logs are accessible on Grafana server.
(I have tested it at my end, logs are available at Grafana Server)

alloy.service hardening

---

modules/common/services/desktop.nix
modules/desktop/graphics/ewwbar.nix
modules/microvm/virtualization/microvm/guivm.nix
packages/nm-launcher/default.nix

Replace `nm-connection-editor` with `nm-applet` for system network configuration.
- Check that application appears in tray on startup.
- Test that it is easier to connect to wifi using network manager applet in comparison with `nm-connection-editor`.

Add network manager applet

---

.github/workflows/build.yml
flake.nix
modules/reference/services/proxy-server/3proxy-config.nix
templates/boilerplate/flake.nix

Remove all references to cache.vedenemo.dev that is not populated any more, and will be completely gone soon.
- [ X ] Summary of the proposed changes in the PR description
- [ X ] Commits are squashed into relevant entities - avoid a lot of minimal dev time commits in the PR
- [ X ] [Contribution guidelines](https://github.com/tiiuae/ghaf/blob/main/CONTRIBUTING.md) followed

Retire cache.vedenemo.dev

---

flake.lock

Add AppVM names support. Now you can see, which stream belongs to which AppVM
Run Audio Control
Run Chromium and check, that steams appear under "Chromium-appvm" name
Another audio apps, if it is possible

[GhafPkgs] Update Audio Control

---

modules/common/services/desktop.nix
modules/desktop/graphics/ewwbar.nix
modules/desktop/graphics/labwc.config.nix
modules/desktop/graphics/styles/gtk-lock.nix

1. **Added Control Panel and Power Menu Buttons**:
- New control panel button (called "Settings" now) added to the quick settings widget.
- New log out and lock buttons added into the power menu widget.
- More detailed design and composition currently in progress by UI designer.
2. **Removed Shutdown and Log Out Apps From Launcher**:
- The shutdown and log out applications have been removed from the launcher to reduce redundancy.
3. **Added Missing nm-applet UI Elements**:
- Missing UI elements for the nm-applet have been added.
4. **Moved GTK Lock Style Definition To Its Own File**: 
- This PR proposes moving all future style definitions to `modules/desktop/graphics/styles` for easier maintainability of the styles and the components that use them.
- Other styles that could be moved …

EWW: Add control panel, log out, and lock buttons, restyling

---

packages/audio-ctrl/default.nix

Minor change to simplify audio-ctrl helper script
The script is used by eww-bar and desktop for hardware volume buttons

Simplify audio-ctrl helper package

---

flake.lock
flake.nix
modules/disko/disko-ab-partitions.nix

Remove unneeded partitions
Add compression
Add swap space
- enable resume from the swap partition
the flake update should be tested on all targets
the zfs changes should be tested on the x1 image
It enables swap partition and removes some unused partitions
A full installation is needed to verify the changes and to ensure that the changes have been applied. without a full installation the image will not boot on the x1

bump the flake and fix the zfs disk

---

modules/microvm/virtualization/microvm/appvm.nix

QEMU VMs require a USB controller for hotplugging to work. MicroVM.nix automatically enables the USB controller when any static USB devices are added or when graphics.enable is set to true, but this is not the case for all AppVMs. For example, after the internal USB camera passthrough to ChromiumVM was commented out, there is no USB controller present and USB camera hotplugging no longer works. This fix addresses that issue.
Fixes SSRCSP-5500.
Connect a USB camera to Lenovo X1 and make sure it's available in Chromium.

Enable USB controller for AppVMs

---

modules/desktop/graphics/ewwbar.nix
modules/desktop/graphics/ghaf-launcher.nix
modules/desktop/graphics/labwc.config.nix
modules/desktop/graphics/login-manager.nix
modules/desktop/graphics/styles/launcher-style.nix
modules/desktop/graphics/styles/lock-style.nix
modules/desktop/graphics/styles/login-style.nix

1. **Improved Autolock Functionality**:
- Previously, when inactive for 5 minutes, the screen would dim to low brightness and return to 100% brightness for a moment before locking.
This behavior should be fixed now - the transition from dimming to the lock screen should now be smooth.
- Can be tested by letting system idle for 5 minutes or replacing `${builtins.toString cfg.autolock.duration}` with desired time in seconds in `/modules/desktop/graphics/labwc.config.nix:267`.
2. **Relocated Styles**:
- Moved the definitions for the lock screen, login screen, and app launcher styles into the dedicated styles directory.
3. **Updated Default Lock Behavior**:
- Changed the default lock behavior to use `loginctl`. Loginctl `lock-session` behavior is defined in labwc.config `lock-event` service. …

Improved autolock functionality, relocated styles

---

modules/microvm/virtualization/microvm/appvm.nix
modules/microvm/virtualization/microvm/common/ghaf-audio.nix

Set Ghaf audio apps to directly connect to audiovm with pulseaudio
Makes app vms use audiovm pulseaudio directly without application audio tunneling
With this change the pulseaudio don't move patch is not needed
Appvm audio routing has changed, audio should work same as before

Pulseaudio direct connection

---

modules/desktop/graphics/ewwbar.nix
modules/desktop/graphics/labwc.config.nix
packages/ghaf-workspace/default.nix

1. **Added Workspaces Control Script**:
- Introduced a new control script for managing ghaf workspaces in `packages/ghaf-workspace`.
- This script is necessary because labwc does not provide commands to control or monitor workspaces directly, apart from keybind functionality.
- The script keeps track of current workspace and max number of workspaces in separate files under `~/.config/labwc`;
- Active workspace should be remembered between system reboots;
2. **Added Workspaces Widget to Taskbar**:
- Added to the top-left section of the taskbar.
- Displays the active workspace index and allows users to switch workspaces directly from the taskbar.
3. **Configured Keybindings for Workspace Switching**:
- Added keybindings for workspace switching:
- `Super + [number]` — Switches to the …

EWW: Taskbar workspaces control

---

.github/workflows/build.yml
.github/workflows/check.yml
.github/workflows/doc.yml

- Stop building any ghaf targets directly on github-hosted runners in the `build.yml` workflow. Instead, delegate all builds to remote builders as configured in github action variable `BUILDER_MACHINE_CONFIG`. Currently, all builds will be delegated to `hetzarm.vedenemo.dev` (aarch64) and `build4.vedenemo.dev` (x86_64). We hope this change also makes it possible to start building ghaf's biggest targets (`package-lenovo-x1-carbon-gen11-debug` and `package-generic-x86_64-debug`) in the `build.yml` github action. Adding those targets to the `build.yml` will be done later in a follow-up PR.
- Make builds in `build.yml` start using binary caches as configured in the [ghaf flake](https://github.com/tiiuae/ghaf/blob/285596115982fd3eb53ebd358b1dbcc3c5128414/flake.nix#L6-L24) by setting the …

Move all workflow builds to remote builders

---

.github/workflows/build.yml

Start building ghaf targets `generic-x86_64-debug` and `lenovo-x1-carbon-gen11-debug` in the build.yml workflow.
This should work after https://github.com/tiiuae/ghaf/pull/865 since all the builds are now done on the remote builders, not on the github-hosted runners. Earlier attempts to enable  `generic-x86_64-debug` or `lenovo-x1-carbon-gen11-debug` on the build workflow have failed due to two reasons: **(1)** github-hosted runners not having enough resources to build these massive targets and **(2)** [hash mismatches](https://github.com/tiiuae/ghaf/issues/444) I suspect have occurred mostly due to github-hosted runners running the builds on Ubuntu-based VMs. After https://github.com/tiiuae/ghaf/pull/865, both those issues should  be resolved by running all the builds on the remote (nix) …

build.yml: Build x86 generic and x1 targets

---

modules/desktop/graphics/labwc.config.nix
modules/desktop/graphics/labwc.nix
modules/microvm/virtualization/microvm/appvm.nix
modules/microvm/virtualization/microvm/common/waypipe.nix
modules/microvm/virtualization/microvm/guivm.nix
modules/reference/appvms/business.nix
modules/reference/appvms/chromium.nix
overlays/custom-packages/waypipe/default.nix
overlays/custom-packages/waypipe/waypipe-security-context.patch
overlays/custom-packages/waypipe/waypipe-window-borders.patch
packages/vsockproxy/default.nix

This enables support for the Wayland security context protocol in Ghaf. I previously added support for it to Labwc and Waypipe and upstreamed those changes. The version of Labwc used in Ghaf already includes it. For Waypipe, I added a patch but it was merged upstream recently. The new version should be released close to the end of the year. After that we should be able to get rid of the Waypipe overlay.
The security context protocol allows window frame colors to be defined on a per-VM basis rather than by application identifier. All settings are defined on the compositor side and AppVMs cannot change them. The same application can now have different border colors when run from different VMs. For example, the trusted browser and the regular one now have different colors, even though they …

Enable Wayland security context protocol

---

modules/desktop/graphics/ewwbar.nix
modules/microvm/virtualization/microvm/guivm.nix

1. **Fixed Popups Not Closing Automatically**
- Resolved an issue where popups were reserving screen space even after "closing".
- This applies to volume and brightness change indicators (previously referred to as hotkey indicators).
2. **Adjusted Popups to Have Their Own Windows**
- Updated popup behavior so that each popup now opens in a separate, isolated window.
Popups will no longer interfere with each other and simply overlap instead.
3. **Added Functionality to Close Widgets by Clicking Outside**
- Widgets should now close automatically when clicking outside their area (e.g. on the desktop).
- This applies to power menu, calendar and quick settings widgets.
4. **Added wlr-randr to guivm**:
- To be used in the future by Ghaf control panel.
- If multiple displays are connected, …

EWW: Fix popup window not closing properly, add wlr-randr to guivm

---

REUSE.toml
flake.lock
flake.nix
modules/common/common.nix
modules/common/systemd/base.nix
modules/common/systemd/systemd-localed-locale-archive.patch
modules/common/systemd/systemd-re-enable-locale-setting.patch
modules/desktop/graphics/waybar.config.nix
modules/microvm/virtualization/microvm/adminvm.nix
modules/microvm/virtualization/microvm/appvm.nix
modules/microvm/virtualization/microvm/guivm.nix
modules/microvm/virtualization/microvm/microvm-host.nix
targets/laptop/laptop-configuration-builder.nix

Re-enables locale setting in systemd-localed, with added support for LOCALE_ARCHIVE.
Removed hardcoded timezone setting to allow timedatectl set-timezone to work.
Run: `/nix/store/*-cli/bin/givc-cli --addr admin-vm-debug --name admin-vm-debug --port 9001 --notls set-locale ar_AE.UTF-8` and start chromium; observe UI language in Arabic. Run again with `set-timezone Europe/Helsinki`, observe UI time change. Reboot device, and changes should persist.

Enable setting locale and timezone

---

.github/workflows/build.yml

Start using [nix-fast-build](https://github.com/Mic92/nix-fast-build) in the build.yml workflow to execute all build operations completely on the remote end.
Removes the step 'Maximize space available on rootfs' since with `nix-fast-build`, we no longer download the full build closure on the github-hosted runner. Furthermore, with the `--no-download` option, we also skip the download of the final build result (ghaf image), so we no longer need to free up the storage on the github runner.
This change also removes the upload to https://ghaf-dev.cachix.org from the build workflow: it is no longer needed, since builds are already cached on the remote builders' local nix store. Jenkins builds will take care of uploading the build binaries to a separate nix binary cache, maintained with …

build.yml: Use nix-fast-build to build on remote

---

modules/hardware/common/usb/vhotplug.nix

The integrated camera is passed to the business-vm through the QEMU options but the hot-plugging service is configured to pass all USB cameras to the chromium-vm. This adds it to the ignore list so that it stays connected to the business-vm.
Fixes SSRCSP-5557.
Test that the integrated Lenovo X1 camera works in applications launched from the business-vm.
Note: A reboot is required if the system is updated using nixos-rebuild.

Fix integrated camera in business-vm

---

flake.lock

a partial bump of the available tools updates
includes the latest fixes for the control panel
-------
Some small changes to microvm and the supporting tools
all targets
minor version updates
control panel updates - 
Green/OK statuses for all VMs and services
Display settings: resolution and scale can be changed, confirmation popup added
Start and stop apps (only once because of some internal library bug)
Also button for launching audio control widget added, but not tested

bump some tools

---

modules/hardware/common/usb/vhotplug.nix

Using the vendor:product ID for the UAE SKU
-------
MVP X1 carbon
Enables internal camera in the business-vm for the UAE laptops running on X1

Fix the camera pass through to the business-vm

---

modules/desktop/graphics/ewwbar.nix
modules/desktop/graphics/labwc.config.nix
modules/desktop/graphics/labwc.nix
modules/desktop/graphics/styles/launcher-style.nix
modules/desktop/graphics/styles/lock-style.nix

This adds basic bar back on targets without givc, such as vm-debug and orin.
Note that widgets, settings and network applet are still not implemented on these systems. Only power control and date/time is available.

desktop: add bar in targets without givc

---

modules/common/services/audio.nix
modules/common/services/desktop.nix
modules/desktop/graphics/ewwbar.nix
modules/desktop/graphics/labwc.config.nix
packages/bt-launcher/default.nix

Add separate audio control channel for audio control data
This allows using unprivileged pulseaudio channel for apps
and channel with more privileged for controlling pulseaudio
No visible change to the user. Controlling audio should work through different TCP port (4714)

Add separate audio control channel

---

modules/common/networking/hosts.nix
modules/common/services/desktop.nix
modules/desktop/graphics/demo-apps.nix
modules/givc/common.nix
modules/hardware/common/usb/vhotplug.nix
modules/reference/appvms/business.nix
modules/reference/appvms/comms.nix
modules/reference/appvms/default.nix
modules/reference/appvms/google-chrome.nix
modules/reference/profiles/laptop-x86.nix
modules/reference/profiles/mvp-user-trial.nix
modules/reference/programs/default.nix
modules/reference/programs/google-chrome.nix
packages/ghaf-xdg-open/default.nix
packages/icon-pack/default.nix
packages/mitmweb-ui/default.nix
packages/open-normal-extension/open_normal.sh

Enabling google-chrome system-wide for apps and standalone usage.
1. Boot up the device and connect to WiFi.  
2. Open the following applications and check their functionality: Microsoft 365, Microsoft Outlook, Teams, Google Chrome, 
and trusted browser.  
4. Ensure the [Open in normal browser](https://github.com/tiiuae/ghaf/pull/815) is functional.  
5. Sign in to your Google account in Google Chrome and send tabs from another device that is already signed in to that account.  
6. Confirm that bookmarks are synced to your Google account in Chrome. 
7. Try to access webcam through google chrome or the apps 
Note: Google Chromecast feature does not work as a known issue

Adding google chrome program to ghaf

---

packages/vhotplug/default.nix

This updates the hotplugging service to detect VM restarts and automatically reconnect devices. Currently, users need to manually reconnect USB devices like keyboards and mice after a gui-vm restart, which happens quite often after nixos-rebuild switch. This fix makes all hotplugged devices persist through VM restarts.
Fixes SSRCSP-5141.
On Lenovo X1, connect USB input devices, restart gui-vm and make sure they still work.
A more detailed testing procedure is described in SSRCSP-5141.
Note: A reboot or hotplugging service restart is required if the system is updated using nixos-rebuild.

Implement autoreconnect for hotplugged devices on VM restarts

---

packages/ghaf-xdg-open/default.nix

- Opening PDF files from file manager should work.
- Open files from each VM that supports PDF and image viewing. All combinations should work.

Fix opening files from gui-vm

---

modules/common/systemd/hardened-configs/common/microvm@.nix
modules/common/users/accounts.nix
modules/desktop/graphics/ewwbar.nix
modules/hardware/common/default.nix
modules/hardware/common/shared-mem.nix
modules/microvm/flake-module.nix
modules/microvm/virtualization/microvm/common/waypipe.nix
modules/microvm/virtualization/microvm/guivm.nix
overlays/custom-packages/qemu/0001-ivshmem-flat-memory-support.patch
overlays/custom-packages/qemu/default.nix
packages/memsocket/default.nix
packages/memsocket/module.nix
packages/wifi-signal-strength/default.nix

Add memory sharing mechanism between virtual machines and use it for wayland/waypipe displaying.
- Added the shared memory manager within QEMU.
- Direct Memory Mapping via SysBus:
- Modified QEMU's code to map shared memory directly into the VM's memory address space using the SysBus interface.
- Option for Defining Shared Memory Manager:
- Added an option to QEMU for defining a shared memory manager when running VMs.
- BigPages Area Allocation:
- Allocated shared memory within the BigPages area for optimized memory usage.
1. **Linux Driver for Shared Memory and Interrupts:**
- Added a Linux driver to manage shared memory operations and interrupts and creating the `/dev/ivshmem` device.
2. **Memsocket Application for Inter-VM Communication:**
- Introduced the `memsocket` application to …

Wayland displaying using shared memory between virtual machines

---

modules/common/services/disks.nix
modules/desktop/graphics/ewwbar.nix
modules/desktop/graphics/labwc.config.nix
modules/desktop/graphics/labwc.nix

1. **Fixed  USB Tray Icon Not Appearing Consistently:**
- ~The USB tray icon should now appear consistently on device plugin and disappear on device removal.~
- The USB tray icon will now always be visible, even if no devices are connected.
This is due to how [EWW](https://github.com/elkowar/eww) handles the systray widget - visibility updates do not refresh the systray.
2. **Added Missing Adwaita Cursor Types**
- Verify USB tray applet is working as intended:
- Appears and disappears with device adding and removal respectively
- Applet menu contains all necessary functionality
- USB notifications for mounting, adding, removing etc. appear consistently
- Verify all cursor types work as intended (can be tested here https://codepen.io/WebDevCA/pen/DRjdMa)
- Due to a minor change in how …

Desktop: Fix USB tray icon, add missing cursor types

---

overlays/custom-packages/qemu/acpi-devices-passthrough-qemu-8.1.patch

When no battery is available, qemu vms will have dummy battery information and GUI will show 0% battery and not charging.
This was done by tweaking the qemu battery device patch, so that if battery is not available, dummy information is presented.
Please comment on the PR, if this approach is not desired for some reason. If that is the case, then we'll probably have to create a separate target for setup without a battery (for current measurements). Note that in X1 user is not expected to casually remove the battery, as removing it requires unscrewing several screws.
- Run ghaf in X1 with battery and see that it works normally: Battery status shows proper information.
- Run ghaf in X1 without a battery and see that it works normally but battery shows 0% and not charging.
Without this …

Fix gui-vm not starting when no battery installed

---

modules/desktop/graphics/ewwbar.nix
modules/desktop/graphics/labwc.config.nix

1. **Fixed notifications breaking after a display is removed:**  
- Previously, notifications would stop working if a display showing a notification was suddenly disconnected.  
- This fix implements a workaround for a known issue in Mako upstream ([issue #512](https://github.com/emersion/mako/issues/512)). 
- Confirm that notifications continue to appear correctly after disconnecting an external display.  
- Verify no regression in taskbar behavior when connecting and disconnecting external displays.

Desktop: Fix notifications breaking after display is removed

---

modules/desktop/graphics/ewwbar.nix
modules/desktop/graphics/labwc.config.nix
modules/desktop/graphics/labwc.nix

1. **Increased Default Number of Virtual Desktops to 4**
2. **Added Configurable `maxDesktops` Setting:**
- Added a `maxDesktops` option in the `labwc` nix config (`labwc.nix`).
- Changes to the compositor and taskbar configs are handled automatically based on the `maxDesktops` value.
3. **Desktop ID Popup on Desktop Switch:**
- Implemented a popup window to display the current desktop when switching between virtual desktops.
1. Confirm that the number of available virtual desktops has increased from 2 to 4.
2. Verify that switching between desktops works using:
- `Super` (Windows key) + `[number]`.
- `Super` + `Alt` + `[left/right]` to cycle through desktops.
3. Ensure a popup appears when switching desktops, indicating the currently active desktop.
4. (Optional) Verify Desktop id popup …

Desktop: Enhance virtual desktop configuration and add desktop id popup

---

flake.lock
modules/common/services/desktop.nix
modules/microvm/virtualization/microvm/guivm.nix

So the Audio Control is always up and able
in system tray and by DBus
- Run Ghaf
- Check, that Audio Control icon in system tray appeared

[GuiVM] add Audio Control systemctl service

---

modules/common/security/apparmor/default.nix
modules/common/security/apparmor/profiles/google-chrome.nix
modules/common/security/apparmor/profiles/ping.nix
modules/common/security/default.nix
modules/common/services/xdghandlers.nix
modules/reference/appvms/business.nix
modules/reference/appvms/google-chrome.nix
modules/reference/personalize/authorizedSshKeys.nix

- Enabled AppArmor 
- AppArmor profiles for google-chrome and ping
- AppArmor enabled in chrome-vm and business-vm
- [] Author has run `nix flake check --accept-flake-config` and it passes
Verify if chromium profile is active inside chromium-vm.
`$> sudo aa-status`
Do audio and video recording/playback, Google spread sheet editing using Chromium browser.
A brief documentation and test report are available in confluence.
https://ssrc.atlassian.net/wiki/spaces/GA/pages/1187708968/Security#1.-AppArmor%3A

Enable AppArmor 

---

modules/desktop/graphics/labwc.nix

With this patch user can set custom image when the system is locked for identification purpose.
User Image can be set when system is locked
```
[ghaf@gui-vm:~]$ ls /home/ghaf/Pictures/.face (any jpg file is fine, recommended to use circular image)
```

gtklock-userinfo-module: Add custom Icon path

---

modules/common/security/apparmor/profiles/google-chrome.nix

- Fixes camera access issue in business and chrome vm
- Appropriate access provided in Google Chrome Apparmor profile
- Fixes:
https://jira.tii.ae/browse/SSRCSP-5864
- Lenovo X1
-  Check if external camera is accessible from Google chrome (I used http:://veed.io/record)
-  Check if internal camera is accessible from Microsoft Teams.
-  If you want to do full installation you will have to increase VM memory to avoid OOM:
```
diff --git a/modules/disko/disko-ab-partitions.nix b/modules/disko/disko-ab-partitions.nix
index 042f220..bb0d308 100644
--- a/modules/disko/disko-ab-partitions.nix
+++ b/modules/disko/disko-ab-partitions.nix
@@ -47,7 +47,7 @@
};
disko = {
-      memSize = 17384;
+      memSize = 20480;
imageBuilder = {
extraPostVM = lib.mkIf (config.ghaf.imageBuilder.compression == …
```

Fix camera access in chrome and business vm

---

modules/common/systemd/hardened-configs/common/greetd.nix
modules/disko/disko-ab-partitions.nix

- Hardened service config for greetd
- Exposure level after hardening: 3.5
- Lenovo x1 
- Boot the system and login, check if the system behaves normal.

greetd.service hardening

---

docs/src/SUMMARY.md
docs/src/release_notes/ghaf-24.12.md
docs/src/release_notes/release_notes.md

Docs: add ghaf-24.12 release notes

---

targets/generic-x86_64/flake-module.nix

Binary images of all other targets are compressed already during the build phase. This makes downloads significantly faster. Compress also x86_64-linux.generic-x86_64-debug image in the build phase.
Check that image works as expected after manual decompression or check that flash script succeeds.

Compress generic-x86_64 image

---

modules/common/users/admin.nix
modules/common/users/desktop.nix
modules/desktop/graphics/labwc.nix
modules/microvm/virtualization/microvm/audiovm.nix
modules/microvm/virtualization/microvm/guivm.nix
modules/microvm/virtualization/microvm/microvm-host.nix
modules/reference/services/ollama/ollama.nix

This PR includes the following changes and fixes:
- remove fingerprint authentication from `greetd` as user home needs decryption
- re-ordering PAM modules on gtklock to unlock with either password or fingerprint, not requiring both
- add custom rule to require users to be in group `video`, preventing
admin login on GUI. Still works for AGX/NX with `createHome` option. 
- remove older 'desktop' group in favor of 'video'
- fix user creation script to disallow creating user duplicates
- fix user creation script to allow '-' characters in name
-  move ollama persistent directory to service, removing failing ollama
user/group setting, adding guard for launcher
- move XDG parameters from gui-vm to labc config
This should also fix [SRCSP-5891](https://jira.tii.ae/browse/SSRCSP-5891). The user …

Custom PAM rule for desktop login

---

.github/workflows/build.yml

PR https://github.com/tiiuae/ghaf/pull/949 changed the build workflow so it triggers also on push/merge to main.
As a result, the build workflow would also run on forked repositories, yielding unnecessary errors.
This change adds a check to not try to run the build workflow in forked repositories.
Tested in fork at: https://github.com/henrirosten/ghaf/actions/runs/12793643895.
Ref: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/using-conditions-to-control-job-execution#example-only-run-job-for-specific-repository

GhA: Skip build workflow in forked repositories

---

modules/desktop/graphics/ewwbar.nix
modules/desktop/graphics/ewwbar/config/scripts/default.nix
modules/desktop/graphics/ewwbar/config/variables/default.nix
modules/desktop/graphics/ewwbar/config/widgets/default.nix
modules/desktop/graphics/ewwbar/config/windows/default.nix
modules/desktop/graphics/labwc.nix
modules/desktop/graphics/styles/ewwbar-style.nix

1. **Added Volume Mixer Widget in the Taskbar Quick Settings (currently disabled):**
- The volume mixer is accessible by clicking the "settings" icon next to the System Volume slider.
- It dynamically displays currently active sink inputs (audio streams) or remains empty if no sink inputs are active.
- Each sink input can be individually controlled, offering the same core functionality as the System Volume slider, including volume adjustment, mute, and unmute.
- Each sink input will show the associated app icon if available. If not available, it will fallback to the default speaker icon.
- Tested only with Google Chrome browser audio playback.
2. **Added Microphone slider in the Taskbar Quick Settings:**
- Slider appears only when the default input device is in "RUNNING" state;
- Slider …

Desktop: eww config refactor, mic volume widget

---

modules/desktop/graphics/ewwbar/config/scripts/default.nix
modules/desktop/graphics/ewwbar/config/variables/default.nix
modules/desktop/graphics/ewwbar/config/widgets/default.nix
modules/desktop/graphics/styles/ewwbar-style.nix

1. **Added active audio device selection in the Quick Settings widget**
- Can be opened by clicking the device name above the audio volume slider.
- Output and Input devices can be selected independently.
- The currently active device can be identified by the checkmark next to its' name.
- Designs are not final.
2. **Adjusted the fetching of audio data to improve performance**
1. **Non-critical error messages can be observed in Eww logs when opening Quick Settings widget**
- For both Output and Input devices:
- Verify device selection opens and closes as expected
- Verify device can be selected and becomes active immediately
- Verify new devices are added to the list when connected
- Verify devices are removed from the list when disconnected
- Verify selected device name is the same in …

Desktop: Select audio device from taskbar

---

modules/desktop/graphics/ewwbar.nix
modules/desktop/graphics/ewwbar/config/scripts/default.nix
modules/desktop/graphics/ewwbar/config/widgets/default.nix
modules/desktop/graphics/ewwbar/config/windows/default.nix
modules/desktop/graphics/labwc.config.nix
modules/desktop/graphics/styles/ewwbar-style.nix

1. **Automatic scaling for HiDPI displays:**  
- Automatic scaling is now performed during system boot and on display-related events
- Manual scaling settings are not supported.
- See the scaling table below for more details:
| Condition                  | Scaling Factor | Description                                      |
|----------------------------|----------------|--------------------------------------------------|
| TV size <= 65 inches        | 1.50           | 150% scaling for TVs up to 65 inches             |
| TV size > 65 inches         | 1.75           | 175% scaling for TVs larger than 65 inches       |
| PPI < 170                   | 1              | No scaling for low PPI displays                 |
| 170 <= PPI < 200            | 1.25           | 125% scaling for medium PPI …

Desktop: Automatic scaling on HiDPI displays

---

modules/common/systemd/hardened-configs/common/systemd-udevd.nix
modules/microvm/virtualization/microvm/guivm.nix

- Fixed dynamic user login issue with hardened systemd configs.
- Mounting user home requires admin capability in systemd-udevd, so allowed it.
- Login to gui-vm and see if everything is working fine.

Enable systemd hardened configs in gui-vm

---

modules/common/development/nix.nix
modules/microvm/virtualization/microvm/microvm-host.nix

- Disables nix tooling if development setup is not enabled
- Indirectly disables nix tooling in release build
- Enables automatic garbaze collection in ghaf-host and disable everywhere else.
- Fixes:
https://jira.tii.ae/browse/SSRCSP-3457
- Lenovo X1
- Jetson Orin NX and AGX 
- In release build, no nix commands should be available, nix daemon should not be running.
- As Terminal is not available in release flavor, disable nix-setup in `./modules/common/profiles/debug.nix` (to imitate release)
```
nix-setup.enable = false;
```
- Build debug image and run. No nix commands should be available, nix daemon should not be running. 
- In debug build nix daemon should be running in all VMs and automatic garbage collection should be available only in host.
- If automatic garbaze collection is …

Disable nix tooling

---

modules/reference/appvms/comms.nix

a '\n' separated list is expected for the udev.extraRules not null. was failing to evaluate on the dell-latitude devices.

fix the addition of the gps

---

.github/eval.sh
.github/workflows/check.yml
.github/workflows/eval.yml

Re-introduce the following changes from https://github.com/tiiuae/ghaf/pull/947:
- Move the nix evaluation step to its own workflow `eval.yml`, which runs the nix evaluation in parallel, splitting the evaluation to 8 subsets, each of which are executed on a separate github-hosted runner. In testing, this improves the eval action runtime from ~35 minutes down to ~7 minutes. 
- `eval.sh` allows filtering the evaluated targets via the `-t` [option](https://github.com/tiiuae/ghaf/blob/00e910f2bf2227b28111985dd658b5edd1fd3073/.github/eval.sh#L31): the initial version in this PR will evaluate all Ghaf flake outputs that match the default filter '`packages.*`'. 
Apparently Ghaf flake does not evaluate with `nix flake show --all-systems` the way suggested in …

Github action parallel nix eval

---

modules/hardware/common/devices.nix
modules/hardware/common/usb/vhotplug.nix
modules/hardware/definition.nix
modules/reference/hardware/lenovo-x1/definitions/x1-gen12.nix
targets/laptop/flake-module.nix
targets/lenovo-x1-installer/flake-module.nix

Added new target for gen12.
Added pass-through for gen12 devices.
Enable access to video bios table (VBT) to gui-vm.
Requires update to microvm side to enable passing of extra arguments: [https://github.com/astro/microvm.nix/pull/325](https://github.com/astro/microvm.nix/pull/325)
- [N/A] Tested on Jetson Orin NX or AGX `aarch64`
- [N/A] Tested on Polarfire `riscv64`
* lenovo-x1-carbon-gen12-debug
* lenovo-x1-carbon-gen12-release
* Build a Ghaf gen12 target
* Test that Ghaf works on a Lenovo X1 Carbon Gen 12 laptop

Lenovo X1 Carbon Gen 12 support

---

flake.lock
nix/devshell.nix

These upstream pulls revert an issue that breaks the hostPlatform determination during eval and build.
https://github.com/NixOS/nixpkgs/pull/379615
https://github.com/NixOS/nixpkgs/pull/379802

bump: fix hostPlatform errors

---

modules/common/services/audio.nix

Fixes issue with 3,5mm headphone jack did not get automatically selected
Issue caused with Pipewire/wireplumber default configuration change
Boot X1 without headphones, play music, connect 3.5mm headphones, disconnect 3.5mm headphones.
Expacted mucis to continue playing from headphones and return back to internal speakers

Fix issue with (not) auto-selecting 3.5mm headphone jack

---

modules/desktop/graphics/ewwbar/config/scripts/default.nix

_eww-bat_-script generates * unnecessary * log prints on NVIDIA Jetson Orin NX / AGX platfroms:
```
ghaf-host ewwbar-ctrl[xx]: cat: /sys/class/power_supply/BAT0/energy_now: No such file or directory
ghaf-host ewwbar-ctrl[xx]: cat: /sys/class/power_supply/BAT0/power_now: No such file or directory
ghaf-host ewwbar-ctrl[xx]: cat: /sys/class/power_supply/BAT0/capacity: No such file or directory
ghaf-host ewwbar-ctrl[xx]: cat: /sys/class/power_supply/BAT0/status: No such file or directory
ghaf-host ewwbar-ctrl[xx]: /nix/store/hash-eww-bat/bin/eww-bat: line 12: [: : integer expression expected
ghaf-host ewwbar-ctrl[xx]: (standard_in) 1: syntax error
ghaf-host ewwbar-ctrl[xx]: /nix/store/hash-eww-bat/bin/eww-bat: line 29: [: : integer expression expected
```
It seems like _eww-bat_-script prints …

ewwbar: initialize eww-bat script variables

---

modules/hardware/common/usb/vhotplug.nix
modules/reference/hardware/jetpack/nvidia-jetson-orin/jetson-orin.nix

Adding support for UE306 Ethernet Network Adapter which has vendor specific interface and does not have bInterfaceClass as Communications (2) and bInterfaceSubClass as "Ethernet Networking" (6) defined in "Configuration Descriptor" space.
**Closes: #6168**
i) Should fix Ethernet adapter not working in `Net-VM`

vhotplug: Add vendor specific ethernet adapter support

---

flake.lock
modules/desktop/graphics/ewwbar/config/scripts/default.nix
modules/desktop/graphics/ewwbar/config/variables/default.nix
modules/desktop/graphics/ewwbar/config/widgets/default.nix
modules/desktop/graphics/ewwbar/config/windows/default.nix
modules/desktop/graphics/labwc.config.nix
modules/desktop/graphics/labwc.nix
modules/desktop/graphics/styles/ewwbar-style.nix
modules/microvm/virtualization/microvm/guivm.nix
modules/reference/appvms/business.nix
modules/reference/desktop/applications.nix

1. **Added Window Manager Widget:**  
- Added a new **window manager widget** positioned at the bottom of the screen.  
- Combines elements of GNOME and macOS bottom bars.  
- Due to compositor/Wayland limitations, most icons are hardcoded.  
- **Note:** The Falcon AI (Alpaca) application icon is missing as it is not included in the current icon theme.  
- **Controls:**  
- Can be opened by moving the cursor to the bottom center of the screen, but only if at least one application window is open.  
- Clicking a window icon brings that window into focus.  
- Middle-clicking (scroll wheel click) a window icon closes the window (and any duplicates of it).  
- Window manager can be closed by hovering out of its' bounds.
- **Limitations:**  
- Windows in the bar are grouped by default, meaning …

Desktop: Add window manager widget, ghafpkgs bump

---

modules/desktop/graphics/ewwbar.nix
modules/desktop/graphics/ewwbar/config/scripts/default.nix
modules/desktop/graphics/ewwbar/config/variables/default.nix
modules/desktop/graphics/ewwbar/config/widgets/default.nix
modules/desktop/graphics/labwc.config.nix

1. **Added Per-VM Volume Mixer to Quick Settings Widget:**  
- VM volume sliders now appear beneath the system volume slider when clicking the button on its right side.  
- Sliders for closed VMs remain visible but become non-functional. 
- VM volume sliders affect only the respective VM and its children. 
2. **Fixed Default System Theme Not Applying Dark Mode On Fresh Installs**
- Verify VM volume sliders become appear as respective VMs with audio playback are opened.
- Verify VM volume sliders affect their respective VM volume as expected.
- Verify VM volume sliders become non-functional if the VM is closed completely and become functional again when VM is opened.
- Verify GTK dark theme is applied correctly system-wide on a fresh install of Ghaf.

Desktop: Taskbar per-VM volume mixer

---

modules/desktop/graphics/ewwbar.nix
modules/desktop/graphics/labwc.config.nix

1. **Fixed Launcher and Taskbar Services Not Starting After `wlr-randr` v0.5.0:**  
- `wlr-randr` v0.5.0 rejects standalone CLI arguments, preventing ghaf-launcher and ewwbar services from starting. 
- Forced taskbar and launcher services to use Bash as an interpreter in `Exec` commands to ensure proper execution when redirecting output.
- General note for devs: Systemd units **do not** use shell as an interpreter for `Exec` commands.
It's therefore recommended to always call a script with no arguments nor options, or use `bash -c` (as shown in this PR) to interpret commands properly.
- Verify fix works as expected, taskbar and ghaf launcher work at boot.
- Verify previously introduced fix for log flooding in headless mode still works and is effective.

Desktop: Fix desktop services not starting after wlr-randr v0.5.0

---

flake.lock

Jetpack-nixos repository contain a fix for AGX USB from USB.
1. Compile and flash AGX and NX QSPI
(1.5. AGX only: Verify AGX boots from EMMC)
2. Compile rootfs image and flash it to USB drive
3. Ghaf shoulf boot

bump: jetpack-nixos

---

modules/desktop/graphics/ewwbar/config/widgets/default.nix
modules/desktop/graphics/labwc.config.nix
packages/ghaf-powercontrol/default.nix

Bugfix for #1036 
1. **Kill User Processes on Logout**  
- Added a `logout` command to `ghaf-powercontrol`.  
- `logout` first terminates any Wayland compositor using `wayland-logout`, then kills user processes via `loginctl kill-user`.  
- `wayland-logout` is compositor-agnostic, making `ghaf-powercontrol` compatible with any compositor.  
- The logout button was removed from the lock screen due to slow execution when triggered from there.  
- Logout remains available via the taskbar power menu.  
- Observe the logs via **ghaf** account with the following: `journalctl -fe | grep --line-buffered --color=auto "changing state deactivating"`
- line containing `changing state deactivating → inactive` should appear before the login screen is visible
- Follow expected behavior and steps …

Desktop: Kill user processes on logout

---

modules/desktop/graphics/ewwbar.nix
modules/desktop/graphics/ewwbar/config/scripts/default.nix
modules/desktop/graphics/labwc.config.nix

1. **Persistent display configuration per user session:**  
- Saves a simple display configuration whenever the display setup changes.  
- Stores enabled/disabled state, position, transform, and scale for each display.  
- Default polling interval set to 1 minute.  
- If a saved configuration is present, it is applied automatically on user login.
Notes:
- In rare cases, the display config may be lost on logout or when the session ends.  
This can happen if the polling check happens within <1s time window as the session terminating.
- Login and adjust the display setup, preferably with 2 or more displays connected, focusing on these settings:
- Positioning
- Scaling
- Enabled/Disabled state (optional)
- Wait at least 1min before logging out or rebooting.
- Verify your display config is …

Desktop: Persistent display config for each user session

---

flake.lock
flake.nix
modules/common/logging/hw-mac-retrieve.nix
modules/common/services/default.nix
modules/common/services/github.nix
modules/microvm/virtualization/microvm/guivm.nix

MAC address shared with GUIVM.
Report page is added into settings of control panel.
Github configuration is added to submit a report. It has to be updated with valid info.
Bug report icon is not provided.

Ctrl panel bug report

---

modules/microvm/virtualization/microvm/microvm-host.nix
overlays/custom-packages/default.nix
overlays/custom-packages/libfm/default.nix
overlays/custom-packages/libfm/libfm-folder-reload.patch
packages/vinotify/default.nix
packages/vinotify/vinotify/requirements.txt
packages/vinotify/vinotify/setup.py
packages/vinotify/vinotify/vinotify/__init__.py
packages/vinotify/vinotify/vinotify/vinotify.py

This is a workaround for SSRCSP-5894. The problem occurs when the “Unsafe chrome-vm share” is open in the file manager and the user downloads a file in Chrome and saves it there. In this case the file manager does not display the downloaded file. It is very confusing since it looks as if the file has not been downloaded or has been saved to the wrong location.
The reason for this behavior is that the file manager on Linux uses the inotify API to watch for file changes. However, it turns out that virtiofs doesn’t propagate inotify events to the guest. There was an [attempt](https://lore.kernel.org/all/CAOQ4uxieK3KpY7pf0YTKcrNHW7rnTATTDZdK9L4Mqy32cDwV8w@mail.gmail.com/T/) to add support for this but as far as I understand it has not been merged into the mainline.
As a workaround, this PR …

Fix file manager refresh issue

---

modules/common/default.nix
modules/common/development/cuda.nix
modules/common/development/default.nix
modules/common/virtualization/podman.nix
targets/nvidia-jetson-orin/flake-module.nix

This PR is for CUDA 12.x supported nvidia containers.
Configuration options below:
- ghaf.development.cuda option is introduced for supported platforms. 
- ghaf.virtualization.podman.daemon is added for podman support with nvidia containers and docker compatibility options.
- ghaf.virtualization.docker.daemon is updated for docker support with nvidia containers 
Both docker and podman can coexist together as an option.
Planned to be removed or moved to work inside vm's later but this option is required for nvidia containers and ML software.
- **For Docker:**
- In your ghaf configuration (targets/nvidia-jetson-orin/flake-module.nix of your target platform) add `ghaf.virtualization.docker.daemon.enable=true;`
- rebuild your config
- For x86_64 platforms:
- Run `sudo docker run --rm …

Options for CUDA, podman and docker updated with nvidia-container support with cdi fix for docker

---

modules/microvm/appvm.nix
modules/microvm/flake-module.nix
modules/microvm/mem-manager.nix
targets/laptop/laptop-configuration-builder.nix

Add ballooning monitor and monitor all microvms that have a balloon size defined.
Enable balloon for app VMs, with half of their memory made dynamic.
microvm.nix PR: https://github.com/astro/microvm.nix/pull/324
ghaf-mem-manager PR: https://github.com/tiiuae/ghafpkgs/pull/19
Use device normally, preferably with high memory load.

Add ballooning monitor for VMs

---

flake.lock
modules/reference/services/nw-packet-forwarder/nw-packet-forwarder.nix

New version of network packet forwarder
- Chromecast functionality should work
- Log issue should not appear as described in SSRCSP-6211

bump: nw-packet-forwarder

---

nix/devshell.nix

This PR introduces low threshold access to automated (smoke) testing via ghaf dev shell script which 
- cd to Robot-Framework/test-suites in nix store
- launches the test run and passes the given arguments to Robot Framework
Prerequisites: https://github.com/tiiuae/ci-test-automation/pull/237 (merged) 
1. git clone https://github.com/tiiuae/ghaf.git
2. cd ghaf
3. nix develop .#smoke-tests
4. Read the instructions of the smoke-test command shown in terminal
5. Ensure target device is running and it has IP address
6. Start the smoke test, e.g.
```
robot-test -i ip_address -d Lenovo-X1 -p password
robot-test -i ip_address -d Orin-AGX -p password
robot-test -i ip_address -d Orin-NX -p password
```
It's also possible pass more arguments and run other than smoke-tests e.g.
`robot-test --ip …

Add generic script for smoke tests in dev shell

---

.gitignore
nix/checks.nix
nix/devshell.nix

These were somehow removed in a previous refactoring.

pre-push: fix the pre-push checks

---

modules/microvm/appvm.nix

Don't include tpm service and tools in VMs where it is not enabled.

Guard tpm-abrmd service

---

modules/common/systemd/hardened-configs/NetworkManager-dispatcher.nix
modules/common/systemd/hardened-configs/NetworkManager.nix
modules/common/systemd/hardened-configs/alloy.nix
modules/common/systemd/hardened-configs/dbus.nix
modules/common/systemd/hardened-configs/default.nix
modules/common/systemd/hardened-configs/dnsmasq.nix
modules/common/systemd/hardened-configs/enable-ksm.nix
modules/common/systemd/hardened-configs/firewall.nix
modules/common/systemd/hardened-configs/generate-shutdown-ramfs.nix
modules/common/systemd/hardened-configs/greetd.nix
modules/common/systemd/hardened-configs/kmod-static-nodes.nix
modules/common/systemd/hardened-configs/logrotate-checkconf.nix
modules/common/systemd/hardened-configs/logrotate.nix
modules/common/systemd/hardened-configs/nscd.nix
modules/common/systemd/hardened-configs/seatd.nix
modules/common/systemd/hardened-configs/systemd-journal-catalog-update.nix
modules/common/systemd/hardened-configs/systemd-journal-flush.nix
modules/common/systemd/hardened-configs/systemd-random-seed.nix
modules/common/systemd/hardened-configs/systemd-remount-fs.nix
modules/common/systemd/hardened-configs/systemd-rfkill.nix
modules/common/systemd/hardened-configs/systemd-tmpfiles-clean.nix
modules/common/systemd/hardened-configs/systemd-tmpfiles-setup-dev.nix
modules/common/systemd/hardened-configs/systemd-tmpfiles-setup.nix
modules/common/systemd/hardened-configs/systemd-udev-trigger.nix

Apply more restrictions on following Systemd services:
- dnsmasq
- firewall
- enable-ksm
- generate-shutdown-ramfs
- kmod-static-node
- NetworkManager-dispatcher
- logrotate-checkconf
- logrotate
- nscd
- seatd
- systemd-journal-catalog-update
- systemd-journal-flush
- systemd-random-seed
- systemd-remount-fs
- systemd-rfkill
- systemd-tmpfiles-clean
- systemd-tmpfiles-setup-dev
- systemd-tmpfiles-setup
- systemd-udev-trigger
- NetworkManager
Removed some disabled services
Cleanup of `dbus` and `greetd`.
- All
- Test system functionality

Restrict systemd services

---

modules/profiles/graphics.nix
modules/reference/profiles/mvp-user-trial-extras.nix
modules/reference/profiles/mvp-user-trial.nix
targets/nvidia-jetson-orin/flake-module.nix

1. **Add Idle Management Config Option to options.ghaf.profiles.graphics:**
- Defaults to true to enable swayidle idle management
- [-] Change requires full re-installation
- Allows choosing whether to enable or disable idle management for particular targets

feat(graphics): add idle management configuration option

---

flake.lock
modules/common/systemd/hardened-configs/bluetooth.nix
overlays/README.md
overlays/cross-compilation/default.nix
overlays/cross-compilation/libqmi/default.nix
overlays/custom-packages/labwc/labwc-colored-borders.patch
overlays/custom-packages/papirus-icon-theme/default.nix
overlays/flake-module.nix
targets/nvidia-jetson-orin/cross-compilation.nix

quite a lot of churn
- flake bump so all

bump: standard bump

---

flake.lock
modules/reference/hardware/jetpack/0001-ARM-SMMU-drivers-return-always-true-for-IOMMU_CAP_CA.patch
modules/reference/hardware/jetpack/agx-netvm-wlan-pci-passthrough.nix
modules/reference/hardware/jetpack/nx-netvm-ethernet-pci-passthrough.nix
targets/nvidia-jetson-orin/flake-module.nix

Nvidia Orin NX/AGX currently uses kernel from Nvidia Jetson 36.4.3 BSP. Jetson 36.4.3 BSP support "bring yout own kernel"-feature. In other words it has a support(/guide) for upstream kernel. Pull request introduces following changes:
- Orin NX: Making Xavier NX devkit as a default carrier board.
- Patch for kernel vfio-pci driver (comment in patch).
- _nix flake update jetpack-nixos_:  Contains updates, which relates to kernel 6.6
No specific steps, but everything should work as it has been worked. Only visible change should be host kernel and it should be 6.6.75.

Orin NX/AGX: Switch from nvidia bsp 5.15 kernel to upstream 6.6

---

modules/desktop/graphics/default.nix
modules/desktop/graphics/power-manager.nix
packages/ghaf-powercontrol/package.nix
targets/nvidia-jetson-orin/flake-module.nix

This PR introduces a new `power-manager` module to override default logind power management and refactors `ghaf-powercontrol` for improved functionality and robustness.
**1. Add power-manager module:**
- Implement suspend signal interception and handling.
- Implement shutdown/reboot signal interception and handling.
- Suspend and shutdown/reboot listener services can be enabled individually through nix options.
- Use `ghaf-powercontrol` to override power state management.
The power-manager module provides better control over system power management by intercepting logind signals and using `ghaf-powercontrol` for custom handling of suspend, shutdown, and reboot operations.
With this module enabled, the user should be able to simply call `systemctl suspend/poweroff/reboot`, regardless of …

feat: power manager module, refactor ghaf-powercontrol

---

modules/hardware/common/usb/vhotplug.nix
modules/reference/hardware/dell-latitude/definitions/dell-latitude-7230.nix
modules/reference/hardware/dell-latitude/definitions/dell-latitude-7330-71.nix
modules/reference/hardware/dell-latitude/definitions/dell-latitude-7330-72.nix
modules/reference/hardware/lenovo-x1/definitions/x1-gen10.nix
modules/reference/hardware/lenovo-x1/definitions/x1-gen11.nix

We need to pass usb class to vhotplug and opregion to gui-vm so that it can detect type-c display.
As we are doing GPU pasthrough to `gui-vm` qemu we need pass video BIOS table (VBT) info from UEFI to
`gui-vm` qemu for which qemu need to access `x-igd-opregion` memory region, hence enabling the same.
More details https://github.com/qemu/qemu/blob/master/docs/igd-assign.txt
1. Type C display on Lenovo X1 and Dell Latitude should work with this change.

vhotplug: Enable type-c display for x86_64 variants

---

modules/common/common.nix

Add network, audio, and gpu pci devices to common config so they can be queried in VM namespaces.
No testing in Ghaf required, used downstream

Refactor: Add PCI devices to common

---

docs/src/SUMMARY.md
docs/src/ref_impl/cosmic.md
docs/src/ref_impl/reference_implementations.md
modules/common/services/disks.nix
modules/desktop/graphics/cosmic/config/cosmic-config-to-yaml.sh
modules/desktop/graphics/cosmic/config/cosmic-config.nix
modules/desktop/graphics/cosmic/config/cosmic-config.yaml
modules/desktop/graphics/cosmic/default.nix
modules/desktop/graphics/default.nix
modules/desktop/graphics/fonts.nix
modules/desktop/graphics/labwc.config.nix
modules/desktop/graphics/labwc.nix
modules/microvm/common/waypipe.nix
modules/microvm/host/shared-mem.nix
modules/microvm/sysvms/guivm.nix
modules/profiles/graphics.nix
modules/reference/appvms/business.nix
modules/reference/desktop/applications.nix
overlays/custom-packages/cosmic/cosmic-applets/default.nix
overlays/custom-packages/cosmic/cosmic-greeter/default.nix
overlays/custom-packages/cosmic/cosmic-session/default.nix
overlays/custom-packages/cosmic/cosmic-settings/default.nix
overlays/custom-packages/default.nix
packages/ghaf-powercontrol/package.nix
targets/nvidia-jetson-orin/flake-module.nix

This PR introduces COSMIC as a new desktop environment option for Ghaf, replacing LabWC if enabled.
Notable changes:
1. **Integration of COSMIC DE (Alpha 6)** using NixOS options (available in `nixpkgs` as of April 2025).
2. **Dedicated COSMIC Nix configuration** in `cosmic.nix`:
- Disables certain default features for compatibility with Ghaf.
- Overrides first-party COSMIC packages to remove unsupported features in Ghaf.
- Uses `swayidle` instead of COSMIC's idle manager.
3. **Ghaf-COSMIC system-wide desktop configuration** in `cosmic.config.yaml`:
- `cosmic.config.yaml` is expanded into `/run/current-system/sw/share/cosmic` by `ghaf-cosmic-config` package.
- Helper script `cosmic-config-to-yaml.sh` available to convert local `.config/cosmic` into YAML format for easier maintenance.
- …

desktop: add COSMIC Epoch DE

---

flake.lock

Fixes firmware build issue for NXP iMX8MP-evk platform.
1. Build for NXP iMX8MP-evk.

bump nixos-hardware

---

flake.lock

Fixes native build issue for imx8mp-evk
1. Do native and cross build for NXP imx8mp platform.

bump: nixos-hardware

---

overlays/custom-packages/qemu/default.nix
overlays/custom-packages/qemu/usb-host-enable-autoscan-for-bus-addr.patch
packages/python-packages/vhotplug/package.nix

This fixes an issue with hot-plugging that can potentially cause a race condition and system crash.
When the system is booted from a USB SSD drive, it remains connected to the host because vhotplug detects it as a boot device and doesn't pass it to the GUIVM. When a second USB drive is connected, it gets passed to the GUIVM. If the user then unplugs it, the vhotplug service tries to remove it from the GUIVM but at the same time QEMU tries to find the device by VID/PID and reconnect it. If both drives are the same model, QEMU finds the boot drive and connect it to the GUIVM causing a system crash.
This issue is difficult to reproduce because in most cases the vhotplug service removes the drive from the GUIVM faster than QEMU can detect and reconnect it. However, Samuli managed to …

Update vhotplug to fix issues with multiple devices with the same VID/PID

---

modules/desktop/intel-gpu/default.nix
modules/reference/programs/firefox.nix

As we are supporting newer generations of Intel platforms, we no longer need i965 configuration. Even if we forcefully try to use i965 configuration hardware codecs doesn't enumerate, verified using vainfo command.
1. vainfo works
2.  glmark2-wayland use Render/3D engine.
3.  Video playback should use Video engine.

intel-gpu: Cleanup the intel setup configuration

---

modules/reference/desktop/applications.nix
modules/reference/services/ollama/ollama.nix
overlays/custom-packages/alpaca/default.nix
overlays/custom-packages/default.nix
packages/own-pkgs-overlay.nix
packages/pkgs-by-name/falcon-launcher/package.nix

1. **Fix Alpaca not launching bug by downgrading Alpaca 5.3.0 -> 5.2.0**
- Alpaca was recently upgraded to 5.3.0 via a flake bump
- 5.3.0 has a known issue ([ref1](https://github.com/Jeffser/Alpaca/issues/703) [ref2](https://github.com/Jeffser/Alpaca/issues/626)), where the app might not start or start with functionality missing.
- Possible solutions are upgrading to 6.0.0+ or downgrading back to 5.2.0
See notes below for more info why downgrade was preferred.
2. **Rework Falcon AI launcher package behavior:**
- Introduced new `falcon-launcher` package
- Removed obsolete `load-falcon` package
- `falcon-launcher` is responsible for downloading the Falcon LLM and/or launching Alpaca ("Falcon AI" app)
- Opening "Falcon AI" from the App Library results in the following:
- If Falcon LLM is not …

bugfix: fix Falcon AI app not starting, rework package

---

modules/hardware/common/devices.nix
modules/hardware/common/input.nix
modules/reference/hardware/alienware/alienware-m18.nix
modules/reference/hardware/dell-latitude/definitions/dell-latitude-7230.nix
modules/reference/hardware/dell-latitude/definitions/dell-latitude-7330-71.nix
modules/reference/hardware/dell-latitude/definitions/dell-latitude-7330-72.nix
modules/reference/hardware/demo-tower/demo-tower.nix
modules/reference/hardware/lenovo-x1/definitions/x1-gen10.nix
modules/reference/hardware/lenovo-x1/definitions/x1-gen11.nix
modules/reference/hardware/lenovo-x1/definitions/x1-gen12.nix
packages/pkgs-by-name/hardware-scan/hardware-scan.sh

Remove hardcoded input devices from hardware definition. The input devices should be handled correctly by vhotplug.
This should simplify the hardware definition, and remove the need to specify multiple input devices.
1. For all reference laptop hardware, verify that all input devices (touchpad, trackpoint, touchscreen, and keyboard) work as before
2. (optional) Check that input devices are picked up by vhotplug (`journalctl -b0 -u vhotplug.service` on the host)

Input devices: remove hardcoded evdevs

---

modules/microvm/common/vm-networking.nix

Add net-vm as ids-vm gateway. Fixes SSRCSP-6525.
1. Build and run .#lenovo-x1-extras-debug, observe network available in all VMs

Fix: ids-vm networking

---

targets/laptop/flake-module.nix

This change enables a target for the cosmic desktop. Based on the x1 hardware just for quick evaluations.
1. ...

cosmic: Add an x1 target to trial cosmic desktop

---

modules/microvm/common/xdghandlers.nix
modules/microvm/common/xdgitems.nix
modules/reference/desktop/applications.nix

1. **Removed Sticky Notes From COSMIC DE:**
- Sticky notes app behaves inconsistently in Cosmic, e.g. failing to launch due to segfaults
- Tried some other sticky notes apps on Cosmic, but couldn't find one that runs nicely
2. **Switched Default Image Viewer [Pqiv](https://github.com/phillipberndt/pqiv) -> [Oculante](https://github.com/woelper/oculante):**
- pqiv seems to prefer X11 over Wayland, which causes some rendering issues in Cosmic (and possibly labwc)
- Switched to Oculante, a fast image viewer written in Rust with better Wayland support
- Added more default image mimetypes [supported by Oculante](https://github.com/woelper/oculante/blob/master/res/oculante.desktop)
1. Save several types of images in some Shares directory or otherwise
- recommend previously supported types like …

refactor(desktop): remove sticky notes from cosmic, switch to oculante img viewer

---

modules/development/debug-tools.nix
modules/development/dt-gui.nix

When packages were moved to dt-gui. they were left in debug-tools. cleanup for those.
Add nvtop package to the system. htop for gpu.
1. ...

cleanup: move packages to dt-gui

---

modules/desktop/graphics/labwc.config.nix

1. **Add /run/current-system/sw/bin to nwg-drawer PATH:**
- This change allows nwg-drawer to properly run applications via their .desktop files even if the full path to the binary is not provided in Exec=
- With this change, if a particular package, added via `environment.systemPackages` has its own .desktop entry, nwg-drawer will be able to launch it without issues.
- The reason this change is needed is because we start nwg-drawer as a user service. By default, it seems to inherit the service manager's PATH, which does not include /run/current-system/sw/bin.  
2. **Minor adjustment to default gtk settings files, removing unsupported properties**
Testing is not necessary, as this change should not affect existing functionality and it doesn't add anything new yet.
That being said, a sanity …

fix(desktop): adjust ghaf-launcher env vars

---

modules/desktop/graphics/login-manager.nix
modules/desktop/nvidia-gpu/default.nix
modules/hardware/common/usb/vhotplug.nix
modules/reference/hardware/flake-module.nix
modules/reference/hardware/tower-5080/extra-config.nix
modules/reference/hardware/tower-5080/tower-5080.nix
targets/laptop/flake-module.nix

Add new demo tower hardware and target with Nvidia RTX 5080. Tested with FMO, all functionality appears to work with exception of boot with cables in nvidia card. To be updated.
1. No testing required.

New demo tower hardware with RTX 5080

---

modules/desktop/graphics/cosmic/config/cosmic-config.nix
modules/desktop/graphics/cosmic/default.nix
modules/microvm/sysvms/guivm.nix
overlays/custom-packages/cosmic/cosmic-comp/0001-Add-security-context-indicator.patch
overlays/custom-packages/cosmic/cosmic-comp/default.nix
overlays/custom-packages/default.nix

This adds an initial version of a patch to the COSMIC compositor that enables setting different window frame colors based on the security context attached to the Wayland connection. This allows applications running in different AppVMs to have different window frame colors similar to how it works in Labwc.
1. Build a Lenovo X1 image with COSMIC enabled (`lenovo-x1-gen11-cosmic-debug`).
2. Run different application and make sure they have correct window frame colors.

Add security context indicator to COSMIC

---

flake.lock
flake.nix
modules/reference/services/wireguard-gui/wireguard-gui.nix

* Save conf files to WireGuard config path
* Remove button is fixed
* Export config files functionality implementation
* Better error handling
* `appuser` can only access the conf files
* Fix public key handling
* CLI args for config files' dir and ownership
1. Generate the base configuration by clicking the `Generate Configs` button.
2. Edit parameters (PublicKey, AllowedIps, Address,etc.) to pass same [test procedure](https://github.com/tiiuae/ghaf/pull/1129)
3. Export the configuration by clicking the `Export` button.  
4. Note that the configuration file can only be exported to under `/home` directory. (for example: /home/ghaf/)
5. Verify the ownership status of the exported configuration file; it should match the owner of the parent folder.
6. Attempt to remove the configuration by …

bump:wireguard reactivating buttons and improvements

---

modules/microvm/sysvms/idsvm/mitmproxy/default.nix
modules/reference/appvms/google-chrome.nix

MitmWebUI was updated by the mitmproxy team, introducing a password requirement for login that was previously unnecessary. 
https://github.com/mitmproxy/mitmproxy/issues/7551
* `web_password` parameter has been passed through `webUIPswd` mitmproxy module option.
SSRCSP-6559
1. Click MitmWebUI icon
2. Logs should appear when the network traffic is active

fix: add configurable password for mitmweb UI

---

flake.lock
modules/reference/hardware/jetpack/agx-netvm-wlan-pci-passthrough.nix
modules/reference/hardware/jetpack/nvidia-jetson-orin/jetson-orin.nix
modules/reference/hardware/jetpack/nx-netvm-ethernet-pci-passthrough.nix
nix/devshell.nix
targets/nvidia-jetson-orin/flake-module.nix

Jetpack-nixos (tiiuae fork) supports kernel version select between "bsp-default" and "upstream-6-6". Upstream kernel only works with Jetson 36.X BSP. Commit also updates Jetpack-nixos flake lock.
NVIDIA Orin NX/AGX keeps using upstream 6.6. kernel.
Define kernel version option. For example 
`kernelVersion = "upstream-6-6"`
or 
`kernelVersion = "bsp-default"`
or
If not explicitly defined then "bsp-default" is selected.
If `kernelVersion = "upstream-6-6"` 
-> `uname -a` should print `Linux ghaf-host 6.6.75 ...`
if `kernelVersion = "bsp-default"` 
-> `uname -a` should print `Linux ghaf-host 5.15.148 ...`
if kernelVersion is NOT defined
-> `uname -a` should print `Linux ghaf-host 5.15.148 ...`

feat: Kernel version option for NVIDIA Orin NX/AGX targets

---

modules/common/systemd/hardened-configs/greetd.nix

Sticky Notes was attempting to execute gjs-console from memory, but this action was denied due to memory execution restrictions inherited from the parent process (greetd). This resulted in a segmentation fault.
This commit removes the restrictive setting, allowing gjs-console to execute as expected and resolving the crash.
Tested on top of pr #1206.
1. Boot into cosmic desktop and run sticky note application from cli.

Fix Sticky Notes segfault in Cosmic

---

modules/development/debug-tools.nix
modules/hardware/common/default.nix
modules/hardware/common/usb/external-devices.nix
modules/reference/hardware/lenovo-x1/definitions/x1-gen10.nix
modules/reference/hardware/lenovo-x1/definitions/x1-gen11.nix
modules/reference/hardware/lenovo-x1/definitions/x1-gen12.nix
modules/reference/hardware/lenovo-x1/definitions/x1-gen13.nix
templates/boilerplate/modules/hardware/default.nix

- Created a common list of external USB devices for x86_64 architecture, which can be assigned to any VM as required.
- Added support for a few Xbox controllers.
1. ..

usb: Added a common stub for external usb devices

---

.gitignore
modules/hardware/common/usb/external-devices.nix

Add the usb passthrough for the crazyflie and the crazyflie specific network dongle.
1. ...

crazyflie: add the usb passthrough

---

modules/hardware/common/usb/vhotplug.nix

This patch will add support to the vhotplug module, allowing it to prepend rules. This feature is useful when the order of USB device detection is important for additional VMs.
1. Detection of USB devices should work fine.

vhotplug: Add option to prepend rules

---

modules/givc/guivm.nix
modules/hardware/common/usb/vhotplug.nix
modules/microvm/appvm.nix
modules/microvm/host/boot.nix
modules/microvm/host/microvm-host.nix
modules/microvm/sysvms/audiovm.nix
modules/microvm/sysvms/guivm.nix
modules/microvm/sysvms/netvm.nix
modules/reference/appvms/gala.nix
modules/reference/appvms/zathura.nix
packages/own-pkgs-overlay.nix
packages/pkgs-by-name/wait-for-unit/package.nix

Add custom microvm boot-order for ghaf to delay appvms startup to reserve resources for system-vms during boot.
This custom boot sequence is only enabled iff the gui-vm is enabled.
Features:
- remove the previous sleep for appvms by adding a wait-unit command to monitor the status of a service or target within a VM
- disable microvms autostart feature for net-vm, gui-vm, audio-vm, and app-vms, if enabled
- disable automatic restart of microvm@<vm> service. This allows to shutdown a machine internally (e.g., poweroff.target)
Appvms now have a boot priority flag that determines when they start booting; high, medium, low. Default is **medium**, with the following boot triggers:
| Trigger | Default | Appvm Priority | 
| ------- | ------- | ------- | 
| local-fs.target (host) | System VMs | …

Microvm boot order

---

modules/desktop/graphics/cosmic/config/cosmic-config.nix
modules/desktop/graphics/cosmic/config/cosmic-config.yaml
modules/desktop/graphics/cosmic/default.nix

Minor bugfix to Cosmic config to allow adjusting backlight brightness before user session is started.
This functionality might be useful in cases where previous brightness settings cannot be restored by `systemd-backlight@` service, and the brightness ends up being too low or even completely off in login screen.
1. Boot into Ghaf but do not log in
2. Try changing backlight brightness via the F5/F6 keyboard shortcuts
3. Log in
4. Try changing backlight brightness via the F5/F6 keyboard shortcuts, there should be no regression

bugfix: adjust backlight brightness before login

---

modules/common/logging/client.nix
modules/common/logging/server.nix
modules/common/security/audit/default.nix
modules/common/security/audit/rules/common.nix
modules/common/security/audit/rules/guest.nix
modules/common/security/audit/rules/host.nix
modules/common/security/default.nix
modules/common/services/fprint.nix
modules/common/services/wifi.nix
modules/common/systemd/base.nix
modules/development/debug-tools.nix
modules/givc/adminvm.nix
modules/givc/appvm.nix
modules/givc/audiovm.nix
modules/givc/guivm.nix
modules/givc/host.nix
modules/givc/netvm.nix
modules/microvm/appvm.nix
modules/microvm/host/microvm-host.nix
modules/microvm/modules.nix
modules/microvm/sysvms/adminvm.nix
modules/microvm/sysvms/audiovm.nix
modules/microvm/sysvms/guivm.nix
modules/microvm/sysvms/netvm.nix
modules/reference/profiles/mvp-user-trial-extras.nix
modules/reference/profiles/mvp-user-trial.nix
packages/own-pkgs-overlay.nix
packages/pkgs-by-name/audit-rules/package.nix
packages/pkgs-by-name/audit-rules/process-audit-rules.sh

- Add a module for audit configuration, STIG/OSPP profiles for auditing, and reduce SWTPM logging.
- Disable audit for MVP and added to extras, as the audit logs can be burdening during feature development.  
- Add package for automatic conversion of upstream audit rules (these are not automatically applied)
Future improvements:
- finetuning of the auditd
- finetuning of audit rules 
- adding host/guest specific audit rules
- handle a few nix specific corner cases (e.g., wrappers) for full compliance
1. Build MVP, verify that long SWTPM and audit logs are gone
2. Re-build with audit in MVP profile enabled (or use extras)
3. Check `systemctl status auditd` and `systemctl status audit`, and `auditctl -l`
4. Check that audit logs are present `journalctl -b0 -t audit` in host and guests
5. …

Improve audit

---

modules/common/services/bluetooth.nix
modules/common/services/default.nix
modules/common/services/xpadneo.nix
modules/common/systemd/hardened-configs/bluetooth.nix
modules/microvm/modules.nix

This patch includes
- Adds ghaf.services.xpadneo.enable option
- Loads hid-xpadneo and uhid kernel modules
- Adds udev rule for uhid under Bluetooth user
- Requires ghaf Bluetooth service to be enabled
- By default this feature is **disabled**
1. User need Xbox Controller hardware to test this feature.
2. By default feature is **disabled**, however if user wants to test it, please enable it [here](https://github.com/tiiuae/ghaf/pull/1298/files#diff-65ea1636bbde1e7b83e6f1996a5fe90d832209b27477dc2cd6faced679b07731R93)

feat(xpadneo): Add module to enable wireless Xbox controller support

---

modules/givc/guivm.nix
modules/microvm/appvm.nix
modules/microvm/modules.nix
targets/vm/flake-module.nix

This PR contains some adjustments that were made to the `vm` target while working on the TPM storage feature. We are posting them in a PR in case there is interest to merge parts into upstream. Changes include:
- added a non-graphical qemu target for testing Ghaf on machines without a display output
- increased the resources allocated to qemu host
- set the `useNixStoreImage` option, which disables mounting the top-level nix store inside the qemu ghaf-host with an overlay. This was causing issues because it is then mounted the same way inside the microvm. A temporary disk image is now created when starting the ghaf-host with a copy of the nix store.
- enabled a few reference VMs for testing
- a VMware disk image can also be created instead of qemu (useful on MacOS)
We found this setup …

Changes to the VM target

---

modules/reference/hardware/dell-latitude/definitions/dell-latitude-7230.nix
modules/reference/hardware/dell-latitude/definitions/dell-latitude-7330.nix
modules/reference/hardware/lenovo-x1/definitions/x1-2-in-1-gen-9.nix
modules/reference/hardware/lenovo-x1/definitions/x1-gen10.nix
modules/reference/hardware/lenovo-x1/definitions/x1-gen11.nix
modules/reference/hardware/lenovo-x1/definitions/x1-gen12.nix
modules/reference/hardware/lenovo-x1/definitions/x1-gen13.nix

x-igd-opregion is now enabled by default in Qemu. The Type-C display now works without the explicit Qemu opregion argument, so the extra device configuration is no longer needed.
More details in https://github.com/qemu/qemu/commit/16cbb43302a228f804c067992f6f61787934f3e9
1. Type-C and HDMI connections should function seamlessly with external displays for all applicable targets.

display: Drop x-igd-opregion device arg

---

modules/common/users/desktop.nix

Fixes issue SSRCSP-6858
setup-ghaf-user service status is reported "failed" when it is stopped by setup-test-user.
This commit marks SIGTERM as normal exit.
1. Please see Jira SSRCSP-6858

Setup normal exit for setup-ghaf-user service

---

modules/microvm/sysvms/guivm.nix

use the latest kernel to properly sleep and resume functionality.
Fixes: SSRCSP-6869
1. ...

gui-vm: kernel use latest

---

REUSE.toml
overlays/custom-packages/default.nix
overlays/custom-packages/intel-gpu-tools/default.nix
overlays/custom-packages/intel-gpu-tools/feat-dynamically-detect-iGPU-PCI-address-at-runtime.patch

Adds an overlay to intel-gpu-tools that applies 0001-feat-dynamically-detect-iGPU-PCI-address-at-runtime.patch to enable runtime detection of the iGPU PCI address.
This patch can be treated as **workaround** until we have proper way of PCI address assigned in VMs.
1. It should fix below error of `intel_gpu_top` not running with latest Kernel `6.15.8` for `gui-vm`
```
[root@gui-vm:~]# intel_gpu_top 
Failed to detect engines! (No such file or directory)
(Kernel 4.16 or newer is required for i915 PMU support.)
```

overlays: intel-gpu-tools: Dynamic iGPU detection

---

modules/common/common.nix
modules/common/services/default.nix
modules/common/services/locale.nix
modules/microvm/sysvms/guivm.nix

1. **Add a simple service to propagate gui-vm locale changes to givc, only if givc is available, similar to #1252** 
- This change will allow Cosmic Settings app "Region and Language" page to work as it should in Ghaf, when the next Cosmic Epoch release is out
~givc `set-locale` command doesn't support variable assignment (e.g. `LANG=en_US.UTF-8`)
Due to this, changing the locale also implicitly changes the LANG in [givc under the hood](https://github.com/tiiuae/ghaf-givc/blob/main/modules/pkgs/localelistener/controller.go#L42). This may need to be adjusted in givc at some point down the line.~
givc now supports locale macro assignments with [PR 130](https://github.com/tiiuae/ghaf-givc/pull/130)
**The "Time & Language > Region & Language" cosmic settings page will not work properly until …

feat(cosmic): propagate locale changes

---

modules/desktop/graphics/cosmic/config/cosmic-config.nix
modules/desktop/graphics/cosmic/default.nix

1. **Add temporary watchdog service to monitor known problematic high-cpu usage processes:**
- The service runs on session start for 5 minutes
- If an offending process is found to exceed the maximum threshold CPU usage, all offending processes are killed
- The killed processes are automatically restarted by `cosmic-session`
- Known offenders: `cosmic-applet-audio`, `cosmic-osd`
- ref. https://github.com/pop-os/cosmic-osd/issues/70
**NOTE:** Perform the following test at least 3 times to confirm the behavior is consistent
1. Install Ghaf from scratch (this bug appears mostly on fresh installs)
2. Boot and log into the system
3. Observe `htop` and `journalctl --user-unit=cosmic-cpu-watchdog.service`
- `cosmic-applet-audio` and `cosmic-osd` should appear in htop consuming more than 80% of …

bugfix: add temporary watchdog service for high-CPU processes

---

modules/common/common.nix
modules/common/firewall/firewall.nix
modules/common/firewall/kernel-modules.nix
modules/common/services/wifi.nix
modules/microvm/common/vm-networking.nix
modules/microvm/host/networking.nix
modules/microvm/sysvms/idsvm/mitmproxy/default.nix
modules/reference/services/chromecast/chromecast-config.nix
modules/reference/services/dendrite-pinecone/dendrite-config.nix

Enable static ARP in the internal network, to prevent ARP spoofing and
subsequent MITM attacks.
- additional firewall (ebtables) rules on internal bridge, filtering out
arp traffic; and required kernel modules
- sysctl settings to configure arp behaviour on bridge and vm internal
interfaces
- splitting host networking configuration, allowing to later remove host
networking without removing the internal bridge
- adding static entries for all known hosts
- adding flag for external host networking, allowing to not activate
interfaces on the host by default and disable internal host nat
1. Confirm ARP spoofing works on current main
2. (optional) run `sudo arp net-vm` in chrome-vm before and during spoofing to see MAC address change
3. Apply patch and confirm ARP spoofing does not work …

ARP protection

---

modules/common/security/audit/default.nix
modules/common/security/audit/rules/common.nix
modules/common/security/audit/rules/host.nix
modules/reference/appvms/zathura.nix
modules/reference/personalize/authorizedSshKeys.nix

Enhances NixOS audit coverage, aligns with Anduril NixOS STIG guidance, removes overlapping/erroring rules, and adds opt-in verbose toggles.
- Nix-specific coverage
- Exec rules for `nix-daemon` and `nix` (execve/execveat).
- Path watches for `nix`, `nix-store`, `nix-shell`, `nix-build`, `nix-collect-garbage`, and `nixos-rebuild`.
- Watches for `/etc/nix`, `/etc/nixos`, and `nix-daemon` unit/socket paths.
- Host-level watches for Nix profiles, DB/state, GC lock, and system generation symlinks.
- STIG alignment
- Incorporated rules from [https://stigviewer.com/stigs/anduril_nixos](https://stigviewer.com/stigs/anduril_nixos?utm_source=chatgpt.com). Trimmed duplicates/overlaps
- Verbose options
- `ghaf.security.audit.enableVerboseCommon`
- `ghaf.security.audit.enableVerboseOspp`
- Write rate …

audit: add Nix-specific rules

---

docs/src/content/docs/index.mdx

When following the "Getting Started" on the project home page, the command fails to a missing attribute. Update the template name to a valid template target.
1. Navigate to https://ghaf.tii.ae/ - try running the command on Getting Started-box. Fails to 
`error: flake 'github:tiiuae/ghaf' does not provide attribute 'templates.boilerplate' or 'boilerplate'`
2. Apply the patch, rebuild the docs: `nix build .#doc`
3. Open the index.html on the updated docs and run the (updated) command -> initializes a flake from the template.

docs: fix the flake init template attribute

---

docs/src/content/docs/ghaf/releases/ghaf-25.09.1.mdx
flake.lock
flake.nix
modules/development/debug-tools.nix
overlays/README.md
packages/pkgs-by-name/vsockproxy/package.nix

qemu 10.1 is merged to the upstrem nixos.
1. ...

bump: drop the qemu 10.1 carry patches

---

modules/desktop/graphics/boot.nix
modules/microvm/host/microvm-host.nix
modules/microvm/sysvms/guivm.nix
modules/reference/hardware/system76/definitions/system76-darp11-b.nix

1. Graphical boot config overhaul:
- Added more nix options to configure Ghaf graphical boot: `theme, renderer, splashDelay, deviceTimeout, debug`
2. Enabled graphical boot on guivm
- The splash screen should show up as soon as the gpu is attached and initialized on guivm
3. Fixed black screen boot on system76 darp11-b
1. Shutdown the target system after deploying this patch
2. Power on the system
3. Observe and verify the following boot process:
- Firmware/NixOS generation selection
- Host boot splash screen with Ghaf logo
- Black screen (guivm started, gpu is being initialized)
- Guivm boot splash screen with Ghaf logo
- Black screen (greetd starting)
- Login screen
4. Verify boot process is fixed on system76 darp11-b

feat(boot): enable graphical boot on guivm, fix darp11 graphical boot

---

flake.lock
flake.nix
modules/hardware/common/usb/vhotplug.nix
modules/reference/hardware/jetpack/nvidia-jetson-orin/jetson-orin.nix

This updates vhotplug to the version with the new config format, which allows selecting multiple VMs for a single device.
It also adds support for the external API over VSOCK, which is required for the frontend GUI app.
No new functionality is added in this PR, but it is a prerequisite for the PR with the USB management app from Ganga.
Overall USB hotplug testing is required to make sure this doesn’t introduce any regressions.

Update vhotplug to support new config format and external API

---

modules/common/firewall/attack-mitigation.nix
modules/common/firewall/default.nix
modules/common/firewall/firewall.nix
modules/common/security/default.nix
modules/common/security/fail2ban.nix
modules/common/security/ssh-tarpit/default.nix
modules/development/ssh.nix
modules/microvm/appvm.nix
modules/microvm/sysvms/adminvm.nix
modules/microvm/sysvms/audiovm.nix
modules/microvm/sysvms/guivm.nix
modules/microvm/sysvms/netvm.nix
tests/firewall/default.nix

* Fail2Ban is enabled on all VMs to protect against SSH brute-force attacks. 
* A custom jail is configured to redirect SSH connections from banned IPs to the ssh-tarpit server on the net-vm, slowing down attackers by deliberately delaying their connections. 
* On all other VMs, packets from banned IPs are dropped immediately.
* VMs allow a maximum of 5 ICMP request packets (ping)  in a single burst per minute for each IP address.
* SSH sync flood protection has been activated for every VM. (  maximum 30 new ssh connection requests/minute)
**Scenario - 1 (External Network - Netvm)** 
1. Regression test for network-related services
2. Check endless-go in net-vm whether it is activated with `systemctl status endless-go`
3. Attempt to establish an SSH connection, but enter the password …

Enabling fail2ban module

---

flake.lock

Fix VM controls in ctrl-panel to allow starting a VM after it has been shut down.
Also fix issue, where VM/service controls became insensitive in some scenarios.
https://github.com/tiiuae/ghaf-givc/pull/205
https://github.com/tiiuae/ghaf-ctrl-panel/pull/104
https://jira.tii.ae/browse/SSRCSP-7215
1. open ghaf control panel
2. choose an app vm from left hand side tree, for example chrome-vm
3. choose stop from VM controls drop down
4. wait for the status to update to "stopped"
5. choose start from VM controls drop down
6. wait for the status to update to "running"
7. verify that app (for example, chrome) can be started from menu

Fix ctrl-panel VM starting

---

modules/common/logging/server.nix
modules/microvm/sysvms/adminvm.nix

Enable mTLS support for the Alloy log forwarder when sending logs to Loki. Improvements can be listed as follows:
- Supports per-target mTLS profiles (custom CA, SNI, min TLS version, and client cert/key), enabling easy personalization for different SIEMs or gateways with their own PKI and policy requirements.
- Allows using a custom CA (internal PKI), which is typical in SIEM environments and zero-trust networks.
- Client identity available (mTLS-ready).
- Transport is TLS-encrypted with explicit policy (no silent downgrade).
1. Check if the logs are being uploaded to remote server (e.g., Grafana)
2. On `admin-vm`, run the following command to dump a live graph of all running Alloy components: `curl -s http://127.0.0.1:12345/api/v0/web/components`
3. Look for the `loki.write` block …

Add tls_config support to alloy server

---

modules/common/common.nix
modules/common/services/audio.nix
modules/common/services/power.nix

1. **Added pipewire state dir to persistent storage:**
- Allows audio state to be saved between reboots
2. **Added gracefulShutdown option to Ghaf common options:**
- Enabled by default
- Only affects system-vms
- If enabled, tells power-manager module to handle shutdown gracefully instead of using microvm's built-in shutdown logic
3. **Power manager module changes:**
- Host power manager module config now includes overriding microvm's default `ExecStop` behavior for system VMs
- With this change, when the host is shutting down or a system-vm shutdown is requested, the host will start the respective vm's poweroff.target, which, in turn, will allow the VM to gracefully shutdown
- The host will wait until the VM process is fully stopped before proceeding with shutdown, or send SIGTERM to …

power: allow system vms to shutdown gracefully, preserve audio on shutdown

---

modules/common/logging/client.nix
modules/common/logging/server.nix
modules/microvm/sysvms/adminvm.nix

- Switch Alloy clients to `https` and add `tls_config` (CA/cert/key, TLS ≥1.2) delivered via systemd `LoadCredential`. 
- On `admin-vm`, keep Alloy behind `stunnel`, which terminates TLS and enforces mTLS on the public port. 
- The `stunnel` was used as a lightweight, low-dep TLS terminator vs heavier proxies.
Before, there was no encryption in the `alloy` client to server communication:
After this patch:
- The `stunnel` service performance was measured for 10 minutes after boot:
- Average CPU usage:   0.04%
- Max CPU usage:       1.18% at t=26s
- Average Memory:      4.25 MiB
- Max Memory:          7.57 MiB at t=2s
1. Check if the logs are being uploaded to remote server (e.g., Grafana)
2. The alloy service in both clients (all VMs except admin-vm), and server (admin-vm) should be …

Enable TLS for alloy client to server
